### ISSUE TITLE
`infra/helper.py fuzzbench_build_fuzzers` fails

### ISSUE THREAD

**Issue by neuschaefer** [google/oss-fuzz#10043]
In my attempt to test an oss-fuzz configuration locally, I tried to use `infra/helper.py fuzzbench_build_fuzzers`, with the known-good libpng project, but it failed:

```
[jn@nixos:~/fuzz/oss-fuzz]$ infra/helper.py fuzzbench_build_fuzzers libpng
Cloning into '/tmp/tmp2ts8yanp/fuzzbench'...
remote: Enumerating objects: 840, done.
remote: Counting objects: 100% (840/840), done.
remote: Compressing objects: 100% (675/675), done.
remote: Total 840 (delta 291), reused 437 (delta 130), pack-reused 0
Receiving objects: 100% (840/840), 21.51 MiB | 11.36 MiB/s, done.
Resolving deltas: 100% (291/291), done.
Error response from daemon: No such image: gcr.io/oss-fuzz-base/base-builder-fuzzbench:latest
Traceback (most recent call last):
  File "/home/jn/fuzz/oss-fuzz/infra/helper.py", line 1687, in <module>
    sys.exit(main())
  File "/home/jn/fuzz/oss-fuzz/infra/helper.py", line 187, in main
    result = fuzzbench_build_fuzzers(args)
  File "/home/jn/fuzz/oss-fuzz/infra/helper.py", line 956, in fuzzbench_build_fuzzers
    subprocess.run([
  File "/nix/store/lyyf8kvn8fbgvwl9cypallvv032g47lr-python3-3.10.9/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker', 'tag', 'gcr.io/oss-fuzz-base/base-builder-fuzzbench', 'gcr.io/oss-fuzz-base/base-builder']' returned non-zero exit status 1.
```

System information:
- NixOS
- `Docker version 20.10.21, build v20.10.21`

## Expected outcome

- I am able to run `infra/helper.py fuzzbench_build_fuzzers` followed by `infra/helper.py fuzzbench_run_fuzzer`
- Or, alternatively: `fuzzbench_build_fuzzers` and `fuzzbench_run_fuzzer` are not suggested in `infra/helper.py --help` output

**Comment by jonathanmetzman** [comment]
This isn't really a supported flag. Does the regular build_fuzzers work for you?

**Comment by neuschaefer** [comment]
Yes, `build_fuzzers` and `run_fuzzer` work for me. I think they previously didn't work because I didn't use them correctly, but that is now resolved.
