### ISSUE TITLE
Issue 58113 (opensc): Unusable traces pointing to linked library

### ISSUE THREAD

**Issue by xhanulik** [google/oss-fuzz#10375]
Lately, we received issue 58113 (https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58113) with quite unusable traces

```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
	  #0 0x5318e6 in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:69:3
	  #1 0x795693544c0d in CRYPTO_zalloc
```

pointing to some function from a linked library (OpenSSL). However, the issue was hidden in the actual tested project, not the linked library. Is there something that can be done about it, or is it a problem regarding the underlying `libFuzzer` engine?

**Comment by jonathanmetzman** [comment]
>However, the issue was hidden in the actual tested project

Sorry, could you clarify what you mean by this?

**Comment by xhanulik** [comment]
> > However, the issue was hidden in the actual tested project
> 
> Sorry, could you clarify what you mean by this?

Of course. I think it is problematic that the report does not show the entire trace starting from the fuzz target, but only the 'originator' of the memory leak.

This particular problem concerns an object created in opensc using an API from a linked library which was then not released. However, the trace contains only the last step `CRYPTO_zalloc`, which is probably some allocating function inside the linked library. Then the trace does not continue to the point where the object was created in opensc and the fuzz target, from which it got there.

**Comment by jonathanmetzman** [comment]
Thanks!
So yes, this is a limitation of the LSAN tool we are using.
