### ISSUE TITLE
libreoffice build is broken

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1069]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #4: [build LNK] Executable/svidl
Step #4: [build SDI] sfx2/sdi/sfxslots
Step #4: =================================================================
Step #4: ==2288==ERROR: AddressSanitizer: alloc-dealloc-mismatch (operator new [] vs operator delete) on 0x619000000f80
Step #4:     #0 0x51a360 in operator delete(void*) /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:149
Step #4:     #1 0x564d32 in operator() /usr/local/bin/../include/c++/v1/memory:2282:5
Step #4:     #2 0x564d32 in reset /usr/local/bin/../include/c++/v1/memory:2595
Step #4:     #3 0x564d32 in ~unique_ptr /usr/local/bin/../include/c++/v1/memory:2549
Step #4:     #4 0x564d32 in SvStream::~SvStream() /src/libreoffice/tools/source/stream/stream.cxx:371
Step #4:     #5 0x573288 in SvFileStream::~SvFileStream() /src/libreoffice/tools/source/stream/strmunx.cxx:298:1
Step #4:     #6 0x522b61 in operator() /usr/local/bin/../include/c++/v1/memory:2282:5
Step #4:     #7 0x522b61 in reset /usr/local/bin/../include/c++/v1/memory:2595
Step #4:     #8 0x522b61 in ~unique_ptr /usr/local/bin/../include/c++/v1/memory:2549
Step #4:     #9 0x522b61 in SvTokenStream::~SvTokenStream() /src/libreoffice/idl/source/cmptools/lex.cxx:93
Step #4:     #10 0x549331 in SvIdlDataBase::ReadIdFile(rtl::OString const&) /src/libreoffice/idl/source/prj/database.cxx:264:1
Step #4:     #11 0x549c89 in SvIdlDataBase::ReadIdFile(rtl::OString const&) /src/libreoffice/idl/source/prj/database.cxx:254:27
Step #4:     #12 0x55607f in SvIdlParser::ReadModuleBody(SvMetaModule&) /src/libreoffice/idl/source/prj/parser.cxx:65:24
Step #4:     #13 0x555b3a in SvIdlParser::ReadModuleHeader(SvMetaModule&) /src/libreoffice/idl/source/prj/parser.cxx:52:5
Step #4:     #14 0x555579 in SvIdlParser::ReadSvIdl(rtl::OUString const&) /src/libreoffice/idl/source/prj/parser.cxx:42:9
Step #4:     #15 0x542853 in ReadIdl(SvIdlWorkingBase*, SvCommand const&) /src/libreoffice/idl/source/prj/command.cxx:125:21
Step #4:     #16 0x5539eb in main /src/libreoffice/idl/source/prj/svidl.cxx:128:9
Step #4:     #17 0x2b67256ac82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
Step #4:     #18 0x41dd98 in _start (/work/workdir/LinkTarget/Executable/svidl+0x41dd98)
Step #4: 
Step #4: 0x619000000f80 is located 0 bytes inside of 1024-byte region [0x619000000f80,0x619000001380)
Step #4: allocated by thread T0 here:
Step #4:     #0 0x519798 in operator new[](unsigned long) /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:95
Step #4:     #1 0x564a2a in SvStream::SetBufferSize(unsigned short) /src/libreoffice/tools/source/stream/stream.cxx:417:24
Step #4:     #2 0x572168 in SvFileStream::SvFileStream(rtl::OUString const&, StreamMode) /src/libreoffice/tools/source/stream/strmunx.cxx:278:5
Step #4:     #3 0x522975 in SvTokenStream::SvTokenStream(rtl::OUString const&) /src/libreoffice/idl/source/cmptools/lex.cxx:85:22
Step #4:     #4 0x549284 in SvIdlDataBase::ReadIdFile(rtl::OString const&) /src/libreoffice/idl/source/prj/database.cxx:148:19
Step #4:     #5 0x549c89 in SvIdlDataBase::ReadIdFile(rtl::OString const&) /src/libreoffice/idl/source/prj/database.cxx:254:27
Step #4:     #6 0x55607f in SvIdlParser::ReadModuleBody(SvMetaModule&) /src/libreoffice/idl/source/prj/parser.cxx:65:24
Step #4:     #7 0x555b3a in SvIdlParser::ReadModuleHeader(SvMetaModule&) /src/libreoffice/idl/source/prj/parser.cxx:52:5
Step #4:     #8 0x555579 in SvIdlParser::ReadSvIdl(rtl::OUString const&) /src/libreoffice/idl/source/prj/parser.cxx:42:9
Step #4:     #9 0x542853 in ReadIdl(SvIdlWorkingBase*, SvCommand const&) /src/libreoffice/idl/source/prj/command.cxx:125:21
Step #4:     #10 0x5539eb in main /src/libreoffice/idl/source/prj/svidl.cxx:128:9
Step #4:     #11 0x2b67256ac82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
Step #4: 
Step #4: SUMMARY: AddressSanitizer: alloc-dealloc-mismatch /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:149 in operator delete(void*)
Step #4: ==2288==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
Step #4: ==2288==ABORTING
Step #4: make[1]: *** [/work/workdir/SdiTarget/sfx2/sdi/sfxslots] Error 1
Step #4: /src/libreoffice/solenv/gbuild/SdiTarget.mk:25: recipe for target '/work/workdir/SdiTarget/sfx2/sdi/sfxslots' failed
```

**Comment by Dor1s** [comment]
//cc @caolanm

**Comment by inferno-chromium** [comment]
seems fixed now.
