### ISSUE TITLE
NOTE: fuzzing was not performed, you have only executed the target code on a fixed set of inputs.

### ISSUE THREAD

**Issue by MageWeiG** [google/oss-fuzz#10721]
I run a fuzzer named AddrListFixFuzzer in project joni. And then, I get a crash.
```
#11051	NEW    cov: 1555 ft: 3535 corp: 253/1582b lim: 8 exec/s: 3683 rss: 854Mb L: 8/8 MS: 2 CopyPart-Custom-
Unknown escape \j is ignored
Unknown escape \j is ignored
regular expression has redundant nested repeat operator ?? ????/
regular expression has redundant nested repeat operator ?? ????%/
regular expression has redundant nested repeat operator ?? ????%/
regular expression has ']' without escape
regular expression has ']' without escape
regular expression has redundant nested repeat operator * /**"*/
regular expression has redundant nested repeat operator * /**"*/

== Java Exception: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.jcodings.specific.UTF8Encoding.length(UTF8Encoding.java:30)
	at org.jcodings.specific.BaseUTF8Encoding.mbcToCode(BaseUTF8Encoding.java:90)
	at org.jcodings.specific.UTF8Encoding.mbcToCode(UTF8Encoding.java:22)
	at org.joni.ScannerSupport.peek(ScannerSupport.java:151)
	at org.joni.ScannerSupport.peekIs(ScannerSupport.java:155)
	at org.joni.Lexer.greedyCheck(Lexer.java:1279)
	at org.joni.Lexer.fetchTokenFor_repeat(Lexer.java:745)
	at org.joni.Lexer.fetchToken(Lexer.java:1202)
	at org.joni.Parser.parseRegexp(Parser.java:1383)
	at org.joni.Analyser.compile(Analyser.java:78)
	at org.joni.Regex.<init>(Regex.java:169)
	at org.joni.Regex.<init>(Regex.java:148)
	at org.joni.Regex.<init>(Regex.java:134)
	at org.joni.Regex.<init>(Regex.java:114)
	at AddrListFixFuzzer.fuzzerTestOneInput(AddrListFixFuzzer.java:31)
DEDUP_TOKEN: 32f98042ce9d4e63
== libFuzzer crashing input ==
MS: 10 ChangeByte-Custom-PersAutoDict-Custom-CopyPart-Custom-ChangeByte-Custom-ChangeBinInt-Custom- DE: "\003\000\000\000"-; base unit: b1edea938add1307d7d1151cfef43e1213ef96b8
0xfd,0xff,0xff,0xc5,0xff,0xff,0xfb,0x1e,
\375\377\377\305\377\377\373\036
artifact_prefix='./'; Test unit written to ./crash-14f348f937f29174dccf760c6869365283abc2bf
Base64: /f//xf//+x4=
reproducer_path='.'; Java reproducer written to ./Crash_14f348f937f29174dccf760c6869365283abc2bf.java
```
This seems like an out-of-bounds type of error, but when I get ready to view the error message (`python3 infra/helper.py reproduce joni AddrListFixFuzzer ./build/out/joni/Crash_14f348f937f29174dccf760c6869365283abc2bf.java`), the problem arises. I don't know how to operate the back, can you help me? Thank you very much。
```
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
character class has ']' without escape
Executed /testcase in 5636 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

**Comment by DavidKorczynski** [comment]
This is a case of an unreproducible crash found by a fuzzer. This is likely due to some statefulness of the target code.

**Comment by MageWeiG** [comment]
Thankyou.
