### ISSUE TITLE
Keycloak issues

### ISSUE THREAD

**Issue by AdamKorcz** [google/oss-fuzz#10764]
I have a few issues with the Keycloak fuzzers:

1. I don't have runtime stats available; I get a 404 on https://oss-fuzz.com/fuzzer-stats?group_by=by-fuzzer&date_start=2023-07-24&date_end=2023-07-30&fuzzer=libFuzzer&job=libfuzzer_asan_keycloak&project=keycloak
2. Fuzzers added around 1 week ago still do not have coverage.
3. The coverage is not increasing a lot. Judging from some of the fuzzers, the coverage should increase fairly easily over time, for example case 3, 4 and 5 of this fuzzer: https://storage.googleapis.com/oss-fuzz-coverage/keycloak/reports/20230731/linux/default/SamlParserFuzzer.java.html#L41

**Comment by AdamKorcz** [comment]
This is probably related to https://github.com/google/oss-fuzz/issues/10798

**Comment by oliverchang** [comment]
Looking at keycloak logs, I'm seeing:
```
Component revisions (build r202308050622):
Keycloak: 339619816a87550bb2c98c933e80c9208b3845f3
Cncf-fuzzing: 1d3899ee82a851150fe51889504f55c22578f34c

Bot name: oss-fuzz-linux-zone7-host-fvhq-8
Return code: 1

Command: /mnt/scratch0/clusterfuzz/resources/platform/linux/unshare -c -n /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_keycloak_57926c1c50a17652a51445c3f882a84093944412/revisions/AuthorizationTokenServiceFuzzer -timeout=25 -rss_limit_mb=2560 -max_len=95 -fork=2 -artifact_prefix=/mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/ -max_total_time=6500 -print_final_stats=1 /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases-disk/temp-931/new /mnt/scratch0/clusterfuzz/bot/inputs/data-bundles/keycloak_AuthorizationTokenServiceFuzzer
Time ran: 15.73300290107727

OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
INFO: Loaded 371 hooks from com.code_intelligence.jazzer.runtime.TraceCmpHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.TraceDivHooks
INFO: Loaded 2 hooks from com.code_intelligence.jazzer.runtime.TraceIndirHooks
INFO: Loaded 4 hooks from com.code_intelligence.jazzer.runtime.NativeLibHooks
INFO: Loaded 5 hooks from com.code_intelligence.jazzer.sanitizers.Deserialization
INFO: Loaded 7 hooks from com.code_intelligence.jazzer.sanitizers.ExpressionLanguageInjection
INFO: Loaded 70 hooks from com.code_intelligence.jazzer.sanitizers.LdapInjection
INFO: Loaded 50 hooks from com.code_intelligence.jazzer.sanitizers.NamingContextLookup
INFO: Loaded 1 hooks from com.code_intelligence.jazzer.sanitizers.OsCommandInjection
INFO: Loaded 148 hooks from com.code_intelligence.jazzer.sanitizers.ReflectiveCall
INFO: Loaded 8 hooks from com.code_intelligence.jazzer.sanitizers.RegexInjection
INFO: Loaded 16 hooks from com.code_intelligence.jazzer.sanitizers.RegexRoadblocks
INFO: Loaded 3 hooks from com.code_intelligence.jazzer.sanitizers.ServerSideRequestForgery
INFO: Loaded 19 hooks from com.code_intelligence.jazzer.sanitizers.SqlInjection
INFO: Loaded 6 hooks from com.code_intelligence.jazzer.sanitizers.XPathInjection
INFO: Instrumented AuthorizationTokenServiceFuzzer (took 226 ms, size +10%)
Exception in thread "main" java.lang.UnsupportedClassVersionError: AuthorizationTokenServiceFuzzer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
	at com.code_intelligence.jazzer.driver.FuzzTargetFinder.findFuzzTarget(FuzzTargetFinder.java:62)
	at com.code_intelligence.jazzer.driver.Driver.start(Driver.java:146)
	at com.code_intelligence.jazzer.Jazzer.start(Jazzer.java:104)
	at com.code_intelligence.jazzer.Jazzer.main(Jazzer.java:70)
cf::fuzzing_strategies: fork:2,random_max_len:1
```

**Comment by DavidKorczynski** [comment]
Awesome, Thanks @oliverchang  -- solving the issue you pasted solved the problem! it was also possible to get stats by looking at the cloud storage directly rather than through oss-fuzz.com (ref https://github.com/google/oss-fuzz/issues/10798)
