### ISSUE TITLE
CiFuzz fails on "Upload Sarif" step

### ISSUE THREAD

**Issue by antonmedv** [google/oss-fuzz#10915]
Hi, 

I integrated CiFuzz into expr project. 

But workflow fails on "Upload Sarif" step: https://github.com/antonmedv/expr/actions/runs/6060580613/job/16444899676?pr=429

```
Run github/codeql-action/upload-sarif@v2
Could not determine current commit SHA using git. Continuing with data from user input or environment.
Error: Path does not exist: cifuzz-sarif/results.sarif
Error: Path does not exist: cifuzz-sarif/results.sarif
    at getSarifFilePaths (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:140:15)
    at Object.uploadFromActions (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:135:30)
    at run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:50:47)
    at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:72:[9](https://github.com/antonmedv/expr/actions/runs/6060580613/job/16444899676?pr=429#step:7:10))
Could not determine current commit SHA using git. Continuing with data from user input or environment.
```

**Comment by antonmedv** [comment]
Figured it out. I was missing `output-sarif: true`.
