### ISSUE TITLE
OSS-Fuzz helper breaks on PRs made in github editor

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#10955]
This is my theory for the breakage here:
https://github.com/google/oss-fuzz/pull/10947
```
Traceback (most recent call last):
  File "infra/pr_helper.py", line 297, in <module>
    main()
  File "infra/pr_helper.py", line [12](https://github.com/google/oss-fuzz/actions/runs/6170602264/job/16747187992?pr=10947#step:7:13)3, in main
    contributors = github.get_past_contributors(project_path)
  File "infra/pr_helper.py", line 246, in get_past_contributors
    login = commit['author']['login']
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

**Comment by jonathanmetzman** [comment]
CC @hogo6002
