### ISSUE TITLE
assert due to negative max_total_time is triggered

### ISSUE THREAD

**Issue by ligurio** [google/oss-fuzz#11017]
GH workflow with fuzzing PUC Rio Lua [^1] is failed due to negative `max_total_time` (see assert in code [^2]):

```
2023-09-26 10:00:12,722 - root - INFO - Starting fuzzing
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 96, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 92, in main
    return run_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 62, in run_fuzzers_entrypoint
    result = run_fuzzers.run_fuzzers(config)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 316, in run_fuzzers
    if not fuzz_target_runner.run_fuzz_targets():
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 131, in run_fuzz_targets
    result = self.run_fuzz_target(target)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 259, in run_fuzz_target
    return fuzz_target_obj.fuzz()
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 195, in fuzz
    result = engine_impl.fuzz(self.target_path, options, artifacts_dir,
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 278, in fuzz
    fuzz_result = runner.fuzz(
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py", line [40](https://github.com/ligurio/lua-c-api-tests/actions/runs/6311004556/job/17134116743?pr=51#step:5:41)1, in fuzz
    return LibFuzzerCommon.fuzz(self, corpus_directories, fuzz_timeout,
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py", line 200, in fuzz
    assert max_total_time > 0
AssertionError
```

Full log: https://github.com/ligurio/lua-c-api-tests/actions/runs/6311004556/job/17134116743?pr=51

[^1]: https://github.com/google/oss-fuzz/tree/master/projects/lua
[^2]: https://github.com/google/clusterfuzz/blob/298cecc64af7ecbb1c528dd1789e999caa6af825/src/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py#L125

**Comment by ligurio** [comment]
this happened because timeout in GH workflow (`fuzz-seconds`) [^1] is equal to timeout in https://github.com/google/clusterfuzz/blob/master/src/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py#L84

[^1]: https://github.com/ligurio/lua-c-api-tests/blob/e4c2a46510a72baf6e3741dbd7529e74aaf698e6/.github/workflows/oss-fuzz.yml#L53
[^2]: https://github.com/google/clusterfuzz/blob/298cecc64af7ecbb1c528dd1789e999caa6af825/src/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py#L84

I suspect it is better to check this earlier in GH action.

**Comment by jonathanmetzman** [comment]
Let me take a look at this.
