### ISSUE TITLE
[memcached] Coverage build failure

### ISSUE THREAD

**Issue by bxa-stripe** [google/oss-fuzz#11154]
Similar to a few other previous projects (#10717, #11081, #11010), `memcached` is failing to build coverage:
```
Step #5: [/corpus/fuzzer_proxy.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzzer_proxy.zip or
Step #5:         /corpus/fuzzer_proxy.zip.zip, and cannot find /corpus/fuzzer_proxy.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzzer_proxy. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
```

The fuzzer itself appears to be [running](https://oss-fuzz.com/fuzzer-stats?project=memcached&fuzzer=libFuzzer_memcached_fuzzer_proxy&job=libfuzzer_asan_memcached&group_by=by-day), and I see a corpus in `memcached-corpus.clusterfuzz-external.appspot.com`. I also can't replicate this issue locally. Any ideas?

**Comment by oliverchang** [comment]
digging into this one, it looks like our corpus pruning jobs are timing out:

```
2023-11-12 21:39:48,353 - run_bot - ERROR - Merging new testcases timed out.
NoneType: None
2023-11-12 21:39:48,361 - run_bot - WARNING - Merge failed.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 234, in _merge_new_units
    libfuzzer.DEFAULT_MERGE_TIMEOUT))
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 450, in _minimize_corpus_two_step
    reproducers_dir, max_time)
  File "/mnt/scratch0/clusterfuzz/src/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 531, in minimize_corpus
    raise MergeError('Merging new testcases failed.')
clusterfuzz._internal.bot.fuzzers.libFuzzer.engine.MergeError: Merging new testcases failed.
```

Seeing what we can do to mitigate this

**Comment by bxa-stripe** [comment]
Hey @oliverchang, was there any movement on this?

**Comment by silvergasp** [comment]
Looks like this is now an issue with surrealdb as well https://oss-fuzz-build-logs.storage.googleapis.com/index.html#surrealdb. Looks like there is a similar error;
```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/fuzz_structured_executor.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/fuzz_structured_executor.zip or
Step #5:         /corpus/fuzz_structured_executor.zip.zip, and cannot find /corpus/fuzz_structured_executor.zip.ZIP, period.
Step #5: Failed to unpack the corpus for fuzz_structured_executor. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image surrealdb
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage surrealdb
Step #5: python infra/helper.py coverage surrealdb
Step #5: ********************************************************************
```

**Comment by bxa-stripe** [comment]
👋 Are there any updates on this issue? Seems like several other projects are experiencing this.

**Comment by tyler92** [comment]
Same issue for [openbabel](https://oss-fuzz-build-logs.storage.googleapis.com/log-e5185bf8-4b3d-4519-a471-a4161fae9dcf.txt) and [tomlplusplus](https://oss-fuzz-build-logs.storage.googleapis.com/log-07509b3f-3987-42b3-aa57-d3770e104dbd.txt).
