### ISSUE TITLE
OpenSSL Fuzz Introspector build failure

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#11181]
A few commits were merged to update OpenSSL on November 1. Since then, it seems the Fuzz Introspector build has been failing. The error isn't making much sense to me:
```
Step #6 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 154, in <module>
Step #6 - "compile-libfuzzer-introspector-x86_64":     main()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 138, in main
Step #6 - "compile-libfuzzer-introspector-x86_64":     return_code = commands.run_analysis_on_dir(
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/commands.py", line 61, in run_analysis_on_dir
Step #6 - "compile-libfuzzer-introspector-x86_64":     introspection_proj.load_data_files(parallelise, correlation_file)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/analysis.py", line 95, in load_data_files
Step #6 - "compile-libfuzzer-introspector-x86_64":     for idx in return_dict:
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/multiprocessing/managers.py", line 1052, in __next__
Step #6 - "compile-libfuzzer-introspector-x86_64":     return self._callmethod('__next__', args)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
Step #6 - "compile-libfuzzer-introspector-x86_64":     kind, result = conn.recv()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 250, in recv
Step #6 - "compile-libfuzzer-introspector-x86_64":     buf = self._recv_bytes()
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
Step #6 - "compile-libfuzzer-introspector-x86_64":     buf = self._recv(4)
Step #6 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
Step #6 - "compile-libfuzzer-introspector-x86_64":     chunk = read(handle, remaining)
Step #6 - "compile-libfuzzer-introspector-x86_64": ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by DavidKorczynski** [comment]
I think the error is a resource exhaustion, most likely some timeout happening or some memory exhaustion.

I think it happened after https://github.com/google/oss-fuzz/pull/11171 and the reason being more code was added to the analysis.

I think Fuzz Introspector may struggle anyways with analysing multiple versions of the source code in "one analysis". Fuzz Introspector would work better if instead of building 4 different versions only a single version is build: https://github.com/google/oss-fuzz/blob/c886b35fa6515c555c8ae36543a7d897964eff1d/projects/openssl/build.sh#L67-L74 

From a code coverage perspective/completeness perspective how much would we lose if, in fuzz introspector runs, we limit the `build_fuzzers` to a single branch?

**Comment by kroeckx** [comment]
I'm fine with the introspector doing only the master branch.

**Comment by DavidKorczynski** [comment]
Fix in https://github.com/google/oss-fuzz/pull/11201

Will close this once the introspector report comes up

**Comment by kroeckx** [comment]
The report is available, closing
