### ISSUE TITLE
Fuzz issue 63900 compile failure:  is fuzzer system failure

### ISSUE THREAD

**Issue by davea42** [google/oss-fuzz#11262]
This failure made sense a few weeks ago. But the source      of src/libdwarf/fuzz/fuzz_crc.c was corrected
weeks ago, and in addition to adding
```
#ifndef O_BINARY
#define O_BINARY 0
#endif

```
to fix the bug
I altered the source to have `O_RDONLY  | O_BINARY` (note the space before and after the or-bar)

But below there is no such space at the or-bar and the build fails. Meaning the build process is NOT
using the top-of-trunk fuzz_crc.c but is instead building a weeks-old source.

pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_crc.c -o /workspace/out/afl-address-x86_64/fuzz_crc ./src/lib/libdwarf/libdwarf.a -lz
```
Step #3 - "compile-afl-address-x86_64": ␛[1m/src/libdwarf/fuzz/fuzz_crc.c:54:37: ␛[0m␛[0;1;31merror: ␛[0m␛[1muse of undeclared identifier 'O_BINARY'␛[0m
Step #3 - "compile-afl-address-x86_64":   fuzz_fd = open(filename, O_RDONLY|O_BINARY);
Step #3 - "compile-afl-address-x86_64": ␛[0;1;32m                                    ^
Step #3 - "compile-afl-address-x86_64": ␛[0m1 error generated.
```

**Comment by DavidKorczynski** [comment]
The issue is no longer with the `fuzz_crc.c` but the `fuzz_debuglink` now. 

The build is failing now with [this log](https://oss-fuzz-build-logs.storage.googleapis.com/log-0c9ea661-5587-4df8-88ea-ac1ab699d120.txt):


```bash
Step #3 - "compile-afl-address-x86_64": + for fuzzFile in $FUZZER_DIR/fuzz*.c
Step #3 - "compile-afl-address-x86_64": ++ basename /src/libdwarf/fuzz/fuzz_aranges.c .c
Step #3 - "compile-afl-address-x86_64": + fuzzName=fuzz_aranges
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_aranges.c -o /workspace/out/afl-address-x86_64/fuzz_aranges ./src/lib/libdwarf/libdwarf.a -lz
Step #3 - "compile-afl-address-x86_64": + for fuzzFile in $FUZZER_DIR/fuzz*.c
Step #3 - "compile-afl-address-x86_64": ++ basename /src/libdwarf/fuzz/fuzz_crc.c .c
Step #3 - "compile-afl-address-x86_64": + fuzzName=fuzz_crc
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_crc.c -o /workspace/out/afl-address-x86_64/fuzz_crc ./src/lib/libdwarf/libdwarf.a -lz
Step #3 - "compile-afl-address-x86_64": + for fuzzFile in $FUZZER_DIR/fuzz*.c
Step #3 - "compile-afl-address-x86_64": ++ basename /src/libdwarf/fuzz/fuzz_crc_32.c .c
Step #3 - "compile-afl-address-x86_64": + fuzzName=fuzz_crc_32
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_crc_32.c -o /workspace/out/afl-address-x86_64/fuzz_crc_32 ./src/lib/libdwarf/libdwarf.a -lz
Step #3 - "compile-afl-address-x86_64": + for fuzzFile in $FUZZER_DIR/fuzz*.c
Step #3 - "compile-afl-address-x86_64": ++ basename /src/libdwarf/fuzz/fuzz_debug_addr_access.c .c
Step #3 - "compile-afl-address-x86_64": + fuzzName=fuzz_debug_addr_access
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_debug_addr_access.c -o /workspace/out/afl-address-x86_64/fuzz_debug_addr_access ./src/lib/libdwarf/libdwarf.a -lz
Step #3 - "compile-afl-address-x86_64": + for fuzzFile in $FUZZER_DIR/fuzz*.c
Step #3 - "compile-afl-address-x86_64": ++ basename /src/libdwarf/fuzz/fuzz_debug_str.c .c
Step #3 - "compile-afl-address-x86_64": + fuzzName=fuzz_debug_str
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_debug_str.c -o /workspace/out/afl-address-x86_64/fuzz_debug_str ./src/lib/libdwarf/libdwarf.a -lz
Step #3 - "compile-afl-address-x86_64": + for fuzzFile in $FUZZER_DIR/fuzz*.c
Step #3 - "compile-afl-address-x86_64": ++ basename /src/libdwarf/fuzz/fuzz_debuglink.c .c
Step #3 - "compile-afl-address-x86_64": + fuzzName=fuzz_debuglink
Step #3 - "compile-afl-address-x86_64": + /src/aflplusplus/afl-clang-fast -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope /usr/lib/libFuzzingEngine.a -I../src/lib/libdwarf/ /src/libdwarf/fuzz/fuzz_debuglink.c -o /workspace/out/afl-address-x86_64/fuzz_debuglink ./src/lib/libdwarf/libdwarf.a -lz
Step #3 - "compile-afl-address-x86_64": [1m/src/libdwarf/fuzz/fuzz_debuglink.c:47:38: [0m[0;1;31merror: [0m[1muse of undeclared identifier 'O_BINARY'[0m
Step #3 - "compile-afl-address-x86_64":   fuzz_fd = open(filename, O_RDONLY |O_BINARY);
Step #3 - "compile-afl-address-x86_64": [0;1;32m                                     ^
```

The issue is in `fuzz_debuglink.c` here: https://github.com/davea42/libdwarf-code/blob/528f7495b63d73ec46c153be8770753f4b6869f2/fuzz/fuzz_debuglink.c#L47

**Comment by davea42** [comment]
Ok, that was wrong too. Missing #ifndef #define of O_BINARY. My bad.

I've checked through all of them just now and I believe all are now correct.
Just did a cc -c on all of them and all compile now.

**Comment by DavidKorczynski** [comment]
I just checked the build. I can confirm the compilation goes well, but, the `fuzz_debuglink.c` is failing at the first instance of the fuzzer running with:

```bash

libdwarf is unable to record error DW_DLE_FILE_WRONG_TYPE(412). Not an object type we recognize. No error argument or handler available
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1233==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000038 (pc 0x00000056d390 bp 0x7ffd21801eb0 sp 0x7ffd21801e70 T0)
==1233==The signal is caused by a READ memory access.
==1233==Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
    #0 0x56d390 in dwarf_add_debuglink_global_path /src/libdwarf/src/lib/libdwarf/dwarf_debuglink.c:1062:28
    #1 0x56a115 in LLVMFuzzerTestOneInput /src/libdwarf/fuzz/fuzz_debuglink.c:72:9
    #2 0x43dde3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #3 0x43f194 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:804:3
    #4 0x43f669 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
    #5 0x42eccf in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #6 0x458322 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #7 0x7feed7f59082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: e678fe54a5d2c2092f8e47eb0b33105e380f7340)
    #8 0x41f70d in _start (/tmp/not-out/tmpzl7d7bao/fuzz_debuglink+0x41f70d)
```


This means the build will be declared not-working. To fix this, could we set a check on `dbg` here: https://github.com/davea42/libdwarf-code/blob/main/fuzz/fuzz_debuglink.c#L72-L77 ?

**Comment by davea42** [comment]
This Sanitizer failure is an instance of finding a bug in libdwarf.
Fuzzer finding yet another genuine library bug.

dwarf_add_debuglink_global_path()
fails to check for a null input argument which is required to be non-null
and a legitimate struct pointer (checked via a magic number).

Yikes. Been wrong for a long time. Will fix immediately.
David Anderson

**Comment by davea42** [comment]
dwarf_debuglink.c tested and passed and pushed to github.

**Comment by DavidKorczynski** [comment]
Great @davea42 -- I can see the libdwarf build is successfully building again! Closing this issue.
