### ISSUE TITLE
CIFuzz seems to fail with "TypeError: argument of type 'NoneType' is not iterable" occasionally when writing SARIF files

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#11423]
It was spotted in https://github.com/systemd/systemd/pull/30661: https://github.com/systemd/systemd/actions/runs/7361563279/job/20039027110
```
2023-12-30T02:48:24.2335228Z 2023-12-30 02:48:24,233 - root - INFO - Writing sarif results.
2023-12-30T02:48:24.2559140Z 2023-12-30 02:48:24,252 - root - INFO - state: fuzz-resource-record.c frames [[<clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb4592b0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfedb97c40>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb3f4520>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb3f4ac0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb3f4400>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe9241fa0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe9241fd0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb3f4310>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb3f4640>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfeb3f4850>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6400>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6220>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d61c0>], [<clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6070>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d60a0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6460>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6160>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6040>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d60d0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6190>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6100>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6550>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d64f0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d6130>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d65b0>, <clusterfuzz._internal.crash_analysis.stack_parsing.stack_parser.StackFrame object at 0x7fdfe91d65e0>]], [None, 'raise', 'abort', 'log_assert_failed', 'LLVMFuzzerTestOneInput', 'fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned int)', 'fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned int, bool, fuzzer::InputInfo*, bool, bool*)', 'fuzzer::Fuzzer::MutateAndTestOne()', 'fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&)', 'fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned int))', 'main', '__libc_start_main', '_start']
2023-12-30T02:48:24.2581892Z Traceback (most recent call last):
2023-12-30T02:48:24.2582896Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 96, in <module>
2023-12-30T02:48:24.2583709Z     sys.exit(main())
2023-12-30T02:48:24.2584484Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 92, in main
2023-12-30T02:48:24.2585334Z     return run_fuzzers_entrypoint()
2023-12-30T02:48:24.2586343Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 62, in run_fuzzers_entrypoint
2023-12-30T02:48:24.2587311Z     result = run_fuzzers.run_fuzzers(config)
2023-12-30T02:48:24.2588216Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 316, in run_fuzzers
2023-12-30T02:48:24.2589075Z     if not fuzz_target_runner.run_fuzz_targets():
2023-12-30T02:48:24.2590034Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 154, in run_fuzz_targets
2023-12-30T02:48:24.2591025Z     write_fuzz_result_to_sarif(result, target_path, self.workspace)
2023-12-30T02:48:24.2592183Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 162, in write_fuzz_result_to_sarif
2023-12-30T02:48:24.2593264Z     sarif_utils.write_stacktrace_to_sarif(fuzz_result.stacktrace, target_path,
2023-12-30T02:48:24.2594487Z   File "/opt/oss-fuzz/infra/cifuzz/sarif_utils.py", line 242, in write_stacktrace_to_sarif
2023-12-30T02:48:24.2595417Z     data = get_sarif_data(stacktrace, target_path)
2023-12-30T02:48:24.2596333Z   File "/opt/oss-fuzz/infra/cifuzz/sarif_utils.py", line 209, in get_sarif_data
2023-12-30T02:48:24.2597194Z     error_source_info = get_error_source_info(crash_info)
2023-12-30T02:48:24.2598185Z   File "/opt/oss-fuzz/infra/cifuzz/sarif_utils.py", line 178, in get_error_source_info
2023-12-30T02:48:24.2599013Z     frame = get_error_frame(crash_info)
2023-12-30T02:48:24.2599896Z   File "/opt/oss-fuzz/infra/cifuzz/sarif_utils.py", line 171, in get_error_frame
2023-12-30T02:48:24.2600689Z     if state in frame.function_name:
2023-12-30T02:48:24.2601382Z TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jonathanmetzman** [comment]
I think this was fixed in https://github.com/google/oss-fuzz/pull/11710/files
What do you think?

**Comment by evverx** [comment]
I haven't seen those backtrace lately so it seems they are gone. Closing. (I'll reopen the issue should I see them again).
