### ISSUE TITLE
java base image is failing to build

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#11613]
When building the java base image I run into this issue:

```sh
8.552 + cat
8.554 + bazel build //src/main/java/com/code_intelligence/jazzer:jazzer_standalone_deploy.jar //deploy:jazzer-api //launcher:jazzer
8.562 2024/02/18 21:37:30 Using unreleased version at commit 8482c7cf494686eb7498cec6ee58dad03b07ef0d
8.562 2024/02/18 21:37:30 Downloading https://storage.googleapis.com/bazel-builds/artifacts/ubuntu1404/8482c7cf494686eb7498cec6ee58dad03b07ef0d/bazel...
10.85 Extracting Bazel installation...
13.22 Starting local Bazel server and connecting to it...
14.51 Loading: 
15.51 Loading: 
16.51 Loading: 
17.75 Loading: 
18.46 WARNING: Download from https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
18.46 INFO: Repository com_grail_bazel_toolchain instantiated at:
18.46   /src/jazzer/WORKSPACE.bazel:34:13: in <toplevel>
18.46 Repository rule http_archive defined at:
18.46   /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
18.47 ERROR: An error occurred during the fetch of repository 'com_grail_bazel_toolchain':
18.47    Traceback (most recent call last):
18.47   File "/root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
18.47           download_info = ctx.download_and_extract(
18.47 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp6596007316104794476/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
18.47 ERROR: /src/jazzer/WORKSPACE.bazel:34:13: fetching http_archive rule //external:com_grail_bazel_toolchain: Traceback (most recent call last):
18.47   File "/root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
18.47           download_info = ctx.download_and_extract(
18.47 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp6596007316104794476/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
18.48 ERROR: Error computing the main repository mapping: no such package '@com_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp6596007316104794476/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
------
Dockerfile:24
--------------------
  22 |     ENV JAZZER_API_PATH "/usr/local/lib/jazzer_api_deploy.jar"
  23 |     
  24 | >>> RUN install_java.sh

```

**Comment by DavidKorczynski** [comment]
Closing this as it's building again. https://github.com/google/oss-fuzz/issues/11623 supersedes this issue.
