### ISSUE TITLE
strongswan coverage not reported

### ISSUE THREAD

**Issue by tobiasbrunner** [google/oss-fuzz#1180]
I just noticed that there isn't any coverage reported for the `fuzz_certs` fuzz target of the strongSwan project. In the fuzzer stats I see the last coverage report was on Nov 19, 2017 (on Jan 25, 2018 there was an explicit "No coverage" reported, otherwise the related columns just show `--`). The global coverage report is also not available. Any idea why that is?

**Comment by tobiasbrunner** [comment]
Also, running `python infra/helper.py coverage strongswan fuzz_certs` results in:

    WARNING: No coverage file for *.sancov
    WARNING: No coverage file for /out/fuzz_certs
    ERROR: No valid coverage files given.

**Comment by inferno-chromium** [comment]
So, we were failing on generating coverage due to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=4538

```
Corpus pruning failed to generate coverage: INFO: Seed: 2987101981
INFO: Loaded 1 modules   (15790 guards): 15790 [0x898368, 0x8a7a20),
INFO:     1330 files found in /min
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 22154 bytes
INFO: seed corpus: files: 1330 min: 1b max: 22154b total: 855247b rss: 32Mb
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==1==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000051 (pc 0x0000004eb9b5 bp 0x7ffe0aeafaa0 sp 0x7ffe0aeafa70 T1)
==1==The signal is caused by a READ memory access.
==1==Hint: address points to the zero page.
    #0 0x4eb9b4 in asn1_length /src/strongswan/src/libstrongswan/asn1/asn1.c:257:12
    #1 0x4eec2b in iterate /src/strongswan/src/libstrongswan/asn1/asn1_parser.c:188:15
    #2 0x4ed464 in asn1_parse_algorithmIdentifier /src/strongswan/src/libstrongswan/asn1/asn1.c:672:9
    #3 0x4f93ad in rsa_pss_params_parse /src/strongswan/src/libstrongswan/credentials/keys/signature_params.c:290:12
    #4 0x4f9062 in signature_params_parse /src/strongswan/src/libstrongswan/credentials/keys/signature_params.c:181:9
    #5 0x52af61 in parse_certificate /src/strongswan/src/libstrongswan/plugins/x509/x509_cert.c:1409:10
    #6 0x52a7a8 in x509_cert_load /src/strongswan/src/libstrongswan/plugins/x509/x509_cert.c:2635:7
    #7 0x4733e2 in create /src/strongswan/src/libstrongswan/credentials/credential_factory.c:129:16
    #8 0x5593fa in load_from_blob /src/strongswan/src/libstrongswan/plugins/pem/pem_builder.c:428:10
    #9 0x558dfb in pem_load /src/strongswan/src/libstrongswan/plugins/pem/pem_builder.c:494:10
    #10 0x558f2f in pem_certificate_load /src/strongswan/src/libstrongswan/plugins/pem/pem_builder.c:524:9
    #11 0x4733e2 in create /src/strongswan/src/libstrongswan/credentials/credential_factory.c:129:16
    #12 0x42ceb7 in LLVMFuzzerTestOneInput /src/strongswan/fuzz/fuzz_certs.c:33:9
    #13 0x43a616 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:515:13
    #14 0x439f4b in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:440:3
    #15 0x43bb95 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:723:7
    #16 0x43be61 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:739:3
    #17 0x43168f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:754:6
    #18 0x42d000 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #19 0x7fab18aaa82f in __libc_start_main /build/glibc-bfm8X4/glibc-2.23/csu/../csu/libc-start.c:291
    #20 0x407aa8 in _start (/mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_strongswan_967bd11e72663b51012eac76b54d2551fbcf800b/coverage/fuzz_certs+0x407aa8)

UndefinedBehaviorSanitizer can not provide additional info.
==1==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000
artifact_prefix='./'; Test unit written to ./crash-39d378f33d6f45d38226bda663e52a03f2639a48
SanitizerCoverage: ./fuzz_certs.1.sancov: 2290 PCs written
```

Looks like you pushed a fix for this on master. I just forced a build now, so lets see if corpus pruning catches up to latest build and then generates coverage, otherwise, need to wait another day.

**Comment by inferno-chromium** [comment]
Now it works
https://oss-fuzz.com/v2/fuzzer-stats/by-fuzzer/2018-02-14/2018-02-20/fuzzer/libFuzzer_strongswan_fuzz_certs
https://oss-fuzz.com/coverage_report/fuzzer/libFuzzer_strongswan_fuzz_certs/2018-02-21

**Comment by tobiasbrunner** [comment]
Thanks.
