### ISSUE TITLE
[krb5] Missing target in coverage

### ISSUE THREAD

**Issue by pkillarjun** [google/oss-fuzz#12282]
`fuzz_profile.c` is missing in the coverage report.

You can argue probably it's not compiled, but I doubt that.

[fuzz_profile.c](https://github.com/krb5/krb5/blob/master/src/tests/fuzzing/fuzz_profile.c) source code  is available.

It should be copied as instructed in the [build file](https://github.com/krb5/krb5/blob/master/src/tests/fuzzing/oss-fuzz.sh#L20).

```bash
make
popd

# Copy fuzz targets and seed corpus to $OUT.
pushd src/tests/fuzzing

fuzzers=("fuzz_chpw" "fuzz_gss" "fuzz_json" "fuzz_krad" "fuzz_krb5_ticket"
        "fuzz_marshal_cred" "fuzz_marshal_princ" "fuzz_ndr" "fuzz_pac"
        "fuzz_profile" "fuzz_util")

for fuzzer in "${fuzzers[@]}"; do
    cp "$fuzzer" "$OUT/$fuzzer"

```

### When it goes missing:

* It is there on [2024/06/23](https://storage.googleapis.com/oss-fuzz-coverage/krb5/reports/20240623/linux/src/krb5/src/tests/fuzzing/report.html). 
* Gone [2024/06/24](https://storage.googleapis.com/oss-fuzz-coverage/krb5/reports/20240624/linux/src/krb5/src/tests/fuzzing/report.html)
* Today still gone [2024/07/26](https://storage.googleapis.com/oss-fuzz-coverage/krb5/reports/20240726/linux/src/krb5/src/tests/fuzzing/report.html)

### Note:

The last edit in krb5 was on [May 29, 2024](https://github.com/krb5/krb5/commits/master/src/tests/fuzzing), 2024/05/29.
Also last edit on oss-fuzz was on [Jun 4, 2024](https://github.com/google/oss-fuzz/commits/master/projects/krb5), 2024/06/04.

But there was a bug fix in between [krb5-69156](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69156&q=proj%3Dkrb5&can=1), https://github.com/krb5/krb5/commit/e85e30234f0e0e250a00e5f3468bb7311a7d3fb2 .
The bug as also fixed on `Jun 4, 2024`

**Comment by correctmost** [comment]
[A recent coverage log](https://oss-fuzz-build-logs.storage.googleapis.com/log-55573d30-7e30-496b-80a3-96201cc348b8.txt) contains some errors:

```
Step #5: Error occured while running fuzz_profile:
[...]
Step #5: ==66== ERROR: libFuzzer: timeout after 101 seconds
Step #5:     #0 0x561a4ee08d34 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/ubsan/ubsan_diag_standalone.cpp:31:3
Step #5:     #1 0x561a4ed887b8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
Step #5:     #2 0x561a4ed6b457 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:304:5
Step #5:     #3 0x7f0a77ece41f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 9a65bb469e45a1c6fbcffae5b82a2fd7a69eb479)
Step #5:     #4 0x7f0a77daf22b in read (/lib/x86_64-linux-gnu/libc.so.6+0x10e22b) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
Step #5:     #5 0x7f0a77d31b9e in _IO_file_underflow (/lib/x86_64-linux-gnu/libc.so.6+0x90b9e) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
Step #5:     #6 0x7f0a77d32f85 in _IO_default_uflow (/lib/x86_64-linux-gnu/libc.so.6+0x91f85) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
Step #5:     #7 0x7f0a77d2486b in _IO_getline_info (/lib/x86_64-linux-gnu/libc.so.6+0x8386b) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
Step #5:     #8 0x7f0a77d236c9 in _IO_fgets (/lib/x86_64-linux-gnu/libc.so.6+0x826c9) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
Step #5:     #9 0x561a4ee0d41f in parse_file /src/krb5/src/util/profile/prof_parse.c:350:13
Step #5:     #10 0x561a4ee0e2dd in parse_include_file /src/krb5/src/util/profile/prof_parse.c:232:14
Step #5:     #11 0x561a4ee0e2dd in parse_include_dir /src/krb5/src/util/profile/prof_parse.c:281:18
Step #5:     #12 0x561a4ee0d8ee in parse_line /src/krb5/src/util/profile/prof_parse.c:303:16
Step #5:     #13 0x561a4ee0d8ee in parse_file /src/krb5/src/util/profile/prof_parse.c:353:18
Step #5:     #14 0x561a4ee0d32e in profile_parse_file /src/krb5/src/util/profile/prof_parse.c:429:14
Step #5:     #15 0x561a4ee0a0fc in LLVMFuzzerTestOneInput /src/krb5/src/tests/fuzzing/fuzz_profile.c:72:9
Step #5:     #16 0x561a4ed6ca00 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:614:13
Step #5:     #17 0x561a4ed76319 in fuzzer::Fuzzer::CrashResistantMergeInternalStep(std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char>> const&, bool) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMerge.cpp:239:5
Step #5:     #18 0x561a4ed5caa0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:887:8
Step #5:     #19 0x561a4ed89022 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
Step #5:     #20 0x7f0a77cc5082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 0702430aef5fa3dda43986563e9ffcc47efbd75e)
Step #5:     #21 0x561a4ed4dc6d in _start (out/libfuzzer-coverage-x86_64/fuzz_profile+0x1fc6d)
```

The above timeout repeats a bunch of times and seems to lead to missing coverage data:
```
Step #5: du: cannot access '/workspace/out/libfuzzer-coverage-x86_64/dumps/fuzz_profile.*.profraw': No such file or directory
[...]
Step #5: WARNING: fuzz_profile has no profdata generated.
```

**Comment by pkillarjun** [comment]
Well, `libc` is cooked.

**Comment by pkillarjun** [comment]
Ah, `libc` is cooked, I guess.
Using FUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION for `include` and `includedir` in `prof_parse.c` can resolve this.
