### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: testcase-detail.html

### ISSUE THREAD

**Issue by tbeu** [google/oss-fuzz#12371]
When viewsing the test case details web page an exception is raised.

```
Traceback (most recent call last):
  File "/srv/handlers/base_handler.py", line 278, in dispatch_request
    return super().dispatch_request(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/srv/libs/handler.py", line 384, in wrapper
    response = make_response(func(self, *args, **kwargs))
  File "/srv/handlers/testcase_detail/show.py", line 605, in get
    return self.render('testcase-detail.html', values)
  File "/srv/handlers/base_handler.py", line 203, in render
    template = _JINJA_ENVIRONMENT.get_template(path)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: testcase-detail.html
```

**Comment by DavidKorczynski** [comment]
@jonathanmetzman @oliverchang are you familiar with this? Testcases don't seem to viewable atm.

**Comment by jonathanmetzman** [comment]
Looking into this.

**Comment by jonathanmetzman** [comment]
It looks fixed now.
