### ISSUE TITLE
Recent Java changes causing millions of exceptions. 

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#12496]
This seems to be affecting tons of our java projects, and is possibly breaking the rest of OSS-Fuzz
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: AuthenticodeMsiSignerFuzzer has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 59.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:468)
	at com.code_intelligence.jazzer.driver.FuzzTargetFinder.findFuzzTarget(FuzzTargetFinder.java:52)
	at com.code_intelligence.jazzer.driver.Driver.start(Driver.java:160)
	at com.code_intelligence.jazzer.Jazzer.start(Jazzer.java:113)
	at com.code_intelligence.jazzer.Jazzer.main(Jazzer.java:72)
```

**Comment by jonathanmetzman** [comment]
CC @kyakdan

**Comment by jonathanmetzman** [comment]
https://github.com/google/oss-fuzz/pull/12375

**Comment by jonathanmetzman** [comment]
Maybe this was caused by not updating Java in https://github.com/google/clusterfuzz/blob/master/docker/base/Dockerfile

**Comment by jonathanmetzman** [comment]
We fixed this by adding Java 15 to the images.
