### ISSUE TITLE
ICU build is broken

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1258]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #15: UndefinedBehaviorSanitizer:DEADLYSIGNAL
Step #15: ==9484==ERROR: UndefinedBehaviorSanitizer: stack-overflow on address 0x7ffd8b00cf88 (pc 0x7f5c14179bbc bp 0x000000003380 sp 0x7ffd8b00cf80 T9484)
Step #15:     #0 0x7f5c14179bbb  (/lib/x86_64-linux-gnu/libc.so.6+0x81bbb)
Step #15:     #1 0x7f5c1417c183 in __libc_malloc (/lib/x86_64-linux-gnu/libc.so.6+0x84183)
Step #15:     #2 0x69d5c9 in uprv_malloc_61 /src/icu/source/common/cmemory.cpp:58:20
Step #15:     #3 0x754ac4 in icu_61::UnicodeString::allocate(int) /src/icu/source/common/unistr.cpp:382:34
Step #15:     #4 0x756117 in icu_61::UnicodeString::cloneArrayIfNeeded(int, int, signed char, int**, signed char) /src/icu/source/common/unistr.cpp:1811:8
Step #15:     #5 0x755159 in icu_61::UnicodeString::doAppend(char16_t const*, int, int) /src/icu/source/common/unistr.cpp:1550:7
Step #15:     #6 0x75b265 in icu_61::UnicodeString::doReplace(int, int, char16_t const*, int, int) /src/icu/source/common/unistr.cpp:1446:12
Step #15:     #7 0x43068e in icu_61::UnicodeString::setTo(char16_t const*, int) /src/icu/source/common/unicode/unistr.h:4620:10
Step #15:     #8 0x43041d in StringBaseResource::StringBaseResource(SRBRoot*, char const*, signed char, char16_t const*, int, UString const*, UErrorCode&) /src/icu/source/tools/genrb/reslist.cpp:274:13
Step #15:     #9 0x438e15 in StringResource::StringResource(SRBRoot*, char const*, char16_t const*, int, UString const*, UErrorCode&) /src/icu/source/tools/genrb/reslist.h:321:15
Step #15:     #10 0x438bad in string_open /src/icu/source/tools/genrb/reslist.cpp:1099:17
Step #15:     #11 0x4237e1 in parseString(ParseState*, char*, unsigned int, UString const*, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:613:18
Step #15:     #12 0x42b0e7 in parseResource(ParseState*, char*, UString const*, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:1951:16
Step #15:     #13 0x429168 in addCollation(ParseState*, TableResource*, char const*, unsigned int, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:865:18
Step #15:     #14 0x428a82 in parseCollationElements(ParseState*, char*, unsigned int, signed char, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:1122:36
Step #15:     #15 0x4242e3 in parseTable(ParseState*, char*, unsigned int, UString const*, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:1259:16
Step #15:     #16 0x42b0e7 in parseResource(ParseState*, char*, UString const*, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:1951:16
Step #15:     #17 0x4233fc in realParseTable(ParseState*, TableResource*, char*, unsigned int, UErrorCode*) /src/icu/source/tools/genrb/parse.cpp:1225:18
Step #15:     #18 0x42233f in parse /src/icu/source/tools/genrb/parse.cpp:2055:5
Step #15:     #19 0x42c910 in (anonymous namespace)::GenrbImporter::getRules(char const*, char const*, icu_61::UnicodeString&, char const*&, UErrorCode&) /src/icu/source/tools/genrb/parse.cpp:767:13
Step #15:     #20 0x4998e1 in icu_61::CollationRuleParser::parseSetting(UErrorCode&) /src/icu/source/i18n/collationruleparser.cpp:642:27
Step #15:     #21 0x496118 in icu_61::CollationRuleParser::parse(icu_61::UnicodeString const&, UErrorCode&) /src/icu/source/i18n/collationruleparser.cpp:105:13
Step #15:     #22 0x499a53 in icu_61::CollationRuleParser::parseSetting(UErrorCode&) /src/icu/source/i18n/collationruleparser.cpp:653:17
Step #15:     #23 0x496118 in icu_61::CollationRuleParser::parse(icu_61::UnicodeString const&, UErrorCode&) /src/icu/source/i18n/collationruleparser.cpp:105:13
Step #15:     #24 0x499a53 in icu_61::CollationRuleParser::parseSetting(UErrorCode&) /src/icu/source/i18n/collationruleparser.cpp:653:17
<...>
```

**Comment by Dor1s** [comment]
Not sure if we have an owner... Maybe @aheninger ?

**Comment by inferno-chromium** [comment]
now fixed
