### ISSUE TITLE
500 error on Total Coverage page

### ISSUE THREAD

**Issue by correctmost** [google/oss-fuzz#12604]
I get a 500 error on https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_astroid/latest and https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_librsvg/latest:

```
Handler.get() got an unexpected keyword argument 'report_type'

Traceback (most recent call last):
  File "/srv/handlers/base_handler.py", line 278, in dispatch_request
    return super().dispatch_request(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/layers/google.python.pip/pip/lib/python3.11/site-packages/flask/views.py", line 188, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/libs/handler.py", line 417, in wrapper
    response = make_response(func(self, *args, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Handler.get() got an unexpected keyword argument 'report_type'
```

**Comment by IvanNardi** [comment]
Same error on https://oss-fuzz.com/coverage-report/job/libfuzzer_asan_ndpi/latest

**Comment by IvanNardi** [comment]
I confirm that. Thanks!
