### ISSUE TITLE
Make recursive search from corpus directory as default.

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#129]
Example: https://clusterfuzz-external.appspot.com/v2/testcase-detail/6470551652532224

Error: failed to open /mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/empty/libjpeg-turbo_libjpeg_turbo_fuzzer/afl-testcases. Please use -r if you want to include samples from directories.

We should make recursive search as default as corpuses can have their own subdirectory structure. Thoughts ?

**Comment by alex** [comment]
Is the default different between local and OSS-fuzz? I assume I'd have noticed if it error'd with the corpus?

**Comment by inferno-chromium** [comment]
By local, which command are you referring. In local commands using infra/helper.py, i don't think we load seed corpus. infra/helper.py is just a litmus test on if fuzzer loads fine. 

Anyway, I want to double check this before I forget. So filed bug.

**Comment by inferno-chromium** [comment]
This is ClusterFuzz side launcher script enhancement needed.

**Comment by inferno-chromium** [comment]
In order to prevent fixing this at multiple places, we should just unarchive seed corpus by dropping absolute paths, just like unzip -j works. will look tmrw.

**Comment by inferno-chromium** [comment]
Ok fixed it now.

It should also fix some libyaml exception.
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/launcher.py", line 913, in <module>
    main(sys.argv)
  File "/mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/launcher.py", line 791, in main
    minijail_chroot)
  File "/mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/launcher.py", line 364, in getCorpusDirectories
    copyFromCorpus(corpus_subset_directory, main_corpus_directory, 2)
  File "/mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/launcher.py", line 344, in copyFromCorpus
    os.path.join(dest_corpus_path, to_copy))
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: '/mnt/scratch0/clusterfuzz/slave-bot/inputs/fuzzers/libFuzzer/empty/libyaml_fuzzer/libyaml'
