### ISSUE TITLE
Startup crash in augeas fuzz target

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1326]
Has been detected after lading https://github.com/google/oss-fuzz/pull/838

Verified locally as well:

```
# ls
augeas_escape_name_fuzzer
root@0d5da1488d9e:/out# ./augeas_escape_name_fuzzer 
INFO: Seed: 2381063852
INFO: Loaded 1 modules   (11524 inline 8-bit counters): 11524 [0xa112e8, 0xa13fec), 
INFO: Loaded 1 PC tables (11524 PCs): 11524 [0x76dd90,0x79add0), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
=================================================================
==20==ERROR: AddressSanitizer: alloc-dealloc-mismatch (malloc vs operator delete []) on 0x602000007130
    #0 0x524f50 in operator delete[](void*) /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:153
    #1 0x5285dd in escape_match(unsigned char const*, unsigned long) /src/augeas_escape_name_fuzzer.cc:35:5
    #2 0x528720 in LLVMFuzzerTestOneInput /src/augeas_escape_name_fuzzer.cc:41:5
    #3 0x5521b1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
    #4 0x5507ef in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:442:3
    #5 0x55544b in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:708:5
    #6 0x555e78 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:741:3
    #7 0x53597e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:754:6
    #8 0x5288fc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #9 0x7ff30bbd982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x41d598 in _start (/out/augeas_escape_name_fuzzer+0x41d598)

0x602000007130 is located 0 bytes inside of 3-byte region [0x602000007130,0x602000007133)
allocated by thread T0 here:
    #0 0x4ea130 in calloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
    #1 0x5d2f83 in mem_alloc_n /src/augeas/src/memory.c:66:23
    #2 0x5ba459 in pathx_escape_name /src/augeas/src/pathx.c:1717:9
    #3 0x5b7eb7 in aug_escape_name /src/augeas/src/augeas.c:1852:14
    #4 0x5284fa in escape_match(unsigned char const*, unsigned long) /src/augeas_escape_name_fuzzer.cc:27:5
    #5 0x528720 in LLVMFuzzerTestOneInput /src/augeas_escape_name_fuzzer.cc:41:5
    #6 0x5521b1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
    #7 0x5507ef in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:442:3
    #8 0x55544b in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:708:5
    #9 0x555e78 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:741:3
    #10 0x53597e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:754:6
    #11 0x5288fc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #12 0x7ff30bbd982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: alloc-dealloc-mismatch /src/llvm/projects/compiler-rt/lib/asan/asan_new_delete.cc:153 in operator delete[](void*)
==20==HINT: if you don't care about these errors you may set ASAN_OPTIONS=alloc_dealloc_mismatch=0
==20==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0xa,
\x0a
artifact_prefix='./'; Test unit written to ./crash-adc83b19e793491b1c6ea0fd8b46cd9f32e592fc
Base64: Cg==
```

**Comment by alex** [comment]
Pretty sure https://github.com/google/oss-fuzz/blob/master/projects/augeas/augeas_escape_name_fuzzer.cc#L35 should be `free(out);`

**Comment by Dor1s** [comment]
Yeah, looks like, I'll land a fix. Thanks @alex for taking a look

**Comment by alex** [comment]
You can probably also drop the `data_string` construction, there's no need for the `std::string` - all this fuzzer does is call `c_str()` on it.

**Comment by Dor1s** [comment]
I think its purpose is to have a null terminated string as the target is using `strlen()` inside of https://github.com/hercules-team/augeas/blob/71a964c719e9f3e4046c426a01b8e784811d6c9c/src/pathx.c#L1702 called from https://github.com/hercules-team/augeas/blob/71a964c719e9f3e4046c426a01b8e784811d6c9c/src/augeas.c#L1845

**Comment by alex** [comment]
Ahhh; whoops!

**Comment by Dor1s** [comment]
//cc @qiankehan @lutter, as FYI

I'm also wondering whether you had a chance to run fuzz target locally when you implemented it :)
