### ISSUE TITLE
Startup crash in yara fuzz target

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1327]
Has been detected after lading #838

```
root@01b74464f8a8:/out# ./macho_fuzzer 
INFO: Seed: 3726464007
INFO: Loaded 1 modules   (6953 inline 8-bit counters): 6953 [0x9b2be8, 0x9b4711), 
INFO: Loaded 1 PC tables (6953 PCs): 6953 [0x71f7b0,0x73aa40), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
macho_fuzzer: /src/libfuzzer/FuzzerLoop.cpp:521: void fuzzer::Fuzzer::ExecuteCallback(const uint8_t *, size_t): Assertion `Res == 0' failed.
==18== ERROR: libFuzzer: deadly signal
    #0 0x4f7ab3 in __sanitizer_print_stack_trace /src/llvm/projects/compiler-rt/lib/asan/asan_stack.cc:38
    #1 0x5f07a5 in fuzzer::Fuzzer::CrashCallback() /src/libfuzzer/FuzzerLoop.cpp:233:5
    #2 0x5f073c in fuzzer::Fuzzer::StaticCrashSignalCallback() /src/libfuzzer/FuzzerLoop.cpp:206:6
    #3 0x7f53960c538f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1138f)
    #4 0x7f53956fd427 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
    #5 0x7f53956ff029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #6 0x7f53956f5bd6  (/lib/x86_64-linux-gnu/libc.so.6+0x2dbd6)
    #7 0x7f53956f5c81 in __assert_fail (/lib/x86_64-linux-gnu/libc.so.6+0x2dc81)
    #8 0x5f47b2 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:521:3
    #9 0x5f71b9 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:703:3
    #10 0x5f80b8 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:741:3
    #11 0x5d7bbe in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:754:6
    #12 0x5cab3c in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #13 0x7f53956e882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x41ce88 in _start (/out/macho_fuzzer+0x41ce88)

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 

```

**Comment by Dor1s** [comment]
//cc @plusvic Looks like the fuzz target returns 1 in some cases: https://github.com/VirusTotal/yara/blob/master/tests/oss-fuzz/macho_fuzzer.cc#L75

`LLVMFuzzerTestOneInput` must always return 0 (http://llvm.org/docs/LibFuzzer.html#id22)

**Comment by plusvic** [comment]
@Dor1s thank you for the heads up, I've fixed it in https://github.com/VirusTotal/yara/commit/a687b2d6b21eb8afc9b2c2e5a703e2ece2a56695

**Comment by inferno-chromium** [comment]
Now fixed
