### ISSUE TITLE
wget: bad build

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#1329]
Has been detected after lading #838

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #5: INFO: performing bad build checks for /workspace/out/address/wget_options_fuzzer.
Step #5: Broken fuzz targets (1):
Step #5: wget_options_fuzzer:
Step #5: BAD BUILD: the fuzzer seems to have either startup crash or exit.
Step #5: ERROR: 100% of fuzz targets seem to be broken. See the list above for a detailed information.
```

**Comment by Dor1s** [comment]
//cc @rockdaboot could you please take a look?

**Comment by Dor1s** [comment]
I think there was a discussion that `exit()` call is causing troubles:

```
root@2916e7c94cac:/out# ./wget_options_fuzzer 
INFO: Seed: 3032108556
INFO: Loaded 1 modules   (41830 inline 8-bit counters): 41830 [0xe8d328, 0xe9768e), 
INFO: Loaded 1 PC tables (41830 PCs): 41830 [0xe97690,0xf3acf0), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
==18== ERROR: libFuzzer: fuzz target exited
    #0 0x4f8fb3 in __sanitizer_print_stack_trace /src/llvm/projects/compiler-rt/lib/asan/asan_stack.cc:38
    #1 0x605184 in fuzzer::Fuzzer::ExitCallback() /src/libfuzzer/FuzzerLoop.cpp:248:5
    #2 0x7f976d433ff7  (/lib/x86_64-linux-gnu/libc.so.6+0x39ff7)
    #3 0x7f976d434044 in exit (/lib/x86_64-linux-gnu/libc.so.6+0x3a044)
    #4 0x539df5 in main_wget /src/wget/src/main.c
    #5 0x5293c2 in LLVMFuzzerTestOneInput /src/wget/fuzz/wget_options_fuzzer.c:163:2
    #6 0x608c91 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
    #7 0x60ba59 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:703:3
    #8 0x60c958 in fuzzer::Fuzzer::Loop(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, fuzzer::fuzzer_allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&) /src/libfuzzer/FuzzerLoop.cpp:741:3
    #9 0x5ec45e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:754:6
    #10 0x5df3dc in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #11 0x7f976d41a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x41e388 in _start (/out/wget_options_fuzzer+0x41e388)

SUMMARY: libFuzzer: fuzz target exited
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
```

**Comment by rockdaboot** [comment]
I also explained that exit() is overridden in my fuzzer code, performing a longjump() back into LLVMFuzzerTestOneInput(). So glibc's exit() was only called when called from libFuzzer.

I now test a different approach, renaming exit() in the application code (in fuzzing mode only).

**Comment by rockdaboot** [comment]
Success here.

**Comment by Dor1s** [comment]
Yay, thanks a lot @rockdaboot, looking forward to landing the fix! :)

**Comment by inferno-chromium** [comment]
green build
