### ISSUE TITLE
chakra build broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1346]
@EdMaurer - can you please take a look

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #3: Status: Downloaded newer image for gcr.io/oss-fuzz-base/msan-builder:latest
Finished Step #3
Starting Step #4
Step #4: Already have image: gcr.io/oss-fuzz/chakra
Step #4: ---------------------------------------------------------------
Step #4: CC=clang
Step #4: CXX=clang++
Step #4: CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope 
Step #4: CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope  -stdlib=libc++
Step #4: ---------------------------------------------------------------
Step #4: + DISABLED_WARNINGS=-Wno-everything
Step #4: + cat
Step #4: + chmod +x /usr/local/bin/cmake
Step #4: ++ which clang
Step #4: ++ which clang++
Step #4: + ./build.sh --test-build --static --embed-icu --cc=/usr/local/bin/clang --cxx=/usr/local/bin/clang++ -j -v -y
Step #4: Traceback (most recent call last):
Step #4:   File "/src/chakra/tools/configure_icu.py", line 232, in <module>
Step #4:     main()
Step #4:   File "/src/chakra/tools/configure_icu.py", line 225, in main
Step #4:     archive_path = download_icu(args.icu_root, args.version, args.yes)
Step #4:   File "/src/chakra/tools/configure_icu.py", line 181, in download_icu
Step #4:     md5_request = urllib2.urlopen(md5_url)
Step #4:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
Step #4:     return opener.open(url, data, timeout)
Step #4:   File "/usr/lib/python2.7/urllib2.py", line 429, in open
Step #4:     response = self._open(req, data)
Step #4:   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
Step #4:     '_open', req)
Step #4:   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
Step #4:     result = func(*args)
Step #4:   File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
Step #4: Downloading ICU from http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-src.tgz
Step #4: Downloaded ICU to /tmp/tmpdbzPDb.tgz
Step #4:     context=self._context)
Step #4:   File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
Step #4:     raise URLError(err)
Step #4: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
Step #4: You must accept the ICU license agreement in order to use this configuration
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/chakra" failed: exit status 1
```

**Comment by alex** [comment]
The cert used on ssl.icu-project.org has expired.

**Comment by inferno-chromium** [comment]
fixed
