### ISSUE TITLE
curl build broken

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#1351]
Has been detected after lading #838

https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #4: Running: /src/curl_fuzzer/corpora/curl_fuzzer/oss-fuzz-gen-6638d89b27ceef13e985ca5a1d9f64cc9d78f579
Step #4: 
Step #4: =================================================================
Step #4: ==8599==ERROR: LeakSanitizer: detected memory leaks
Step #4: 
Step #4: Direct leak of 168 byte(s) in 1 object(s) allocated from:
Step #4:     #0 0x4ea4e0 in calloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:97
Step #4:     #1 0x532680 in curl_docalloc /src/curl/lib/memdebug.c:206:9
Step #4:     #2 0x63d284 in Curl_ftp_parselist /src/curl/lib/ftplistparser.c:356:27
Step #4:     #3 0x59c267 in chop_write /src/curl/lib/sendf.c:585:22
Step #4:     #4 0x5c96a8 in readwrite_data /src/curl/lib/transfer.c:796:26
Step #4:     #5 0x5c703c in Curl_readwrite /src/curl/lib/transfer.c:1125:14
Step #4:     #6 0x540672 in multi_runsingle /src/curl/lib/multi.c:1893:16
Step #4:     #7 0x53e5c3 in curl_multi_perform /src/curl/lib/multi.c:2160:14
Step #4:     #8 0x5298be in fuzz_handle_transfer(fuzz_data*) /src/curl_fuzzer/curl_fuzzer.cc:382:5
Step #4:     #9 0x528acb in LLVMFuzzerTestOneInput /src/curl_fuzzer/curl_fuzzer.cc:93:3
Step #4:     #10 0xb0e3d1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
Step #4:     #11 0xae547a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
Step #4:     #12 0xaf0e2b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:703:9
Step #4:     #13 0xae4b1c in main /src/libfuzzer/FuzzerMain.cpp:20:10
Step #4:     #14 0x7fac718d682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
Step #4: 
Step #4: Indirect leak of 176 byte(s) in 1 object(s) allocated from:
Step #4:     #0 0x4ea2c8 in malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:88
Step #4:     #1 0x532115 in curl_domalloc /src/curl/lib/memdebug.c:175:9
Step #4:     #2 0x63d2bb in Curl_ftp_parselist /src/curl/lib/ftplistparser.c:361:40
Step #4:     #3 0x59c267 in chop_write /src/curl/lib/sendf.c:585:22
Step #4:     #4 0x5c96a8 in readwrite_data /src/curl/lib/transfer.c:796:26
Step #4:     #5 0x5c703c in Curl_readwrite /src/curl/lib/transfer.c:1125:14
Step #4:     #6 0x540672 in multi_runsingle /src/curl/lib/multi.c:1893:16
Step #4:     #7 0x53e5c3 in curl_multi_perform /src/curl/lib/multi.c:2160:14
Step #4:     #8 0x5298be in fuzz_handle_transfer(fuzz_data*) /src/curl_fuzzer/curl_fuzzer.cc:382:5
Step #4:     #9 0x528acb in LLVMFuzzerTestOneInput /src/curl_fuzzer/curl_fuzzer.cc:93:3
Step #4:     #10 0xb0e3d1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:517:13
Step #4:     #11 0xae547a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
Step #4:     #12 0xaf0e2b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:703:9
Step #4:     #13 0xae4b1c in main /src/libfuzzer/FuzzerMain.cpp:20:10
Step #4:     #14 0x7fac718d682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
Step #4: 
Step #4: SUMMARY: AddressSanitizer: 344 byte(s) leaked in 2 allocation(s).
Step #4: 
Step #4: INFO: a leak has been found in the initial corpus.
Step #4: 
Step #4: INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
Step #4: 
Step #4: make: *** [check] Error 77
Step #4: Makefile:2078: recipe for target 'check' failed
Step #4: + exit 5
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/curl" failed: exit status 5
```

This is now blocking the build since this is a crash in seed corpus.
@cmeister2 - can you please take a look.

**Comment by cmeister2** [comment]
This is due to @bagder having merged https://github.com/curl/curl/commit/8fb78f9ddc6d858d630600059b8ad84a80892fd9 which has also broken the main curl build.

@bagder: Maybe it's worth reverting that fix for now while we're still hitting CI errors in multiple places?

**Comment by bagder** [comment]
I've reverted the problematic commit now.

**Comment by inferno-chromium** [comment]
fixed
