### ISSUE TITLE
Are /dev/random and /dev/urandom available?

### ISSUE THREAD

**Issue by Lekensteyn** [google/oss-fuzz#1479]
In this recent [oss-fuzz report](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8712) there is a condition that should never be reached:
```
Fatal: no entropy gathering module detected
```

This suggests that `/dev/urandom` or `/dev/random` are inaccessible in the Ubuntu 16.04 image. Is that the case or is there some other problem?

```
Fatal: no entropy gathering module detected
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000001 (pc 0x7f7cd1af7428 bp 0x0000058730f0 sp 0x7ffe1d1bdd28 T0)
SCARINESS: 10 (signal)
#0 0x7f7cd1af7427 in gsignal /build/glibc-Cl5G7W/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
#1 0x7f7cd1af9029 in abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:89
#2 0x25447b8 in _gcry_logv
#3 0x2544bc0 in _gcry_log_fatal
#4 0x25bdbcc in initialize
#5 0x257eb94 in _gcry_create_nonce
#6 0x2588997 in _gcry_mpi_randomize
#7 0x256b39d in rsa_decrypt
#8 0x2562df2 in _gcry_pk_decrypt
#9 0x254395d in gcry_pk_decrypt
```

**Comment by inferno-chromium** [comment]
Jonathan deployed a fix, lets see if this bug gets auto-closed tonight.

**Comment by oliverchang** [comment]
Looks like the fix worked.
