### ISSUE TITLE
libtsm is out-of-date

### ISSUE THREAD

**Issue by tianxiaogu** [google/oss-fuzz#1805]
I am sorry for reporting this issue since I am new to oss-fuzz project and just find that there is a particular issue tracker at <https://bugs.chromium.org/p/oss-fuzz/issues/list>.
These issues are duplicate and have been reported already.
Sorry for the confusing report.
Can somebody help me to close this report?

-------------------

> It seems that `libtsm` has been out-of-date for a long time. We cannot find a valid bug report link at <https://www.freedesktop.org/wiki/Software/libtsm/>.
> Our fuzzing tool has found two buffer-over-flow issues of libtsm. But we do not know whether they are duplicate and where to report them.
> To avoid bugs introduced by our customized AFL, we reproduce the crashes on libfuzzer.
> 
> [libtsm-crashes.zip](https://github.com/google/oss-fuzz/files/2365385/libtsm-crashes.zip)
> 
> ```
> ./libtsm_fuzzer_out/crashes/id:000311,sig:06,src:002053,op:havoc,rep:4
> INFO: Seed: 1326421111
> INFO: Loaded 1 modules   (2795 inline 8-bit counters): 2795 [0x850000, 0x850aeb), 
> INFO: Loaded 1 PC tables (2795 PCs): 2795 [0x850af0,0x85b9a0), 
> libtsm_fuzzer: Running 1 inputs 1 time(s) each.
> Running: ./libtsm_fuzzer_out/crashes/id:000311,sig:06,src:002053,op:havoc,rep:4
> =================================================================
> ==1473==ERROR: AddressSanitizer: global-buffer-overflow on address 0x0000005fded0 at pc 0x000000546851 bp 0x7ffccb839890 sp 0x7ffccb839888
> READ of size 1 at 0x0000005fded0 thread T0
> SCARINESS: 12 (1-byte-read-global-buffer-overflow)
>     #0 0x546850 in vte_write_debug /src/libtsm/src/tsm/tsm-vte.c:514:8
>     #1 0x546e91 in do_trans /src/libtsm/src/tsm/tsm-vte.c:1858:3
>     #2 0x540254 in tsm_vte_input /src/libtsm/src/tsm/tsm-vte.c
>     #3 0x531a6d in LLVMFuzzerTestOneInput /src/libtsm_fuzzer.c:44:3
>     #4 0x579e88 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:570:15
>     #5 0x55035a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
>     #6 0x55bbd3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:713:9
>     #7 0x54f9dc in main /src/libfuzzer/FuzzerMain.cpp:20:10
>     #8 0x7f8b35ea282f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
>     #9 0x41e728 in _start (/out/libtsm_fuzzer+0x41e728)
> 
> 0x0000005fded0 is located 48 bytes to the left of global variable '<string literal>' defined in 'src/tsm/tsm-vte.c:950:3' (0x5fdf00) of size 7
>   '<string literal>' is ascii string 'do_esc'
> 0x0000005fded0 is located 0 bytes to the right of global variable '<string literal>' defined in 'src/tsm/tsm-vte.c:654:2' (0x5fdec0) of size 16
>   '<string literal>' is ascii string '[?60;1;6;9;15c'
> SUMMARY: AddressSanitizer: global-buffer-overflow /src/libtsm/src/tsm/tsm-vte.c:514:8 in vte_write_debug
> Shadow bytes around the buggy address:
>   0x0000800b7b80: 00 00 f9 f9 f9 f9 f9 f9 00 00 f9 f9 f9 f9 f9 f9
>   0x0000800b7b90: 00 03 f9 f9 f9 f9 f9 f9 00 00 00 07 f9 f9 f9 f9
>   0x0000800b7ba0: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
>   0x0000800b7bb0: 00 00 00 00 f9 f9 f9 f9 00 02 f9 f9 f9 f9 f9 f9
>   0x0000800b7bc0: 00 00 02 f9 f9 f9 f9 f9 00 03 f9 f9 f9 f9 f9 f9
> =>0x0000800b7bd0: 00 00 00 02 f9 f9 f9 f9 00 00[f9]f9 f9 f9 f9 f9
>   0x0000800b7be0: 07 f9 f9 f9 f9 f9 f9 f9 00 00 00 f9 f9 f9 f9 f9
>   0x0000800b7bf0: 07 f9 f9 f9 f9 f9 f9 f9 00 00 00 07 f9 f9 f9 f9
>   0x0000800b7c00: 00 00 00 07 f9 f9 f9 f9 00 00 00 00 f9 f9 f9 f9
>   0x0000800b7c10: 00 00 00 02 f9 f9 f9 f9 06 f9 f9 f9 f9 f9 f9 f9
>   0x0000800b7c20: 00 06 f9 f9 f9 f9 f9 f9 00 00 05 f9 f9 f9 f9 f9
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07 
>   Heap left redzone:       fa
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
>   Shadow gap:              cc
> ==1473==ABORTING
> 
> ```
> 
> ```
> ./libtsm_fuzzer_out/crashes/id:000449,sig:06,src:003395,op:havoc,rep:2
> INFO: Seed: 1333277281
> INFO: Loaded 1 modules   (2795 inline 8-bit counters): 2795 [0x850000, 0x850aeb), 
> INFO: Loaded 1 PC tables (2795 PCs): 2795 [0x850af0,0x85b9a0), 
> libtsm_fuzzer: Running 1 inputs 1 time(s) each.
> Running: ./libtsm_fuzzer_out/crashes/id:000449,sig:06,src:003395,op:havoc,rep:2
> =================================================================
> ==1572==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6070000003f0 at pc 0x00000053a1b0 bp 0x7fff50dc6c20 sp 0x7fff50dc6c18
> READ of size 1 at 0x6070000003f0 thread T0
> SCARINESS: 12 (1-byte-read-heap-buffer-overflow)
>     #0 0x53a1af in tsm_screen_tab_left /src/libtsm/src/tsm/tsm-screen.c:1321:8
>     #1 0x546e91 in do_trans /src/libtsm/src/tsm/tsm-vte.c:1858:3
>     #2 0x540254 in tsm_vte_input /src/libtsm/src/tsm/tsm-vte.c
>     #3 0x531a6d in LLVMFuzzerTestOneInput /src/libtsm_fuzzer.c:44:3
>     #4 0x579e88 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:570:15
>     #5 0x55035a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
>     #6 0x55bbd3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:713:9
>     #7 0x54f9dc in main /src/libfuzzer/FuzzerMain.cpp:20:10
>     #8 0x7f29208b482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
>     #9 0x41e728 in _start (/out/libtsm_fuzzer+0x41e728)
> 
> 0x6070000003f0 is located 0 bytes to the right of 80-byte region [0x6070000003a0,0x6070000003f0)
> allocated by thread T0 here:
>     #0 0x4ed8ce in realloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:165
>     #1 0x533e37 in tsm_screen_resize /src/libtsm/src/tsm/tsm-screen.c:652:15
>     #2 0x53360f in tsm_screen_new /src/libtsm/src/tsm/tsm-screen.c:490:8
>     #3 0x5319cb in LLVMFuzzerTestOneInput /src/libtsm_fuzzer.c:39:3
>     #4 0x579e88 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:570:15
>     #5 0x55035a in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
>     #6 0x55bbd3 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:713:9
>     #7 0x54f9dc in main /src/libfuzzer/FuzzerMain.cpp:20:10
>     #8 0x7f29208b482f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
> 
> SUMMARY: AddressSanitizer: heap-buffer-overflow /src/libtsm/src/tsm/tsm-screen.c:1321:8 in tsm_screen_tab_left
> Shadow bytes around the buggy address:
>   0x0c0e7fff8020: 00 00 00 00 00 00 00 00 00 00 fa fa fa fa 00 00
>   0x0c0e7fff8030: 00 00 00 00 00 00 00 00 fa fa fa fa 00 00 00 00
>   0x0c0e7fff8040: 00 00 00 00 00 00 fa fa fa fa fd fd fd fd fd fd
>   0x0c0e7fff8050: fd fd fd fd fa fa fa fa 00 00 00 00 00 00 00 00
>   0x0c0e7fff8060: 00 00 fa fa fa fa fd fd fd fd fd fd fd fd fd fd
> =>0x0c0e7fff8070: fa fa fa fa 00 00 00 00 00 00 00 00 00 00[fa]fa
>   0x0c0e7fff8080: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c0e7fff8090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c0e7fff80a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c0e7fff80b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
>   0x0c0e7fff80c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
> Shadow byte legend (one shadow byte represents 8 application bytes):
>   Addressable:           00
>   Partially addressable: 01 02 03 04 05 06 07 
>   Heap left redzone:       fa
>   Freed heap region:       fd
>   Stack left redzone:      f1
>   Stack mid redzone:       f2
>   Stack right redzone:     f3
>   Stack after return:      f5
>   Stack use after scope:   f8
>   Global redzone:          f9
>   Global init order:       f6
>   Poisoned by user:        f7
>   Container overflow:      fc
>   Array cookie:            ac
>   Intra object redzone:    bb
>   ASan internal:           fe
>   Left alloca redzone:     ca
>   Right alloca redzone:    cb
>   Shadow gap:              cc
> ==1572==ABORTING
> 
> ```

**Comment by Dor1s** [comment]
Hi @tianxiaogu,

the issues found by OSS-Fuzz and reported via https://bugs.chromium.org/p/oss-fuzz/issues/list will get automatically closed once fixed. For instance, the second bug you've mentioned was found ~1.5y ago and closed earlier this year: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1081

The first bug you'ev mentioned is still open as it hasn't been fixed yet: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8923

**Comment by tianxiaogu** [comment]
Hi, @Dor1s, thanks very much for your explanation. The project oss-fuzz is really awesome.

I am curious about how the second bug was verified as fixed. Based on the docker file <https://github.com/google/oss-fuzz/blob/7cb80546c18e63b081ebd39a80a013d6074307a8/projects/libtsm/Dockerfile#L21>, the source code is pulled from <https://cgit.freedesktop.org/~dvdhrm/libtsm>.
The last commit of this repo happened in April 2014. There is no update ever since.

I can also use the [test case 5437603467755520](https://oss-fuzz.com/download?testcase_id=5437603467755520) provided in <https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=1081> to reproduce this issue.

**Comment by Dor1s** [comment]
Hm, good question :) The fix revision range points to https://cgit.freedesktop.org/~dvdhrm/libtsm/commit/?id=b73acb4c71698a764763ae8dad94c1e8a2b8d7a3, which is an old commit. Weird.

Which git url we should be using now?

**Comment by tianxiaogu** [comment]
Thanks, @Dor1s , Ｉ probably know how the bug is verified as fixed right now.

I know neither which git url should be used. Nobody seems to maintain this project right now.
