### ISSUE TITLE
An issue reproducible locally has been marked unreproducible

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#1996]
Yesterday several systemd issues were marked unreproducible. In 3 of them the label was changed back to reproducible and, if I correctly understood @inferno-chromium's comment, that happened because something had changed on the ClusterFuzz side.

In https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9341 the label wasn't changed back to "reproducible", though, I can reproduce it locally with the latest images I've just pulled with `infra/helper.py pull_images`:
```
+ /out/fuzz-journal-remote -rss_limit_mb=2048 -timeout=25 -runs=100 /testcase
INFO: Seed: 1658481643
INFO: Loaded 2 modules   (39543 inline 8-bit counters): 39333 [0x7fa00b3a7169, 0x7fa00b3b0b0e), 210 [0x989c10, 0x989ce2),
INFO: Loaded 2 PC tables (39543 PCs): 39333 [0x7fa00b3b0b10,0x7fa00b44a560), 210 [0x989ce8,0x98aa08),
/out/fuzz-journal-remote: Running 1 inputs 100 time(s) each.
Running: /testcase
==6==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fa00ad9124e in utf8_encoded_valid_unichar /work/build/../../src/systemd/src/basic/utf8.c:477:21
    #1 0x7fa00ad90a22 in utf8_is_printable_newline /work/build/../../src/systemd/src/basic/utf8.c:140:31
    #2 0x7fa00ab9076e in output_short /work/build/../../src/systemd/src/shared/logs-show.c:480:44
    #3 0x7fa00ab864c7 in show_journal_entry /work/build/../../src/systemd/src/shared/logs-show.c:1086:15
    #4 0x7fa00ab870d0 in show_journal /work/build/../../src/systemd/src/shared/logs-show.c:1173:29
    #5 0x4a45e9 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-journal-remote.c:67:21
    #6 0x4f759b in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:571:15
    #7 0x4af546 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:280:6
    #8 0x4c036a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:713:9
    #9 0x4ae671 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #10 0x7fa009a0382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #11 0x41fec8 in _start (/out/fuzz-journal-remote+0x41fec8)

  Uninitialized value was created by a heap allocation
    #0 0x460bd0 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc:911
    #1 0x7fa009a5fd06 in _IO_str_overflow (/lib/x86_64-linux-gnu/libc.so.6+0x7cd06)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /work/build/../../src/systemd/src/basic/utf8.c:477:21 in utf8_encoded_valid_unichar
```

**Comment by inferno-chromium** [comment]
Fixing already closed bugs is hard, that is why i couldn't update those few. in case of systemd, i have reopened https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9341 and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11569

**Comment by evverx** [comment]
On an unrelated note, could it be that https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11577 has been closed and https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11513 hasn't because of the large refactoring? They are basically about the same bug that was fixed but the statuses aren't in sync for some reason (the second one is scheduled to be closed on December 10). I haven't seen anything like that before.

**Comment by inferno-chromium** [comment]
That comment in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=11513#c2 was 4 days ago, so unrelated to the refactoring and looks like genuine unreproducible issue. You can click "Redo -> Check if bug still reproduces" to retry on that testcase just to double check. Such unreproducible bugs get closed in 14 days if the crash is not seen in 14 days. if the reproducible bug is just fixed, then unreproducible bug should get closed in next 14 days.

**Comment by inferno-chromium** [comment]
"Progression task finished."-> task finished

Reliably reproduces: NO in report confirms that this is indeed unreproducible. Click redo button just temporarily shows reproducible until verfication completes in progression task. progression task finished and result stayed same.

**Comment by evverx** [comment]
When I pasted the logs saying that the progression task was finished the status was "reliably reproduces: YES" and I'd double-checked that by frantically refreshing the page manually (that is I didn't wait for the page to refresh itself automatically). Maybe I didn't wait long enough for it to change to "NO". Anyway, what I was trying to say is that issues like those are usually closed at more or less the same time and I thought it had something to do with the refactoring, which is not the case, as it turns out.

**Comment by evverx** [comment]
By the way, the logs seems to have changed too:
```
[2018-12-02 15:00:15 UTC] evverx@gmail.com: Redo task(s): progression
[2018-12-02 15:28:43 UTC] oss-fuzz-linux-zone1-host-tx5t-14: Progression task started: r201812020351.
[2018-12-02 15:29:45 UTC] oss-fuzz-linux-zone1-host-tx5t-14: Progression task errored out: Known crash revision 201811270354 did not crash.
[2018-12-02 15:29:45 UTC] oss-fuzz-linux-zone1-host-tx5t-14: Progression task errored out: Testcase appears to be flaky.
```
