### ISSUE TITLE
"ASSERT !II.U.empty()" in "/src/libfuzzer/FuzzerCorpus.h"

### ISSUE THREAD

**Issue by fancycode** [google/oss-fuzz#2281]
I'm not sure if this is the right place to report the issue, but in https://oss-fuzz.com/testcase-detail/5697984232161280 I received the following error which I don't see how it is related to my fuzzers:
```
INFO: Loaded 1 PC tables (1587 PCs): 1587 [0x776738,0x77ca68),
--
  | INFO:        0 files found in /tmp/libFuzzerTemp.1.dir/C21
  | INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
  | INFO: seed corpus: files: 31 min: 37b max: 363b total: 5494b rss: 67Mb
  | #16 pulse  cov: 944 ft: 7792 corp: 14/1131b exec/s: 8 rss: 361Mb
  | #32 pulse  cov: 1036 ft: 9877 corp: 29/5094b focus: 68 exec/s: 6 rss: 361Mb
  | #32 INITED cov: 1037 ft: 9877 corp: 30/5457b focus: 68 exec/s: 6 rss: 361Mb
  | lzma2enc_fuzzer: /src/libfuzzer/FuzzerCorpus.h:170: fuzzer::InputInfo &fuzzer::InputCorpus::ChooseUnitToMutate(fuzzer::Random &): Assertion `!II.U.empty()' failed.
  | MemorySanitizer:DEADLYSIGNAL
  | ==119==ERROR: MemorySanitizer: ABRT on unknown address 0x000000000077 (pc 0x7fbc7d7a8428 bp 0x00000076e2c1 sp 0x7fffed6be368 T119)
  | #0 0x7fbc7d7a8427 in gsignal /build/glibc-Cl5G7W/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
  | #1 0x7fbc7d7aa029 in abort /build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:89
  | #2 0x7fbc7d7a0bd6 in __assert_fail_base /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92
  | #3 0x7fbc7d7a0c81 in __assert_fail /build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:101
  | #4 0x51ee37 in fuzzer::InputCorpus::ChooseUnitToMutate(fuzzer::Random&) /src/libfuzzer/FuzzerCorpus.h:170:5
```

**Comment by kcc** [comment]
It's the right place to report, thanks. 
This is an assertion failure in libFuzzer (i.e. it should not happen). 
I don't know how it could happen :( 
If it happens frequently, I'll take a closer look, but for now I declare this to be caused by cosmic rays.
