### ISSUE TITLE
MSAN interacting weirdly with -fsanitize=fuzzer

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2332]
It seems like we are getting some msan errors inside libFuzzer when using -fsanitize=fuzzer.
I don't know if this is happening in production, but I can easily repro this locally:

```
gsutil -m cp gs://clusterfuzz-builds/skcms/skcms-memory-201904170136.zip . # Built using -fsanitize=fuzzer
unzip skcms-memory-201904170136.zip
```
Now run iccprofile_atf a few times and then Ctrl-C out of it.
Eventually you will see this:

```
Uninitialized bytes in __interceptor_opendir at offset 28 inside [0x703000000480, 29)
==57362==WARNING: MemorySanitizer: use-of-uninitialized-value
==57362==WARNING: Can't read from symbolizer at fd 3
    #0 0x466a43 in fuzzer::IterateDirRecursive(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&, void (*)(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&), void (*)(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&), void (*)(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&)) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerIOPosix.cpp:87:12
    #1 0x4682f6 in fuzzer::Fuzzer::InterruptCallback() /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:269:3
    #2 0x4682af in fuzzer::Fuzzer::StaticInterruptCallback() /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:215:6
    #3 0x52308b in SignalAction(int, void*, void*) /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc:1004:3
    #4 0x7fa8f4b4b38f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1138f)
    #5 0x7fa8f42c096f  (/lib/x86_64-linux-gnu/libc.so.6+0x17296f)
    #6 0x4e60de in __msan_memset /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc
    #7 0x4e60de in __interceptor_memset /src/llvm/projects/compiler-rt/lib/msan/../sanitizer_common/sanitizer_common_interceptors.inc:773
    #8 0x469587 in Reset /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerValueBitMap.h:27:18
    #9 0x469587 in ResetMaps /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerTracePC.h:85
    #10 0x469587 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:527
    #11 0x468f95 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:453:3
    #12 0x46a7e8 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:669:19
    #13 0x46b645 in fuzzer::Fuzzer::Loop(std::Fuzzer::vector<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > > > const&, std::Fuzzer::vector<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> >, fuzzer::fuzzer_allocator<std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > > > const&) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:814:5
    #14 0x45c8aa in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:776:6
    #15 0x482da2 in main /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #16 0x7fa8f416e82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #17 0x41ddc8 in _start (/out/iccprofile_info+0x41ddc8)

  Uninitialized value was created by a heap allocation
    #0 0x4e283d in malloc /src/llvm/projects/compiler-rt/lib/msan/msan_interceptors.cc:911:3
    #1 0x41fae7 in operator new(unsigned long) (/out/iccprofile_info+0x41fae7)

SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/llvm/projects/compiler-rt/lib/fuzzer/FuzzerIOPosix.cpp:87:12 in fuzzer::IterateDirRecursive(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&, void (*)(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&), void (*)(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&), void (*)(std::Fuzzer::basic_string<char, std::Fuzzer::char_traits<char>, std::Fuzzer::allocator<char> > const&))
Exiting
```

It goes without saying that it is bad if fsanitize=fuzzer + MSAN gives us spurious errors in libFuzzer.
But frankly I'm confused how this can even happen, shouldn't libFuzzer be using a private version of libc++?

**Comment by jonathanmetzman** [comment]
cc @morehouse @kcc

**Comment by Dor1s** [comment]
What's the status here? Looks like we've got a bunch of unreproducible MSan crashes across different projects: https://oss-fuzz.com/testcases?open=yes&q=Use-of-uninitialized-value

**Comment by morehouse** [comment]
I haven't looked yet.  Might get to it today or tomorrow.

**Comment by morehouse** [comment]
`-fsanitize=memory,fuzzer` works on the libFuzzer tests, but I never got to test on a wider deployment like OSS-Fuzz, so there's probably some long tail issues still.  A complete list of false positives would be helpful so I can (hopefully) fix them all at once.

Max, your link gives me a blank search, maybe I'm missing permissions or something.
![image](https://user-images.githubusercontent.com/19176026/56761780-1132d000-6753-11e9-9ffe-0ebace504ebc.png)

**Comment by Dor1s** [comment]
Yeah, looks like you have access only to LLVM project, let me fix that.

**Comment by morehouse** [comment]
All the false positives I see there happen during the `SIGINT` handler. I've sent a fix for review:  https://reviews.llvm.org/D61163

**Comment by morehouse** [comment]
Should be resolved after rolling past r359254.

**Comment by jonathanmetzman** [comment]
This problem seems to be resolved after the clang roll. Thanks Matt!
