### ISSUE TITLE
gsutil failing to rsync during GraphicsMagick coverage builds

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#2585]
[Here](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15652#c3) is where the issue occurs.
Assigning to current sheriff.
cc @Dor1s

**Comment by Dor1s** [comment]
Hm, weird... The reports uploaded since July 2nd are indeed incomplete, e.g. https://storage.googleapis.com/oss-fuzz-coverage/imagemagick/reports/20190701/linux/report.html vs https://storage.googleapis.com/oss-fuzz-coverage/imagemagick/reports/20190702/linux/report.html

I'd probably try generating report locally (via https://github.com/google/oss-fuzz/blob/master/docs/code_coverage.md); if it succeeds, shell into the container and try uploading with gsutil to see if it goes through or reproduces the error. If it doesn't reproduce locally, then we can app `-D` or even `-DD` option to the command used for uploading: https://github.com/google/oss-fuzz/blob/master/infra/gcb/build_and_run_coverage.py#L178

**Comment by bobfriesenhahn** [comment]
This problem has been afflicting the GraphicsMagick build since July 4th.  This is blocking forward progress with oss-fuzz.  I do not know how oss-fuzz functions so I can not understand Dor1s bug comment at all.  Does someone with privileged access to the oss-fuzz system need to investigate this?

**Comment by Dor1s** [comment]
@bobfriesenhahn, sorry for the inconvenience. My comment was for my teammates who were the sheriffs in the past two weeks. This week it's my turn, so I'll try to investigate myself.

**Comment by Dor1s** [comment]
Doesn't reproduce locally. Kicked off a job with `-D` flag to see debug output. I have another workaround in mind, but would like to better understand where the error is coming from.

**Comment by Dor1s** [comment]
Here's the debug output:

```
2019-07-23T15:25:05.013024947Z Step #7: Comparing local vs cloud md5-checksum for /workspace/out/coverage/report/linux/src/freetype2/src/winfonts/winfnt.h.html. (JUHgzGszCgYfbVBmc7u7Tw==/JUHgzGszCgYfbVBmc7u7Tw==) I 
2019-07-23T15:25:05.039543673Z Step #7: \ [241/242 files][ 37.1 MiB/ 37.1 MiB]  99% Done   3.1 MiB/s ETA 00:00:00       
INFO 0723 15:25:05.038965 base_api.py] Response of type Object: <Object I 
2019-07-23T15:25:05.039552759Z Step #7:  acl: [] I 
2019-07-23T15:25:05.039555310Z Step #7:  crc32c: u'2FJY2A==' I 
2019-07-23T15:25:05.039670122Z Step #7:  etag: u'<REDACTED>' I 
2019-07-23T15:25:05.039672789Z Step #7:  generation: 1563895504941126 I 
2019-07-23T15:25:05.039673770Z Step #7:  md5Hash: u'yHGKutbsLeXCCQE8MHrHtg==' I 
2019-07-23T15:25:05.039674610Z Step #7:  size: 261037> I 
2019-07-23T15:25:05.040163931Z Step #7: Comparing local vs cloud md5-checksum for /workspace/out/coverage/report/linux/src/freetype2/src/winfonts/winfnt.c.html. (yHGKutbsLeXCCQE8MHrHtg==/yHGKutbsLeXCCQE8MHrHtg==) I 
2019-07-23T15:25:05.048829379Z Step #7: \ [242/242 files][ 37.1 MiB/ 37.1 MiB] 100% Done   3.1 MiB/s ETA 00:00:00       
 I 
2019-07-23T15:25:05.048834378Z Step #7: Operation completed over 242 objects/37.1 MiB.                                    I 
2019-07-23T15:25:05.058871859Z Step #7: DEBUG: Exception stack trace: I 
2019-07-23T15:25:05.058877929Z Step #7:     Traceback (most recent call last): I 
2019-07-23T15:25:05.058880486Z Step #7:       File "/builder/google-cloud-sdk/platform/gsutil/gslib/__main__.py", line 626, in _RunNamedCommandAndHandleExceptions I 
2019-07-23T15:25:05.058881356Z Step #7:         user_project=user_project) I 
2019-07-23T15:25:05.058882304Z Step #7:       File "/builder/google-cloud-sdk/platform/gsutil/gslib/command_runner.py", line 411, in RunNamedCommand I 
2019-07-23T15:25:05.058882885Z Step #7:         return_code = command_inst.RunCommand() I 
2019-07-23T15:25:05.058883734Z Step #7:       File "/builder/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1674, in RunCommand I 
2019-07-23T15:25:05.058884964Z Step #7:         (self.op_failure_count, plural_str, plural_str)) I 
2019-07-23T15:25:05.058886411Z Step #7:     CommandException: CommandException: 1 files/objects could not be copied/removed. I 
2019-07-23T15:25:05.058887247Z Step #7:      I 
2019-07-23T15:25:05.058887894Z Step #7: CommandException: 1 files/objects could not be copied/removed. I 
2019-07-23T15:25:05.060552672Z Step #7: gsutil version: 4.39 I 
2019-07-23T15:25:05.060556675Z Step #7: checksum: 252ffedce4addf29cc0fac2dbd127f20 (OK) I 
2019-07-23T15:25:05.060559059Z Step #7: boto version: 2.49.0 I 
2019-07-23T15:25:05.060560241Z Step #7: python version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609] I 
2019-07-23T15:25:05.060561009Z Step #7: OS: Linux 4.15.0-1036-gcp I 
2019-07-23T15:25:05.060561618Z Step #7: multiprocessing available: True I 
2019-07-23T15:25:05.060562099Z Step #7: using cloud sdk: True I 
2019-07-23T15:25:05.060562785Z Step #7: pass cloud sdk credentials to gsutil: True I 
2019-07-23T15:25:05.060563702Z Step #7: config path(s): No config found I 
2019-07-23T15:25:05.060564865Z Step #7: gsutil path: /builder/google-cloud-sdk/bin/gsutil I 
2019-07-23T15:25:05.060565434Z Step #7: compiled crcmod: True I 
2019-07-23T15:25:05.060566088Z Step #7: installed via package manager: False I 
2019-07-23T15:25:05.060566759Z Step #7: editable install: False I 
2019-07-23T15:25:05.060567285Z Step #7: connect: (www.googleapis.com, 443) I 
2019-07-23T15:25:05.060570167Z Step #7: send: 'GET /storage/v1/b/oss-fuzz-coverage/o?prefix=graphicsmagick%2Freports%2F20190723_test&projection=noAcl&fields=prefixes%2CnextPageToken%2Citems%2Fname&alt=json&delimiter=%2F&maxResults=1000 HTTP/1.1\r\nHost: www.googleapis.com\r\ncontent-length: 0\r\nauthorization: Bearer <REDACTED>\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nuser-agent: apitools gsutil/4.39 Python/2.7.12 (linux2) google-cloud-sdk/253.0.0 analytics/disabled\r\n\r\n' I 
2019-07-23T15:25:05.060570736Z Step #7: reply: 'HTTP/1.1 200 OK\r\n' I 
2019-07-23T15:25:05.060571861Z Step #7: header: X-GUploader-UploadID: <REDACTED>
 I 
2019-07-23T15:25:05.060572502Z Step #7: header: Vary: Origin
 I 
2019-07-23T15:25:05.060572970Z Step #7: header: Vary: X-Origin
 I 
2019-07-23T15:25:05.060584873Z Step #7: header: Content-Type: application/json; charset=UTF-8
 I 
2019-07-23T15:25:05.060585423Z Step #7: header: Expires: Tue, 23 Jul 2019 15:24:50 GMT
 I 
2019-07-23T15:25:05.060586684Z Step #7: header: Date: Tue, 23 Jul 2019 15:24:50 GMT
 I 
2019-07-23T15:25:05.060587317Z Step #7: header: Cache-Control: private, max-age=0, must-revalidate, no-transform
 I 
2019-07-23T15:25:05.060587879Z Step #7: header: Content-Length: 3
 I 
2019-07-23T15:25:05.060588270Z Step #7: header: Server: UploadServer
 I 
2019-07-23T15:25:05.060588860Z Step #7: connect: (www.googleapis.com, 443) I 
2019-07-23T15:25:05.060591032Z Step #7: send: 'GET /storage/v1/b/oss-fuzz-coverage/o?prefix=graphicsmagick%2Freports%2F20190723_test%2F&projection=noAcl&versions=False&fields=nextPageToken%2Citems%2Fcrc32c%2Citems%2FtimeCreated%2Citems%2FkmsKeyName%2Citems%2Fname%2Citems%2Fmd5Hash%2Citems%2Fgeneration%2Cprefixes%2Citems%2FcustomerEncryption%2Citems%2Fsize%2Citems%2Fmetadata%2Fgoog-reserved-file-mtime&alt=json&maxResults=1000 HTTP/1.1\r\nHost: www.googleapis.com\r\ncontent-length: 0\r\nauthorization: Bearer <REDACTED>\r\naccept-encoding: gzip, deflate\r\naccept: application/json\r\nuser-agent: apitools gsutil/4.39 Python/2.7.12 (linux2) google-cloud-sdk/253.0.0 analytics/disabled\r\n\r\n' I 
2019-07-23T15:25:05.060591605Z Step #7: reply: 'HTTP/1.1 200 OK\r\n' I 
2019-07-23T15:25:05.060592581Z Step #7: header: X-GUploader-UploadID: <REDACTED>
 I 
2019-07-23T15:25:05.060592983Z Step #7: header: Vary: Origin
 I 
2019-07-23T15:25:05.060593450Z Step #7: header: Vary: X-Origin
 I 
2019-07-23T15:25:05.060594013Z Step #7: header: Content-Type: application/json; charset=UTF-8
 I 
2019-07-23T15:25:05.060594395Z Step #7: header: Expires: Tue, 23 Jul 2019 15:24:50 GMT
 I 
2019-07-23T15:25:05.060595087Z Step #7: header: Date: Tue, 23 Jul 2019 15:24:50 GMT
 I 
2019-07-23T15:25:05.060595743Z Step #7: header: Cache-Control: private, max-age=0, must-revalidate, no-transform
 I 
2019-07-23T15:25:05.060596325Z Step #7: header: Content-Length: 3
 I 
2019-07-23T15:25:05.060596893Z Step #7: header: Server: UploadServer
 I 
2019-07-23T15:25:05.585188379Z Finished Step #7 I 
2019-07-23T15:25:13.039294071Z ERROR I 
2019-07-23T15:25:13.039299798Z ERROR: build step 7 "gcr.io/cloud-builders/gsutil" failed: exit status 1 I 

```


Doesn't make much sense. I'm not even sure which exact file has failed to upload. `style.css` is missing in the GCS bucket, so probably that's it.

**Comment by Dor1s** [comment]
Ah, ok, checking gsutil code (https://github.com/GoogleCloudPlatform/gsutil/blob/2ca3e55c72bd5811548abf1b1a5dd18594ac023d/gslib/commands/rsync.py#L1674), it can be a file that failed to upload somewhere in the middle of the execution. I have to check the full log to possibly identify it.

**Comment by Dor1s** [comment]
Found the exception:

```
I 2019-07-23T15:24:50.926576663Z Step #7: Encountered exception while syncing: 
I 2019-07-23T15:24:50.926579476Z Step #7: Traceback (most recent call last): 
I 2019-07-23T15:24:50.926580469Z Step #7:   File "/builder/google-cloud-sdk/platform/gsutil/gslib/command.py", line 2056, in run 
I 2019-07-23T15:24:50.926581057Z Step #7:     args = next(self.args_iterator) 
I 2019-07-23T15:24:50.926582272Z Step #7:   File "/builder/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1188, in __iter__ 
I 2019-07-23T15:24:50.926583426Z Step #7:     src_md5) = (self._ParseTmpFileLine(next(self.sorted_src_urls_it))) 
I 2019-07-23T15:24:50.926584160Z Step #7:   File "/builder/google-cloud-sdk/platform/gsutil/gslib/commands/rsync.py", line 1049, in _ParseTmpFileLine 
I 2019-07-23T15:24:50.926584885Z Step #7:     md5) = line.split() 
I 2019-07-23T15:24:50.926585736Z Step #7: ValueError: too many values to unpack 
```

It happens in the beginning of syncing, even before the first file is uploaded.

I don't really want to dig into that, as we don't even need `rsync` functionality. Now testing the workaround with `cp -r`, which also should be faster and more reasonable.

**Comment by Dor1s** [comment]
Code coverage job has succeeded for both graphicsmagick and imagemagick.

**Comment by alex** [comment]
Thanks @Dor1s !
