### ISSUE TITLE
Exceptions in logs analysis task

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#286]
[2017-01-17 00:05:19] Error: Exception occurred in function <function doLogsAnalysis at 0x7f1d57fe3140>: args: ('libFuzzer_brotli_decode_fuzzer', 'libfuzzer_asan_brotli'), kwargs: {} exception: [Errno 28] No space left on device
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/common/utils.py", line 780, in __wrapper
    return async_result.get(timeout=duration)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 28] No space left on device

[2017-01-17 00:18:25] Error: Exception occurred in function <function doLogsAnalysis at 0x7fd821315140>: args: ('libFuzzer_libarchive_fuzzer', 'libfuzzer_asan_libarchive'), kwargs: {} exception:
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/common/utils.py", line 780, in __wrapper
    return async_result.get(timeout=duration)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 563, in get
    raise TimeoutError
TimeoutError

[2017-01-13 02:17:16] Error: Exception occurred in function <function doLogsAnalysis at 0x7ffa056dfed8>: args: ('libFuzzer_curl_fuzzer', 'libfuzzer_asan_curl'), kwargs: {} exception:
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/common/utils.py", line 780, in __wrapper
    return async_result.get(timeout=duration)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 563, in get
    raise TimeoutError
TimeoutError

[2017-01-17 05:30:17] Error: Exception occurred in function <function doLogsAnalysis at 0x7f55c2c6c1b8>: args: ('libFuzzer_arduinojson_json_fuzzer', 'libfuzzer_asan_arduinojson'), kwargs: {} exception:
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/common/utils.py", line 780, in __wrapper
    return async_result.get(timeout=duration)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 563, in get
    raise TimeoutError
TimeoutError

**Comment by Dor1s** [comment]
The first one happens because daily logs for brotli fuzzer are ~120MB, while temporary dir has size of 90MB.

This can be addressed in one of the following ways:
1) use another place to download logs for analysis (e.g. fuzz inputs, it's bigger)
2) increase size of temporary directory
3) [crbug.com/682175](https://bugs.chromium.org/p/chromium/issues/detail?id=682175), see c#3 there

I think that we need to do 3) in any case and also do either 1) or 2).


Looking into other exceptions now.

**Comment by Dor1s** [comment]
This is the same issue for different fuzzers. There are too many logs and they cannot be copied in 10 minutes. Thus, timeout decorator terminates the task.

`gsutil -m rsync` works pretty fastly even with thousands of files, but we are using our helpers for GCS api. Looks like we need to add some multi-threading/multi-processing, or just invoke `gsutil -m rsync` for now.

**Comment by inferno-chromium** [comment]
Ok fixed.
