### ISSUE TITLE
Reproducing AFL seems to fail in fuzzer (outside of the target)

### ISSUE THREAD

**Issue by cherusker** [google/oss-fuzz#2901]
Trying to reproduce https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15639 as suggested in https://github.com/google/oss-fuzz/blob/master/docs/advanced-topics/reproducing.md and running into an issue that rather looks like a fuzzer problem (than a problem with the actual target) to me:

```
==8==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000008 (pc 0x7f783c082428 bp 0x7ffc92956a60 sp 0x7ffc929561c8 T0)
SCARINESS: 10 (signal)
    #0 0x7f783c082427 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
    #1 0x7f783c084029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #2 0x6e908a in abort_message (/out/bzip2+0x6e908a)
    #3 0x6ed1fd in demangling_terminate_handler() (/out/bzip2+0x6ed1fd)
    #4 0x6e8b12 in std::__terminate(void (*)()) (/out/bzip2+0x6e8b12)
    #5 0x6ea8d5 in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (/out/bzip2+0x6ea8d5)
    #6 0x6ea86e in __cxa_throw (/out/bzip2+0x6ea86e)
    #7 0x6dc2c4 in std::__1::__throw_length_error(char const*) (/out/bzip2+0x6dc2c4)
    #8 0x6e87cc in std::__1::__vector_base_common<true>::__throw_length_error() const (/out/bzip2+0x6e87cc)
    #9 0x4f11c4 in __vallocate /usr/local/bin/../include/c++/v1/vector:993:15
    #10 0x4f11c4 in vector /usr/local/bin/../include/c++/v1/vector:1125:9
    #11 0x4f11c4 in ExecuteFilesOnyByOne /src/libfuzzer/afl/afl_driver.cpp:213:23
    #12 0x4f11c4 in main /src/libfuzzer/afl/afl_driver.cpp:253:12
    #13 0x7f783c06d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x4464f8 in _start (/out/bzip2+0x4464f8)
```

The stack trace looks very different to https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15639 - am I doing something wrong? I basically ran:

```
$ python infra/helper.py pull_images
$ python infra/helper.py build_image freetype2
$ python infra/helper.py build_fuzzers --engine afl freetype2
$ python infra/helper.py reproduce freetype2 bzip2 ~/5644042643177472
```

**Comment by cherusker** [comment]
Also, could we please get a grace extension on this issue?

**Comment by Dor1s** [comment]
> Also, could we please get a grace extension on this issue?

Sorry no one got back to you earlier. I've hidden the bug report for now and added `Deadline-Grace` label. I'd recommend requesting the extensions earlier next time.

**Comment by moneromooo-monero** [comment]
I can repro this (on a yet unmerged target):
My fuzz tests work fine when built with libFuzzer, but not AFL:

```
sudo python infra/helper.py check_build monero
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -v /home/user/src/oss-fuzz/build/out/monero:/out -t gcr.io/oss-fuzz-base/base-runner test_all
INFO: performing bad build checks for /tmp/not-out/transaction_fuzz_tests.
Broken fuzz targets (1):
transaction_fuzz_tests:
BAD BUILD: /tmp/not-out/transaction_fuzz_tests seems to have either startup crash or exit:
======================= INFO =========================
This binary is built for AFL-fuzz.
To run the target function on individual input(s) execute this:
  /tmp/not-out/transaction_fuzz_tests < INPUT_FILE
or
  /tmp/not-out/transaction_fuzz_tests INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute this:
  afl-fuzz [afl-flags] /tmp/not-out/transaction_fuzz_tests [-N]
afl-fuzz will run N iterations before re-spawning the process (default: 1000)
======================================================
Reading 18446744073709551615 bytes from -seed=1337
terminating with uncaught exception of type std::length_error: vector
AddressSanitizer:DEADLYSIGNAL
=================================================================
==46==ERROR: AddressSanitizer: ABRT on unknown address 0x00000000002e (pc 0x7e37c61cd428 bp 0x7ffc64e69bd0 sp 0x7ffc64e69328 T0)
SCARINESS: 10 (signal)
    #0 0x7e37c61cd428 in raise (/lib/x86_64-linux-gnu/libc.so.6+0x35428)
    #1 0x7e37c61cf029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #2 0x5413fa in abort_message (/tmp/not-out/transaction_fuzz_tests+0x5413fa)
    #3 0x54557e in demangling_terminate_handler() (/tmp/not-out/transaction_fuzz_tests+0x54557e)
    #4 0x540e82 in std::__terminate(void (*)()) (/tmp/not-out/transaction_fuzz_tests+0x540e82)
    #5 0x542c65 in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) (/tmp/not-out/transaction_fuzz_tests+0x542c65)
    #6 0x542bfe in __cxa_throw (/tmp/not-out/transaction_fuzz_tests+0x542bfe)
    #7 0x534904 in std::__1::__throw_length_error(char const*) (/tmp/not-out/transaction_fuzz_tests+0x534904)
    #8 0x540b5c in std::__1::__vector_base_common<true>::__throw_length_error() const (/tmp/not-out/transaction_fuzz_tests+0x540b5c)
    #9 0x4f6778 in __vallocate /usr/local/bin/../include/c++/v1/vector:995:15
    #10 0x4f6778 in vector /usr/local/bin/../include/c++/v1/vector:1127:9
    #11 0x4f6778 in ExecuteFilesOnyByOne /src/libfuzzer/afl/afl_driver.cpp:214:23
    #12 0x4f6778 in main /src/libfuzzer/afl/afl_driver.cpp:254:12
    #13 0x7e37c61b882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x446048 in _start (/tmp/not-out/transaction_fuzz_tests+0x446048)

DEDUP_TOKEN: raise--abort--abort_message
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35428) in raise
==46==ABORTING
ERROR: 100% of fuzz targets seem to be broken. See the list above for a detailed information.
Check build failed.
```

Note how it's trying to open a file called "-seed=1337", not checking return codes and interpreting negative as file size, and trying to read this (and failing to allocate). Something seems borked in the command line parsing (or the caller).

Building with the default libFuzzer has the test running fine.

**Comment by jonathanmetzman** [comment]
Reproing this is only possible when you use the wrong commandline options.
The correct command is:
```
python infra/helper.py check_build monero --engine afl
```

**Comment by jonathanmetzman** [comment]
Frankly I think having defaults for this command is bad. We should force people to specify and this problem goes away.

**Comment by jonathanmetzman** [comment]
> Frankly I think having defaults for this command is bad. We should force people to specify and this problem goes away.

On second the default seems useful and I don't really have the cycles to think about this problem fix it.
