### ISSUE TITLE
No coverage builds for WavPack

### ISSUE THREAD

**Issue by thuanpv** [google/oss-fuzz#3139]
Hi Oss-Fuzz team,

First of all, thank you for integrating the WavPack project (created and maintained by David Bryant) into your great continuous fuzzing framework. Its Dockerfile was committed ~4 days ago (https://github.com/google/oss-fuzz/tree/master/projects/wavpack).

I have just checked the results on the OSS-Fuzz Dashboard and found that the project has been built successfully and fuzzed for several hours. However, the Dashboard doesn't show any information about the code coverage achieved so far. In the build logs, there is no coverage build for WavPack.

Could you please explain to me (potential) reason(s) and suggest the changes that I need to make to get the code coverage results displayed on the Oss-Fuzz dashboard?

Thanks,

Thuan

**Comment by inferno-chromium** [comment]
I looked in some of fuzzing logs, and looks like corpus merge is running into timeouts. In your fuzz target, you should see way to control unbounded allocations. I also need to fix a bug on ClusterFuzz side which should atleast get fuzzing crashes.

```
Error occurred while working on task.
Traceback (most recent call last):
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/startup/run_bot.py", line 97, in task_loop
    commands.process_command(task)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/commands.py", line 150, in wrapper
    return func(task)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/commands.py", line 378, in process_command
    run_command(task_name, task_argument, job_name)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/commands.py", line 204, in run_command
    task_module.execute_task(task_argument, job_name)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1900, in execute_task
    session.run()
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1820, in run
    crashes, fuzzer_metadata = self.do_engine_fuzzing(engine_impl)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1538, in do_engine_fuzzing
    self.testcase_directory)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1252, in run_engine_fuzzer
    sync_corpus_directory, testcase_directory)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/python/bot/untrusted_runner/tasks_host.py", line 137, in engine_fuzz
    response = host.stub().EngineFuzz(request)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/third_party/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-sbkv-7/clusterfuzz/src/third_party/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 82, in wrapper
    result = func(self, request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 180, in EngineFuzz
    return tasks_impl.engine_fuzz(request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/tasks_impl.py", line 113, in engine_fuzz
    request.testcase_directory)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/fuzz_task.py", line 1260, in run_engine_fuzzer
    fuzz_test_timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 316, in fuzz
    options.fuzz_corpus_dirs, arguments, parsed_stats)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 206, in _merge_new_units
    libfuzzer.DEFAULT_MERGE_TIMEOUT))
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 412, in _minimize_corpus_two_step
    reproducers_dir, max_time)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 485, in minimize_corpus
    result.output)
TimeoutError: Merging new testcases timed out
INFO: Seed: 3264432259
INFO: Loaded 1 modules   (2077 inline 8-bit counters): 2077 [0x7ebea0, 0x7ec6bd), 
INFO: Loaded 1 PC tables (2077 PCs): 2077 [0x5a1ad0,0x5a9ca0), 
MERGE-OUTER: 30313 files, 0 in the initial corpus, 0 processed earlier
MERGE-OUTER: attempt 1
INFO: Seed: 3264617735
INFO: Loaded 1 modules   (2077 inline 8-bit counters): 2077 [0x7ebea0, 0x7ec6bd), 
INFO: Loaded 1 PC tables (2077 PCs): 2077 [0x5a1ad0,0x5a9ca0), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/mcf_tmp_dir/MCF'
MERGE-INNER: 30313 total files; 0 processed earlier; will process 30313 files now
#1	pulse  cov: 57 ft: 131 exec/s: 0 rss: 34Mb
#2	pulse  cov: 59 ft: 138 exec/s: 0 rss: 35Mb
#4	pulse  cov: 59 ft: 142 exec/s: 0 rss: 35Mb
#8	pulse  cov: 60 ft: 150 exec/s: 0 rss: 35Mb
#16	pulse  cov: 60 ft: 160 exec/s: 0 rss: 35Mb
#32	pulse  cov: 82 ft: 309 exec/s: 0 rss: 38Mb
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffffcffff27 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffffcffff27 bytes
#64	pulse  cov: 91 ft: 411 exec/s: 64 rss: 39Mb
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffff6ffff27 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffffffffc27 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffffffc7d8 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffffffe0028 bytes
#128	pulse  cov: 101 ft: 566 exec/s: 64 rss: 41Mb
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffffcaffd8 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffffef93338 bytes
#256	pulse  cov: 555 ft: 4761 exec/s: 51 rss: 48Mb
#512	pulse  cov: 768 ft: 6995 exec/s: 51 rss: 72Mb
#1024	pulse  cov: 917 ft: 9062 exec/s: 48 rss: 118Mb
#2048	pulse  cov: 1194 ft: 12367 exec/s: 51 rss: 133Mb
#4096	pulse  cov: 1279 ft: 15086 exec/s: 53 rss: 136Mb
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffffffba90 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffffa00bb90 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffff300bb90 bytes
#8192	pulse  cov: 1405 ft: 18309 exec/s: 31 rss: 166Mb
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffbd00b993 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffb9006af9 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffb9006af9 bytes
==4==WARNING: AddressSanitizer failed to allocate 0xffffffffb9006af9 bytes
#16384	pulse  cov: 1412 ft: 18880 exec/s: 12 rss: 169Mb
==4==WARNING: AddressSanitizer failed to allocate 0xfffffffff1006af9 bytes
```

**Comment by inferno-chromium** [comment]
Basically two bugs
- Main bug: Coverage wont be captured if corpus merge times out. Any idea why fuzz target is so slow, like exec/s is too low, like 12/30 per sec (ignore my comment on unbounded allocation, timeout actually is because of slow executions per sec).
- Fuzz bug: Basically we ignore crashes if corpus merge times out in fuzz run, that should be fixed with https://github.com/google/clusterfuzz/pull/1288

**Comment by inferno-chromium** [comment]
Also, reflected in performance report - https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2019-12-10&date_end=2019-12-16&fuzzer=libFuzzer_wavpack_fuzzer&job=libfuzzer_asan_wavpack&project=wavpack
https://oss-fuzz.com/performance-report/libFuzzer_wavpack_fuzzer/libfuzzer_asan_wavpack/2019-12-13

**Comment by thuanpv** [comment]
> Main bug: Coverage wont be captured if corpus merge times out. Any idea why fuzz target is so slow, like exec/s is too low, like 12-30 per sec.

In the current fuzz target, we try to decode all the samples. It could be a reason leading the the slow execution speed. I am trying to speed it up. However, could you please elaborate a bit more why the corpus merge times out? Basically I don't see a clear link between a slow execution and a merging failure.

**Comment by inferno-chromium** [comment]
Corpus seems to have like lot of files (exploded i feel like)
$ gsutil ls gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer | wc -l
30312
and if every file takes a few seconds, then it cannot complete in like 20-24 hours.
Corpus merge is corpus minimization, so it needs to first process every file in corpus and then minimize it. ideally we want this to finish in 1-2 hours, or even faster.
Root cause is slow target, so speed needs to go up. maybe it is too slow when size is too large, in that case, can constrain size.

**Comment by thuanpv** [comment]
David @dbry

**Comment by thuanpv** [comment]
David @dbry has prepared a better corpus with much smaller files to fix the performance issue. We have tested it locally the speed goes up ~25x. Since the previous corpus contains large files I would like to delete it so Oss-Fuzz can start from scratch with the newly minimized corpus. Do you think it is necessary? If it is necessary, it would be great if you could suggest me how to delete it. I tried to look at this corpora document (https://google.github.io/oss-fuzz/advanced-topics/corpora/) to find an option for deleting the current synchronized corpus but it seems that I can only view, download it., and backup it. Thanks.

**Comment by inferno-chromium** [comment]
gsutil -m rm -r gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer

**Comment by inferno-chromium** [comment]
Deleted it.

**Comment by thuanpv** [comment]
Thank you a lot for helping me to delete the big corpus and sharing the command. Unfortunately, it seems that the files somehow were not completely deleted so I saw the speed gain is not very high.

I have just tried to use your command to delete the corpus again but the output looks confusing to me
```
...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01996-cd6d58946f827d689bb2cf3a68c18c28198649c1#1576890857262680...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01998-639b52dd547af180d3ac983cc97314e63c77e4f9#1576879883802237...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01997-a90c99205c41e78d1034166219484e5fc4abb2c3#1576903442383903...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01998-564caaa8b9c774016d889d003688d40644819da3#1576892909636694...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01998-97af8854d3dfbb9c4163f410473f730e498fd1e8#1576903434222334...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01998-a7199a42b7b668410f5d68ae764f945460be8885#1576881403660398...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01998-e71f04ca8cfdf6a25ff301189210bc576af035fc#1576880515559582...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01999-b75453d57830e743fca6cedd0c64f646408bc62b#1576879877648978...
Removing gs://wavpack-corpus.clusterfuzz-external.appspot.com/libFuzzer/wavpack_fuzzer/radamsa-01999-e6d343dfa7e71408c0620ff30932691f61819782#1576903445224164...

Operation completed over 25.3k objects.                                          
CommandException: 25279 files/objects could not be removed.
```
I did try to run the command a few times and I got the same output so I suspect the command does not work as expected, at least with my account (thuanpv.nus@gmail.com)

**Comment by inferno-chromium** [comment]
Deleted it again, lets hope it works.

**Comment by thuanpv** [comment]
Thanks. The corpus merge issue seems to be fixed as the corpus_size and corpus_backup columns are not empty now. The speed looks good for AFL (>1000 execs per second). However, there is still no coverage builds and I cannot see any coverage statistics on the Dashboard. Moreover, there is no fuzzing runs with LibFuzzer for 4-5 days.

**Comment by inferno-chromium** [comment]
Can you file a new bug. Corpus pruning working fine, something is up with stats. I am guessing @oliverchang https://github.com/google/clusterfuzz/commit/644f0aa69184fcb20a6327f03b423b34c5b98eb9 will fix this. Need to wait a day to see if stats all recover.

```
I 2020-01-01T20:48:28.228131941Z Cleared system temp directory: /tmp 
I 2020-01-01T20:48:26.196125396Z Finished. 
I 2020-01-01T20:48:26.083114837Z 5510 corpus files uploaded for wavpack_fuzzer. 
I 2020-01-01T20:48:20.094692502Z Shared corpus merge finished successfully. 
I 2020-01-01T20:47:54.792637654Z Merging shared corpus... 
I 2020-01-01T20:47:54.539892513Z 0 corpus files uploaded for wavpack_fuzzer. 
I 2020-01-01T20:47:53.514184542Z Found 0 bad units, 0 unique crashes. 
I 2020-01-01T20:47:53.513576937Z Processing bad units. 
I 2020-01-01T20:47:53.511739662Z Corpus pruned from 16828 to 5509 units. 
I 2020-01-01T20:47:49.705881827Z 5509 corpus files uploaded for wavpack_fuzzer. 
I 2020-01-01T20:47:19.048221562Z URL being requested: POST https://pubsub.googleapis.com/v1/projects/clusterfuzz-external/subscriptions/jobs-wavpack-linux:modifyAckDeadline?alt=json 
I 2020-01-01T20:47:19.043620800Z Renewing lease for task by 600 seconds. 
I 2020-01-01T20:44:48.185295781Z Corpus merge finished successfully. 
I 2020-01-01T20:43:56.460615273Z Running merge... 
I 2020-01-01T20:43:56.282445453Z Unarchiving 6 files from seed corpus /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wavpack_edf4224f858034ec4936a86fd701cb95b7305413/revisions/fuzzer_seed_corpus.zip. 
I 2020-01-01T20:43:56.277437598Z Forced unpack: /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wavpack_edf4224f858034ec4936a86fd701cb95b7305413/revisions/fuzzer_seed_corpus.zip. 
I 2020-01-01T20:43:55.924754600Z Restoring units from quarantine. 
I 2020-01-01T20:43:55.754584190Z Corpus backup url gs://ffmpeg-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/ffmpeg_AV_CODEC_ID_ADPCM_EA_MAXIS_XA_fuzzer/2019-10-03.zip successfully unpacked into shared corpus. 
I 2020-01-01T20:43:55.753243725Z Unpacked 622/622. 
I 2020-01-01T20:43:55.417771997Z URL being requested: GET https://www.googleapis.com/storage/v1/b/ffmpeg-backup.clusterfuzz-external.appspot.com/o/corpus%2FlibFuzzer%2Fffmpeg_AV_CODEC_ID_ADPCM_EA_MAXIS_XA_fuzzer%2F2019-10-03.zip?alt=json 
I 2020-01-01T20:43:55.335138931Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/storage/v1/rest 
I 2020-01-01T20:43:55.334370499Z Corpus backup url gs://readstat-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/readstat_fuzz_format_xport/2019-10-03.zip successfully unpacked into shared corpus. 
I 2020-01-01T20:43:55.332559230Z Unpacked 1281/1281. 
I 2020-01-01T20:43:55.290207725Z Unpacked 1000/1281. 
I 2020-01-01T20:43:55.003529986Z URL being requested: GET https://www.googleapis.com/storage/v1/b/readstat-backup.clusterfuzz-external.appspot.com/o/corpus%2FlibFuzzer%2Freadstat_fuzz_format_xport%2F2019-10-03.zip?alt=json 
I 2020-01-01T20:43:54.837877958Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/storage/v1/rest 
I 2020-01-01T20:43:54.836921868Z Corpus backup url gs://freetype2-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/freetype2_truetype-render-i35/2019-10-03.zip successfully unpacked into shared corpus. 
I 2020-01-01T20:43:54.815523843Z Unpacked 21064/21064. 
I 2020-01-01T20:43:54.806957455Z Unpacked 21000/21064. 
I 2020-01-01T20:43:54.687378240Z Unpacked 20000/21064. 
I 2020-01-01T20:43:54.570572887Z Unpacked 19000/21064. 
I 2020-01-01T20:43:54.445744949Z Unpacked 18000/21064. 
I 2020-01-01T20:43:54.331715740Z Unpacked 17000/21064. 
I 2020-01-01T20:43:54.215526021Z Unpacked 16000/21064. 
I 2020-01-01T20:43:54.100785838Z Unpacked 15000/21064. 
I 2020-01-01T20:43:53.985178583Z Unpacked 14000/21064. 
I 2020-01-01T20:43:53.867369379Z Unpacked 13000/21064. 
I 2020-01-01T20:43:53.743652645Z Unpacked 12000/21064. 
I 2020-01-01T20:43:53.617152828Z Unpacked 11000/21064. 
I 2020-01-01T20:43:53.497269348Z Unpacked 10000/21064. 
I 2020-01-01T20:43:53.374507971Z Unpacked 9000/21064. 
I 2020-01-01T20:43:53.257549737Z Unpacked 8000/21064. 
I 2020-01-01T20:43:53.142197813Z Unpacked 7000/21064. 
I 2020-01-01T20:43:53.020458379Z Unpacked 6000/21064. 
I 2020-01-01T20:43:52.902003327Z Unpacked 5000/21064. 
I 2020-01-01T20:43:52.790777745Z Unpacked 4000/21064. 
I 2020-01-01T20:43:52.673760892Z Unpacked 3000/21064. 
I 2020-01-01T20:43:52.552541327Z Unpacked 2000/21064. 
I 2020-01-01T20:43:52.424306190Z Unpacked 1000/21064. 
I 2020-01-01T20:43:50.785109694Z URL being requested: GET https://www.googleapis.com/storage/v1/b/freetype2-backup.clusterfuzz-external.appspot.com/o/corpus%2FlibFuzzer%2Ffreetype2_truetype-render-i35%2F2019-10-03.zip?alt=json 
I 2020-01-01T20:43:50.690292720Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/storage/v1/rest 
I 2020-01-01T20:43:50.689575763Z Corpus backup url gs://ffmpeg-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/ffmpeg_AV_CODEC_ID_PCM_S64BE_fuzzer/2019-10-03.zip successfully unpacked into shared corpus. 
I 2020-01-01T20:43:50.687586215Z Unpacked 709/709. 
I 2020-01-01T20:43:50.304044214Z URL being requested: GET https://www.googleapis.com/storage/v1/b/ffmpeg-backup.clusterfuzz-external.appspot.com/o/corpus%2FlibFuzzer%2Fffmpeg_AV_CODEC_ID_PCM_S64BE_fuzzer%2F2019-10-03.zip?alt=json 
I 2020-01-01T20:43:50.212208282Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/storage/v1/rest 
I 2020-01-01T20:43:50.211456944Z Corpus backup url gs://imagemagick-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/imagemagick_ping_pdb_fuzzer/2019-10-03.zip successfully unpacked into shared corpus. 
I 2020-01-01T20:43:50.210094253Z Unpacked 564/564. 
I 2020-01-01T20:43:50.016270157Z URL being requested: GET https://www.googleapis.com/storage/v1/b/imagemagick-backup.clusterfuzz-external.appspot.com/o/corpus%2FlibFuzzer%2Fimagemagick_ping_pdb_fuzzer%2F2019-10-03.zip?alt=json 
I 2020-01-01T20:43:49.918916816Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/storage/v1/rest 
I 2020-01-01T20:43:48.905709833Z 0 corpus files downloaded for wavpack_fuzzer. 
I 2020-01-01T20:43:46.911321578Z 16828 corpus files downloaded for wavpack_fuzzer. 
I 2020-01-01T20:42:18.994835469Z URL being requested: POST https://pubsub.googleapis.com/v1/projects/clusterfuzz-external/subscriptions/jobs-wavpack-linux:modifyAckDeadline?alt=json 
I 2020-01-01T20:42:18.990038334Z Renewing lease for task by 600 seconds. 
I 2020-01-01T20:37:34.769893003Z Setup application path. 
I 2020-01-01T20:37:34.769539257Z Retrieved build r202001010539. 
I 2020-01-01T20:37:34.769125905Z Build took 0.01 minutes to unpack. 
I 2020-01-01T20:37:34.768348694Z Use previously picked fuzz target fuzzer for fuzzing. 
I 2020-01-01T20:37:34.767561967Z Unpacked 4/4. 
I 2020-01-01T20:37:34.729118730Z Unpacking build archive /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wavpack_edf4224f858034ec4936a86fd701cb95b7305413/revisions/wavpack-address-202001010539.zip. 
I 2020-01-01T20:37:34.562050973Z Downloading build from url gs://clusterfuzz-builds/wavpack/wavpack-address-202001010539.zip. 
I 2020-01-01T20:37:34.523022359Z URL being requested: GET https://www.googleapis.com/storage/v1/b/clusterfuzz-builds/o/wavpack%2Fwavpack-address-202001010539.zip?alt=json 
I 2020-01-01T20:37:34.418695468Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/storage/v1/rest 
I 2020-01-01T20:37:34.409781492Z Removing build directory /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_wavpack_edf4224f858034ec4936a86fd701cb95b7305413/revisions. 
I 2020-01-01T20:37:34.191252965Z Retrieving build r202001010539. 
I 2020-01-01T20:37:19.473777995Z Data bundle was recently synced, skip. 
I 2020-01-01T20:37:19.071847562Z Cleared system temp directory: /tmp 
I 2020-01-01T20:37:18.941584089Z URL being requested: POST https://pubsub.googleapis.com/v1/projects/clusterfuzz-external/subscriptions/jobs-wavpack-linux:modifyAckDeadline?alt=json 
I 2020-01-01T20:37:18.904810931Z URL being requested: GET https://www.googleapis.com/discovery/v1/apis/pubsub/v1/rest 
I 2020-01-01T20:37:18.897270351Z Executing command 'corpus_pruning libFuzzer_wavpack_fuzzer libfuzzer_asan_wavpack' 
```

**Comment by thuanpv** [comment]
Thanks, Abhishek. Let's wait for 1 or 2 more days and I will file a new bug if necessary.
