### ISSUE TITLE
OSS-Fuzz minimizing over and over again on some crashes

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#3174]
I've seen this on a few of them, example: https://oss-fuzz.com/testcase-detail/5734376516354048

```
[2020-01-01 09:58:14 UTC] oss-fuzz-linux-zone3-host-c0g8-12: Fuzz task : Fuzzer libFuzzer_imagemagick_encoder_tiff_fuzzer generated testcase crashed in 15 seconds (r202001010350).
[2020-01-01 10:03:06 UTC] oss-fuzz-linux-zone3-host-bpgn-12: Minimize task started.
[2020-01-01 10:48:41 UTC] oss-fuzz-linux-zone3-host-c2h3-3: Minimize task started.
[2020-01-01 11:38:58 UTC] oss-fuzz-linux-zone1-host-c6bs-3: Minimize task started.
[2020-01-01 12:19:34 UTC] oss-fuzz-linux-zone3-host-c98p-8: Minimize task started.
[2020-01-01 13:04:50 UTC] oss-fuzz-linux-zone3-host-c2h3-9: Minimize task started.
[2020-01-01 13:51:32 UTC] oss-fuzz-linux-zone1-host-c8dp-2: Minimize task started.
[2020-01-01 14:36:37 UTC] oss-fuzz-linux-zone1-host-c6bs-4: Minimize task started.
[2020-01-01 15:21:53 UTC] oss-fuzz-linux-zone1-host-c6bs-5: Minimize task started.
[2020-01-01 16:22:21 UTC] oss-fuzz-linux-zone3-host-cff2-10: Minimize task started.
[2020-01-01 17:08:00 UTC] oss-fuzz-linux-zone1-host-c4v4-8: Minimize task started.
[2020-01-01 17:53:46 UTC] oss-fuzz-linux-zone1-host-c8dp-14: Minimize task started.
[2020-01-01 18:40:43 UTC] oss-fuzz-linux-zone1-host-c8dp-9: Minimize task started.
[2020-01-01 19:26:13 UTC] oss-fuzz-linux-zone3-host-b862-13: Minimize task started.
[2020-01-01 20:17:15 UTC] oss-fuzz-linux-zone3-host-bpgn-3: Minimize task started.
[2020-01-01 21:02:41 UTC] oss-fuzz-linux-zone3-host-b6vh-15: Minimize task started.
[2020-01-01 21:48:43 UTC] oss-fuzz-linux-zone1-host-c4k6-3: Minimize task started.
[2020-01-01 22:36:49 UTC] oss-fuzz-linux-zone1-host-c2l3-1: Minimize task started.
[2020-01-01 23:21:55 UTC] oss-fuzz-linux-zone3-host-cff2-10: Minimize task started.
[2020-01-02 00:07:15 UTC] oss-fuzz-linux-zone1-host-c90s-2: Minimize task started.
[2020-01-02 00:52:23 UTC] oss-fuzz-linux-zone3-host-c0g8-11: Minimize task started.
[2020-01-02 01:37:26 UTC] oss-fuzz-linux-zone1-host-c5dn-0: Minimize task started.
[2020-01-02 02:22:28 UTC] oss-fuzz-linux-zone1-host-c2l3-13: Minimize task started.
[2020-01-02 03:08:15 UTC] oss-fuzz-linux-zone1-host-c5dn-8: Minimize task started.
[2020-01-02 03:55:53 UTC] oss-fuzz-linux-zone3-host-bkzx-3: Minimize task started.
[2020-01-02 04:40:55 UTC] oss-fuzz-linux-zone3-host-b3pt-12: Minimize task started.
[2020-01-02 05:26:33 UTC] oss-fuzz-linux-zone1-host-c5dn-2: Minimize task started.
[2020-01-02 06:06:51 UTC] oss-fuzz-linux-zone3-host-c2h3-13: Minimize task started.
[2020-01-02 06:52:21 UTC] oss-fuzz-linux-zone3-host-bkzx-13: Minimize task started.
[2020-01-02 07:37:23 UTC] oss-fuzz-linux-zone1-host-c5dn-14: Minimize task started.
[2020-01-02 08:22:32 UTC] oss-fuzz-linux-zone1-host-c4v4-0: Minimize task started.
[2020-01-02 09:08:09 UTC] oss-fuzz-linux-zone3-host-b3pt-11: Minimize task started.
[2020-01-02 09:53:17 UTC] oss-fuzz-linux-zone3-host-bfxw-8: Minimize task started.
[2020-01-02 10:38:29 UTC] oss-fuzz-linux-zone3-host-b6vh-3: Minimize task started.
[2020-01-02 11:23:44 UTC] oss-fuzz-linux-zone3-host-b3pt-7: Minimize task started.
[2020-01-02 12:08:57 UTC] oss-fuzz-linux-zone1-host-c90s-3: Minimize task started.
[2020-01-02 12:54:27 UTC] oss-fuzz-linux-zone1-host-c8dp-9: Minimize task started.
```

**Comment by inferno-chromium** [comment]
```
Failed RPC: <_Rendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "to-be-sent trailing metadata size exceeds peer limit"
	debug_error_string = "{"created":"@1577971635.923294736","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"to-be-sent trailing metadata size exceeds peer limit","grpc_status":8}"
>
Traceback (most recent call last):
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-c8dp-9/clusterfuzz/src/python/bot/untrusted_runner/host.py", line 151, in wrapped
    return func(*args, **kwargs)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-c8dp-9/clusterfuzz/src/third_party/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-c8dp-9/clusterfuzz/src/third_party/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.RESOURCE_EXHAUSTED
	details = "to-be-sent trailing metadata size exceeds peer limit"
	debug_error_string = "{"created":"@1577971635.923294736","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"to-be-sent trailing metadata size exceeds peer limit","grpc_status":8}"
>
```

**Comment by inferno-chromium** [comment]
```
Exception calling application: Cleanse timed out INFO: Seed: 471279014 INFO: Loaded 1 modules (180483 inline 8-bit counters): 180483 [0x2c24ec0, 0x2c50fc3), INFO: Loaded 1 PC tables (180483 PCs): 180483 [0x2c50fc8,0x2f11ff8), CLEANSE[0]: Trying to replace byte 0 of 276956 CLEANSE[0]: Trying to replace byte 1 of 276956 CLEANSE[0]: Trying to replace byte 2 of 276956 CLEANSE[0]: Trying to replace byte 3 of 276956 CLEANSE[0]: Trying to replace byte 4 of 276956 CLEANSE[0]: Trying to replace byte 5 of 276956 CLEANSE[0]: Trying to replace byte 6 of 276956 CLEANSE[0]: Trying to replace byte 7 of 276956 CLEANSE[0]: Trying to replace byte 8 of 276956 CLEANSE: Replaced byte 8 with 0xff CLEANSE[0]: Trying to replace byte 9 of 276956 CLEANSE[0]: Trying to replace byte 10 of 276956 CLEANSE[0]: T
```

libFuzzer cleanse output overflows

**Comment by inferno-chromium** [comment]
https://github.com/google/clusterfuzz/pull/1308 should unblock this, this regressed after we added TimeoutError and capturing output from it.

**Comment by inferno-chromium** [comment]
Still failing, @oliverchang ideas ?

```
Failed RPC: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 82, in wrapper
    result = func(self, request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 176, in ProcessTestcase
    return tasks_impl.process_testcase(request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/tasks_impl.py", line 100, in process_testcase
    request.testcase_path, request.output_path, request.timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/minimize_task.py", line 1116, in run_libfuzzer_engine
    return func(target_path, arguments, testcase_path, output_path, timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 559, in cleanse
    raise engine.TimeoutError('Cleanse timed out.')
TimeoutError: Cleanse timed out.
"
	debug_error_string = "{"created":"@1577989708.203016485","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"Traceback (most recent call last):\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 82, in wrapper\n    result = func(self, request, context)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 176, in ProcessTestcase\n    return tasks_impl.process_testcase(request, context)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/tasks_impl.py", line 100, in process_testcase\n    request.testcase_path, request.output_path, request.timeout)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/minimize_task.py", line 1116, in run_libfuzzer_engine\n    return func(target_path, arguments, testcase_path, output_path, timeout)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 559, in cleanse\n    raise engine.TimeoutError('Cleanse timed out.')\nTimeoutError: Cleanse timed out.\n","grpc_status":2}"
>
Traceback (most recent call last):
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-c6bs-4/clusterfuzz/src/python/bot/untrusted_runner/host.py", line 151, in wrapped
    return func(*args, **kwargs)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-c6bs-4/clusterfuzz/src/third_party/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/scratch0/bots/oss-fuzz-linux-zone1-host-c6bs-4/clusterfuzz/src/third_party/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 82, in wrapper
    result = func(self, request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 176, in ProcessTestcase
    return tasks_impl.process_testcase(request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/tasks_impl.py", line 100, in process_testcase
    request.testcase_path, request.output_path, request.timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/minimize_task.py", line 1116, in run_libfuzzer_engine
    return func(target_path, arguments, testcase_path, output_path, timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 559, in cleanse
    raise engine.TimeoutError('Cleanse timed out.')
TimeoutError: Cleanse timed out.
"
	debug_error_string = "{"created":"@1577989708.203016485","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1099,"grpc_message":"Traceback (most recent call last):\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 82, in wrapper\n    result = func(self, request, context)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 176, in ProcessTestcase\n    return tasks_impl.process_testcase(request, context)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/tasks_impl.py", line 100, in process_testcase\n    request.testcase_path, request.output_path, request.timeout)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/minimize_task.py", line 1116, in run_libfuzzer_engine\n    return func(target_path, arguments, testcase_path, output_path, timeout)\n  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 559, in cleanse\n    raise engine.TimeoutError('Cleanse timed out.')\nTimeoutError: Cleanse timed out.\n","grpc_status":2}"
>
```

**Comment by inferno-chromium** [comment]
@oliverchang - do we need to catch this error in more places. i see you used this pattern - 

```
  try:
    response = host.stub().EngineReproduce(request)
  except grpc.RpcError as e:
    if 'TargetNotFoundError' in str(e):
      # Resurface the right exception.
      raise testcase_manager.TargetNotFoundError('Failed to find target ' +
                                                 target_name)
    if 'TimeoutError' in str(e):
      raise engine.TimeoutError(e.message)
    else:
      raise
```

**Comment by oliverchang** [comment]
This should now be fixed.
