### ISSUE TITLE
presubmit.py: check_project_yaml_constants needs update

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#3277]
I need to run right now, filing this to make sure we won't forget, `check_project_yaml_constants` fails for sanitizers enabled via `experimental: True`, e.g. https://travis-ci.org/google/oss-fuzz/jobs/640219949?utm_medium=notification&utm_source=github_status

```bash
$ ./infra/presubmit.py
Traceback (most recent call last):
  File "./infra/presubmit.py", line 324, in <module>
    sys.exit(main())
  File "./infra/presubmit.py", line 319, in main
    success = do_checks(changed_files)
  File "./infra/presubmit.py", line 193, in do_checks
    return all([check(changed_files) for check in checks])
  File "./infra/presubmit.py", line 193, in <listcomp>
    return all([check(changed_files) for check in checks])
  File "./infra/presubmit.py", line 181, in check_project_yaml
    return all([_check_one_project_yaml(path) for path in paths])
  File "./infra/presubmit.py", line 181, in <listcomp>
    return all([_check_one_project_yaml(path) for path in paths])
  File "./infra/presubmit.py", line 175, in _check_one_project_yaml
    return checker.do_checks()
  File "./infra/presubmit.py", line 115, in do_checks
    check_function()
  File "./infra/presubmit.py", line 135, in check_project_yaml_constants
    if constant not in allowed_constants:
TypeError: unhashable type: 'dict'
The command "./infra/presubmit.py" exited with 1.
```

**Comment by inferno-chromium** [comment]
Can you please fix it.
