### ISSUE TITLE
OSS-Fuzz minimizing in a loop

### ISSUE THREAD

**Issue by alex** [google/oss-fuzz#3301]
Same cause as #3174?

https://oss-fuzz.com/testcase-detail/5764648198733824

```
[2020-01-27 18:46:51 UTC] oss-fuzz-linux-zone3-host-bkzx-6: Fuzz task : Fuzzer libFuzzer_imagemagick_encoder_heic_fuzzer generated testcase crashed in 599 seconds (r202001270431).
[2020-01-27 18:48:04 UTC] oss-fuzz-linux-zone1-host-c8dp-14: Minimize task started.
[2020-01-27 19:29:33 UTC] oss-fuzz-linux-zone1-host-c6bs-6: Minimize task started.
[2020-01-27 20:10:01 UTC] oss-fuzz-linux-zone3-host-bkzx-7: Minimize task started.
[2020-01-27 20:45:13 UTC] oss-fuzz-linux-zone3-host-bfxw-10: Minimize task started.
[2020-01-27 21:30:25 UTC] oss-fuzz-linux-zone1-host-c8dp-10: Minimize task started.
[2020-01-27 22:05:57 UTC] oss-fuzz-linux-zone1-host-c4tr-2: Minimize task started.
[2020-01-27 22:46:56 UTC] oss-fuzz-linux-zone3-host-cff2-8: Minimize task started.
[2020-01-27 23:27:19 UTC] oss-fuzz-linux-zone3-host-c2h3-15: Minimize task started.
[2020-01-28 00:07:39 UTC] oss-fuzz-linux-zone1-host-c4tr-12: Minimize task started.
[2020-01-28 00:43:01 UTC] oss-fuzz-linux-zone3-host-b862-3: Minimize task started.
[2020-01-28 01:18:39 UTC] oss-fuzz-linux-zone3-host-bkzx-1: Minimize task started.
[2020-01-28 01:54:47 UTC] oss-fuzz-linux-zone3-host-b6vh-6: Minimize task started.
[2020-01-28 02:34:51 UTC] oss-fuzz-linux-zone1-host-c8dp-8: Minimize task started.
[2020-01-28 03:15:11 UTC] oss-fuzz-linux-zone3-host-b6vh-14: Minimize task started.
[2020-01-28 03:55:50 UTC] oss-fuzz-linux-zone1-host-c2l3-8: Minimize task started.
[2020-01-28 04:36:13 UTC] oss-fuzz-linux-zone1-host-c5dn-7: Minimize task started.
[2020-01-28 05:18:12 UTC] oss-fuzz-linux-zone3-host-c98p-3: Minimize task started.
[2020-01-28 05:58:41 UTC] oss-fuzz-linux-zone3-host-cff2-8: Minimize task started.
[2020-01-28 06:33:48 UTC] oss-fuzz-linux-zone3-host-c0g8-8: Minimize task started.
[2020-01-28 07:13:58 UTC] oss-fuzz-linux-zone3-host-b6vh-8: Minimize task started.
[2020-01-28 07:54:11 UTC] oss-fuzz-linux-zone3-host-bkzx-1: Minimize task started.
[2020-01-28 08:39:31 UTC] oss-fuzz-linux-zone1-host-c19h-15: Minimize task started.
[2020-01-28 09:19:44 UTC] oss-fuzz-linux-zone1-host-c19h-11: Minimize task started.
[2020-01-28 10:00:31 UTC] oss-fuzz-linux-zone3-host-b3pt-10: Minimize task started.
[2020-01-28 10:42:03 UTC] oss-fuzz-linux-zone1-host-c90s-5: Minimize task started.
[2020-01-28 11:18:04 UTC] oss-fuzz-linux-zone3-host-c0g8-11: Minimize task started.
[2020-01-28 11:58:22 UTC] oss-fuzz-linux-zone3-host-b3pt-6: Minimize task started.
[2020-01-28 12:33:58 UTC] oss-fuzz-linux-zone3-host-c98p-6: Minimize task started.
[2020-01-28 12:49:16 UTC] oss-fuzz-linux-zone1-host-c8dp-1: Minimize task started.
[2020-01-28 13:29:26 UTC] oss-fuzz-linux-zone1-host-c2l3-10: Minimize task started.
[2020-01-28 14:09:36 UTC] oss-fuzz-linux-zone3-host-bpgn-2: Minimize task started.
[2020-01-28 14:49:49 UTC] oss-fuzz-linux-zone3-host-c98p-11: Minimize task started.
[2020-01-28 15:25:19 UTC] oss-fuzz-linux-zone3-host-c98p-3: Minimize task started.
[2020-01-28 16:25:34 UTC] oss-fuzz-linux-zone1-host-c2l3-12: Minimize task started.
[2020-01-28 17:06:02 UTC] oss-fuzz-linux-zone3-host-c2h3-0: Minimize task started.
[2020-01-28 17:47:27 UTC] oss-fuzz-linux-zone3-host-c0g8-8: Minimize task started.
[2020-01-28 18:27:42 UTC] oss-fuzz-linux-zone3-host-c98p-13: Minimize task started.
[2020-01-28 19:10:28 UTC] oss-fuzz-linux-zone1-host-c8dp-3: Minimize task started.
[2020-01-28 19:50:38 UTC] oss-fuzz-linux-zone1-host-c2l3-2: Minimize task started.
[2020-01-28 20:31:53 UTC] oss-fuzz-linux-zone1-host-c4v4-8: Minimize task started.
[2020-01-28 21:12:37 UTC] oss-fuzz-linux-zone3-host-bpgn-3: Minimize task started.
[2020-01-28 21:53:02 UTC] oss-fuzz-linux-zone3-host-cff2-15: Minimize task started.
[2020-01-28 22:33:46 UTC] oss-fuzz-linux-zone1-host-c4k6-6: Minimize task started.
[2020-01-28 23:14:29 UTC] oss-fuzz-linux-zone3-host-c2h3-12: Minimize task started.
[2020-01-28 23:55:19 UTC] oss-fuzz-linux-zone1-host-755w-10: Minimize task started.
[2020-01-29 00:36:50 UTC] oss-fuzz-linux-zone1-host-c4tr-15: Minimize task started.
```

**Comment by inferno-chromium** [comment]
```
Traceback (most recent call last):
  File "/mnt/scratch0/clusterfuzz/src/third_party/grpc/_server.py", line 389, in _call_behavior
    return behavior(argument, context), True
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 84, in wrapper
    result = func(self, request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/untrusted.py", line 178, in ProcessTestcase
    return tasks_impl.process_testcase(request, context)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/untrusted_runner/tasks_impl.py", line 100, in process_testcase
    request.testcase_path, request.output_path, request.timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/tasks/minimize_task.py", line 1136, in run_libfuzzer_engine
    return func(target_path, arguments, testcase_path, output_path, timeout)
  File "/mnt/scratch0/clusterfuzz/src/python/bot/fuzzers/libFuzzer/engine.py", line 558, in cleanse
    raise engine.TimeoutError('Cleanse timed out\n' + result.output)
TimeoutError: Cleanse timed out
```

**Comment by inferno-chromium** [comment]
@oliverchang fixed with https://github.com/google/clusterfuzz/pull/1390
