### ISSUE TITLE
Startup crash notion is confusing in performance analyzer

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#351]
Startup crash should mean libFuzzer didn't get a chance to run. Right now it uses a <5 sec threshold which is wrong since libFuzzer can run and crash on an input it found from a random seed.

Command: /mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_libxml2_a738435c9a3e204f4e873e9c8966e84ab939eba6/revisions/libxml2_xml_read_memory_fuzzer -dict=/mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_libxml2_a738435c9a3e204f4e873e9c8966e84ab939eba6/revisions/xml.dict -max_len=3635 -rss_limit_mb=2048 -timeout=25 -artifact_prefix=/ -max_total_time=2350 -print_final_stats=1 /new /subset /mutations
Bot: ossfuzz-linux-4270
Time ran: 1.793391
Dictionary: 150428 entries
INFO: Seed: 3645423250
INFO: Loaded 1 modules (49541 guards): [0xfc1a90, 0xff20a4),
Loading corpus dir: /new
Loading corpus dir: /subset
Loading corpus dir: /mutations
Loaded 1024/2000 files from /mutations
#0      READ units: 1958

=================================================================
==1==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 192 byte(s) in 4 object(s) allocated from:
    #0 0x4d5c68 in malloc _asan_rtl_
    #1 0x72d20a in xmlNewDocElementContent /src/libxml2/valid.c:952:34

**Comment by inferno-chromium** [comment]
Fixed.
