### ISSUE TITLE
AFL and honggfuzz seem to ignore memory leaks

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3629]
I ran into this trying to build a new fuzz target that immediately triggers a memory leak in a project that unfortunately hasn't been integrated into OSS-Fuzz yet. Though, the issue can be reproduced by  removing `free(compr)` from `compress_fuzzer.c`:
```sh
$ sed -i 's!free(compr);!!' projects/zlib/compress_fuzzer.c
```
```
$ sudo ./infra/helper.py build_fuzzers --clean --engine=afl zlib

$ sudo ./infra/helper.py check_build --engine=afl zlib compress_fuzzer
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=afl -e SANITIZER=address -e ARCHITECTURE=x86_64 -v /home/vagrant/oss-fuzz/build/out/zlib:/out -t gcr.io/oss-fuzz-base/base-runner test_one /out/compress_fuzzer
Check build passed.
```
```
$ sudo ./infra/helper.py shell zlib
...
root@0787d415d67c:/src/zlib# printf '1' | /out/compress_fuzzer
======================= INFO =========================
This binary is built for AFL-fuzz.
To run the target function on individual input(s) execute this:
  /out/compress_fuzzer < INPUT_FILE
or
  /out/compress_fuzzer INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute this:
  afl-fuzz [afl-flags] /out/compress_fuzzer [-N]
afl-fuzz will run N iterations before re-spawning the process (default: 1000)
======================================================
/out/compress_fuzzer: successfully executed 1 input(s)

=================================================================
==20==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4969d2 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x4c901b in LLVMFuzzerTestOneInput /src/compress_fuzzer.c:66:22
    #2 0x4c99fe in main /src/libfuzzer/afl/afl_driver.cpp:271:7
    #3 0x7f0b8871682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 128 byte(s) in 1 object(s) allocated from:
    #0 0x4969d2 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x4c901b in LLVMFuzzerTestOneInput /src/compress_fuzzer.c:66:22
    #2 0x4c999e in main /src/libfuzzer/afl/afl_driver.cpp:260:3
    #3 0x7f0b8871682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 256 byte(s) leaked in 2 allocation(s).
```
```
$ sudo ./infra/helper.py run_fuzzer --engine=afl zlib compress_fuzzer
...
                   american fuzzy lop 2.56b (compress_fuzzer)

┌─ process timing ─────────────────────────────────────┬─ overall results ─────┐
│        run time : 0 days, 0 hrs, 1 min, 25 sec       │  cycles done : 0      │
│   last new path : 0 days, 0 hrs, 0 min, 18 sec       │  total paths : 143    │
│ last uniq crash : none seen yet                      │ uniq crashes : 0      │
│  last uniq hang : none seen yet                      │   uniq hangs : 0      │
...
```

**Comment by evverx** [comment]
When it's built with `libFuzzer` it fails as soon as it starts:
```
$ sudo ./infra/helper.py run_fuzzer  zlib compress_fuzzer
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e RUN_FUZZER_MODE=interactive -v /home/vagrant/oss-fuzz/build/out/zlib:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer compress_fuzzer
Using seed corpus: compress_fuzzer_seed_corpus.zip
/out/compress_fuzzer -rss_limit_mb=2560 -timeout=25 /tmp/compress_fuzzer_corpus < /dev/null
INFO: Seed: 3293035390
INFO: Loaded 1 modules   (1451 inline 8-bit counters): 1451 [0x7e60d0, 0x7e667b),
INFO: Loaded 1 PC tables (1451 PCs): 1451 [0x59e2d8,0x5a3d88),
INFO:       77 files found in /tmp/compress_fuzzer_corpus
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 784574 bytes
INFO: seed corpus: files: 77 min: 254b max: 784574b total: 5190823b rss: 26Mb

=================================================================
==14==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 634 byte(s) in 1 object(s) allocated from:
    #0 0x521a72 in calloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
    #1 0x5540e9 in LLVMFuzzerTestOneInput /src/compress_fuzzer.c:66:22
    #2 0x459d61 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #3 0x459485 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:470:3
    #4 0x45beb7 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:765:7
    #5 0x45c229 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:792:3
    #6 0x44a638 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:824:6
    #7 0x474462 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #8 0x7fb03378a82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 634 byte(s) leaked in 1 allocation(s).

INFO: a leak has been found in the initial corpus.

INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.
```

**Comment by jonathanmetzman** [comment]
I am aware of this. Checking for memory leaks after individual testcases is expensive and requires integration with LSAN that AFL doesn't have. I am fine leaving things the way they are and letting libFuzzer find the memory leaks.
Is this difference causing you issues?

**Comment by evverx** [comment]
> Is this difference causing you issues?

It was unexpected in the sense that having spent a couple of hours tweaking the build system I barely understood, I thought it was because I forgot to pass some flags somewhere or linked the fuzz target with the wrong linker (or both :-).

> I am fine leaving things the way they are and letting libFuzzer find the memory leaks.

Agreed.

**Comment by evverx** [comment]
I forgot to close the issue. I hope next time I'm stuck I'll be able to find this to refresh my memory. Thank you!

**Comment by jonathanmetzman** [comment]
> > Is this difference causing you issues?
> 
> It was unexpected in the sense that having spent a couple of hours tweaking the build system I barely understood, I thought it was because I forgot to pass some flags somewhere or linked the fuzz target with the wrong linker (or both :-).


Sorry about that. I wish there was more we could do to prevent users from running into this subtle inconsistency but I'm not sure anything would help much. Maybe we could put this in documentation  (and there is certainly no harm in doing so) but I suspect it wouldn't be noticed by the right people at the right time and so it wouldn't help.

**Comment by evverx** [comment]
> I suspect it wouldn't be noticed by the right people at the right time and so it wouldn't help.

I don't think the documentation would have helped much either. In retrospect, I think it's one of those issues where taking a break would probably have been the best course of action :-) Thanks again!
