### ISSUE TITLE
CIFuzz: checks are currently failing

### ISSUE THREAD

**Issue by jwhui** [google/oss-fuzz#3727]
I'm currently getting failures with CIFuzz on GitHub Actions:

```
Run google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
  with:
    oss-fuzz-project-name: openthread
    fuzz-seconds: 1800
    dry-run: false
    sanitizer: address
/usr/bin/docker run --name c27d31869d905b865b4b999290a2ad17af001c_cc619b --label c27d31 --workdir /github/workspace --rm -e INPUT_OSS-FUZZ-PROJECT-NAME -e INPUT_FUZZ-SECONDS -e INPUT_DRY-RUN -e INPUT_SANITIZER -e OSS_FUZZ_PROJECT_NAME -e FUZZ_SECONDS -e DRY_RUN -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/openthread/openthread":"/github/workspace" c27d31:869d905b865b4b999290a2ad17af001c
Traceback (most recent call last):
  File "/opt/run_fuzzers_entrypoint.py", line 96, in <module>
    sys.exit(main())
  File "/opt/run_fuzzers_entrypoint.py", line 58, in main
    sanitizer = os.environ.get('SANITIZER').lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

GitHub Actions log archive: [logs_2675.zip](https://github.com/google/oss-fuzz/files/4548435/logs_2675.zip)

Thoughts?

**Comment by jonathanmetzman** [comment]
Thanks, can you try to rerun that action again?
I think this bug was caused by landing: https://github.com/google/oss-fuzz/commit/9b30127675b0bf295648e2f907df0d756ff5a2eb

**Comment by jonathanmetzman** [comment]
Also, could you link me to where this happened please?

**Comment by jwhui** [comment]
> Also, could you link me to where this happened please?

https://github.com/openthread/openthread/runs/627646174

I can re-run, but I'll let you take a look at the link before re-running it.

**Comment by jonathanmetzman** [comment]
I just reverted the change so I think if you rerun it should work.

**Comment by jwhui** [comment]
> I just reverted the change so I think if you rerun it should work.

Yes, CIFuzz is passing again. Thanks.
