### ISSUE TITLE
ASAN_OPTIONS=detect_stack_use_after_return=1 can hide bugs

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#3798]
CIFuzz was green in https://github.com/systemd/systemd/runs/670239657?check_suite_focus=true while in https://semaphoreci.com/systemd/systemd/branches/pull-request-15556/builds/23 the following issue was discovered:
```
/usr/bin/env /tmp/autopkgtest-lxc.69j20dpz/downtmp/build.i0v/src/build-deb/fuzz-dhcp-server:address /tmp/autopkgtest-lxc.69j20dpz/downtmp/build.i0v/src/test/fuzz/fuzz-dhcp-server/request-new
--- stdout ---
/tmp/autopkgtest-lxc.69j20dpz/downtmp/build.i0v/src/test/fuzz/fuzz-dhcp-server/request-new... 
--- stderr ---
Found container virtualization lxc.
open("/sys/firmware/efi/efivars/SystemdOptions-8cf2644b-4b0b-428f-9387-6d876050dc67") failed: No such file or directory
DHCP SERVER: REQUEST (selecting) (0x0)
Assertion 'e' failed at src/libsystemd/sd-event/sd-event.c:3765, function sd_event_now(). Ignoring.
AddressSanitizer:DEADLYSIGNAL
=================================================================
==5305==ERROR: AddressSanitizer: SEGV on unknown address 0x7f5aeea97290 (pc 0x7f5aef1c5a7e bp 0x7f5aeea97290 sp 0x7ffc6899aa10 T0)
==5305==The signal is caused by a WRITE memory access.
    #0 0x7f5aef1c5a7d  (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x2ba7d)
    #1 0x7f5aef282f8a in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.5+0xe8f8a)
    #2 0x5602672c9676 in dhcp_lease_free ../../../../src/libsystemd-network/sd-dhcp-server.c:25
    #3 0x5602672c9676 in dhcp_server_handle_message ../../../../src/libsystemd-network/sd-dhcp-server.c:968
    #4 0x5602672cc0f1 in LLVMFuzzerTestOneInput ../../../../src/fuzz/fuzz-dhcp-server.c:53
    #5 0x5602672c3790 in main ../../../../src/fuzz/fuzz-main.c:39
    #6 0x7f5aee90309a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2409a)
    #7 0x5602672c3a19 in _start (/tmp/autopkgtest-lxc.69j20dpz/downtmp/build.i0v/src/build-deb/test/fuzz/sanitize-address-fuzzers/fuzz-dhcp-server+0x6a19)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libasan.so.5+0x2ba7d) 
==5305==ABORTING
-------
```
I haven't figured out why it happened yet though.

**Comment by evverx** [comment]
Interestingly, apart from Semaphore CI the latest version of that PR kind of totally destroyed [Travis CI](https://travis-ci.org/github/systemd/systemd/builds/686655175), [Ubuntu CI](https://objectstorage.prodstack4-5.canonical.com/v1/AUTH_77e2ada1e7a84929a74ba3b87153c0ac/autopkgtest-bionic-upstream-systemd-ci-systemd-ci/bionic/amd64/s/systemd-upstream/20200513_170807_f91a2@/log.gz) and [CentOS CI](https://ci.centos.org/job/systemd-pr-build-vagrant-sanitizers/5594/console). CIFuzz is still green though: https://github.com/systemd/systemd/actions/runs/103779098.

**Comment by evverx** [comment]
I put the code triggering the bug in https://github.com/evverx/systemd/tree/fuzz-dhcp-server just in case.

**Comment by jonathanmetzman** [comment]
Nice, an A/B test of CIFuzz.

The fuzz target ran in CIFuzz and I don't see any logs about an unreproducible or non-novel (e.g. reproducing on OSS-Fuzz builds) crash.

I guess there are a few possibilities.
1. This bug is discoverable from a non-OSS-Fuzz build but isn't discoverable from an OSS-Fuzz build/ on an OSS-Fuzz image. 
Have you seen this bug reproduced in similar runtime environments to the OSS-Fuzz image (e.g. barebones ubuntu 16.04 image? I see the other environments are centos, ubuntu 18.04 and debian testing.

Might be worth uploading builds as artifacts (or at least documenting how to do this so a PR can modify the necessary file) so debugging this is easier. I'm a bit nervous about always uploading them because it's unclear if it will run afoul of limits: https://github.com/actions/upload-artifact/issues/9

2. This bug can be found on OSS-Fuzz's build/image but we aren't running it for long enough or the fuzzer isn't finding it for some other reason (randomness maybe though probably unlikely).
How are the other runs finding this bug? What are they doing to run the fuzzer? Running it just on seed inputs? Or actually fuzzing?

3. This is found by CIFuzz but lost due to some kind of bug in CIFuzz.

**Comment by evverx** [comment]
I suspect it most likely has something to do with the environment created by "infra/helper.py". I can reproduce the bug with the seed corpora when I build the fuzz target locally without docker but as soon as I start using helper.py the issue goes away.

**Comment by jonathanmetzman** [comment]
Interesting. Do you know if it's the runtime environment or build?
I don't know if your setup permits this but I can binaries produced by helper.py on my host (`./build/out/systemd/fuzz-dhcp-server`). If you could do this it would narrow the problem down significantly.

**Comment by evverx** [comment]
I'm not sure what's going on. It seems `./build/out/systemd/fuzz-dhcp-server` always fails as expected:
```
ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-8/bin/llvm-symbolizer ./build/out/systemd/fuzz-dhcp-server ~/systemd/test/fuzz/fuzz-dhcp-server/
INFO: Seed: 323383482
INFO: Loaded 2 modules   (52614 inline 8-bit counters): 51962 [0x7f5bbe79b330, 0x7f5bbe7a7e2a), 652 [0x892480, 0x89270c),
INFO: Loaded 2 PC tables (52614 PCs): 51962 [0x7f5bbe7a7e30,0x7f5bbe872dd0), 652 [0x892710,0x894fd0),
INFO:        7 files found in /home/vagrant/systemd/test/fuzz/fuzz-dhcp-server/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 7 min: 247b max: 260b total: 1764b rss: 37Mb
=================================================================
==31714==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x7ffc7c8aebd0 in thread T0
    #0 0x4979dd in free /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:123:3
    #1 0x4ce544 in dhcp_server_handle_message /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:988:17
    #2 0x4d3330 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-dhcp-server.c:53:16
    #3 0x52c076 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:556:15
    #4 0x528690 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:470:3
    #5 0x52fa60 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/libfuzzer/FuzzerLoop.cpp:765:7
    #6 0x530a2d in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/libfuzzer/FuzzerLoop.cpp:792:3
    #7 0x4ea731 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:824:6
    #8 0x4dbea7 in main /src/libfuzzer/FuzzerMain.cpp:19:10
    #9 0x7f5bbcd1d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #10 0x41f078 in _start (/home/vagrant/oss-fuzz/build/out/systemd/fuzz-dhcp-server+0x41f078)

Address 0x7ffc7c8aebd0 is located in stack of thread T0 at offset 560 in frame
    #0 0x4ccaff in dhcp_server_handle_message /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:755

  This frame has 8 object(s):
    [32, 40) 'req' (line 756)
    [64, 72) 'error_message' (line 757)
    [96, 144) 'state' (line 808)
    [176, 192) '.compoundliteral'
    [208, 216) 'lease' (line 905)
    [240, 248) 'time_now' (line 906)
    [272, 280) 'lease219' (line 945)
    [304, 312) 'time_now220' (line 946) <== Memory access at offset 560 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: bad-free /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:123:3 in free
==31714==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000
0x1,0x1,0x6,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xa,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x63,0x82,0x53,0x63,0x35,0x1,0x3,0x3d,0x2,0x2,0x2,0xff,
\x01\x01\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0a\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00c\x82Sc5\x01\x03=\x02\x02\x02\xff
artifact_prefix='./'; Test unit written to ./crash-78c41f87ab42a25b2532d7549cbc970149b43315
Base64: AQEGAAAAAAAAAAAACgAAAgAAAAAAAAAAAAAAAAMDAwMDAwMDAwMDAwMDAwMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjglNjNQEDPQICAv8=
```
but when it's run via `infra/helper.py` it either keeps going or fails with
```
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e RUN_FUZZER_MODE=interactive -v /home/vagrant/oss-fuzz/build/out/systemd:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer fuzz-dhcp-server
Using seed corpus: fuzz-dhcp-server_seed_corpus.zip
/out/fuzz-dhcp-server -rss_limit_mb=2560 -timeout=25 /tmp/fuzz-dhcp-server_corpus -max_len=600 < /dev/null
INFO: Seed: 395144241
INFO: Loaded 2 modules   (52614 inline 8-bit counters): 51962 [0x7f3dcff01330, 0x7f3dcff0de2a), 652 [0x892480, 0x89270c),
INFO: Loaded 2 PC tables (52614 PCs): 51962 [0x7f3dcff0de30,0x7f3dcffd8dd0), 652 [0x892710,0x894fd0),
INFO:        7 files found in /tmp/fuzz-dhcp-server_corpus
INFO: seed corpus: files: 7 min: 247b max: 260b total: 1764b rss: 37Mb
#9	INITED cov: 303 ft: 362 corp: 6/1504b exec/s: 0 rss: 38Mb
#12	NEW    cov: 304 ft: 366 corp: 7/1673b lim: 259 exec/s: 0 rss: 38Mb L: 169/259 MS: 3 ShuffleBytes-ChangeBinInt-CrossOver-
#13	NEW    cov: 308 ft: 397 corp: 8/1932b lim: 259 exec/s: 0 rss: 38Mb L: 259/259 MS: 1 CrossOver-
#14	NEW    cov: 311 ft: 404 corp: 9/2191b lim: 259 exec/s: 0 rss: 38Mb L: 259/259 MS: 1 ChangeASCIIInt-
#17	NEW    cov: 311 ft: 405 corp: 10/2438b lim: 259 exec/s: 0 rss: 38Mb L: 247/259 MS: 3 EraseBytes-InsertRepeatedBytes-InsertRepeatedBytes-
#19	NEW    cov: 311 ft: 406 corp: 11/2697b lim: 259 exec/s: 0 rss: 38Mb L: 259/259 MS: 2 CopyPart-CopyPart-
#25	NEW    cov: 313 ft: 408 corp: 12/2952b lim: 259 exec/s: 0 rss: 38Mb L: 255/259 MS: 1 InsertByte-
#39	NEW    cov: 315 ft: 410 corp: 13/3211b lim: 259 exec/s: 0 rss: 39Mb L: 259/259 MS: 4 CrossOver-ChangeByte-ChangeBit-ChangeBinInt-
#61	REDUCE cov: 315 ft: 410 corp: 13/3063b lim: 259 exec/s: 0 rss: 39Mb L: 21/259 MS: 2 ChangeByte-CrossOver-
#65	NEW    cov: 316 ft: 411 corp: 14/3322b lim: 259 exec/s: 0 rss: 39Mb L: 259/259 MS: 4 EraseBytes-InsertByte-InsertByte-CrossOver-
#72	NEW    cov: 317 ft: 412 corp: 15/3580b lim: 259 exec/s: 0 rss: 39Mb L: 258/259 MS: 2 ChangeByte-InsertRepeatedBytes-
#78	REDUCE cov: 317 ft: 412 corp: 15/3564b lim: 259 exec/s: 0 rss: 39Mb L: 243/259 MS: 1 EraseBytes-
#84	NEW    cov: 318 ft: 414 corp: 16/3822b lim: 259 exec/s: 0 rss: 39Mb L: 258/259 MS: 1 ShuffleBytes-
#85	NEW    cov: 318 ft: 415 corp: 17/4078b lim: 259 exec/s: 0 rss: 39Mb L: 256/259 MS: 1 EraseBytes-
#110	NEW    cov: 319 ft: 416 corp: 18/4337b lim: 259 exec/s: 0 rss: 39Mb L: 259/259 MS: 5 CopyPart-ChangeByte-ChangeBit-CopyPart-ChangeBinInt-
#142	REDUCE cov: 319 ft: 416 corp: 18/4334b lim: 259 exec/s: 0 rss: 39Mb L: 18/259 MS: 2 InsertByte-EraseBytes-
#145	NEW    cov: 319 ft: 417 corp: 19/4590b lim: 259 exec/s: 0 rss: 39Mb L: 256/259 MS: 3 ChangeBit-EraseBytes-CopyPart-
#163	NEW    cov: 319 ft: 418 corp: 20/4847b lim: 259 exec/s: 0 rss: 39Mb L: 257/259 MS: 3 ShuffleBytes-ChangeASCIIInt-CopyPart-
AddressSanitizer:DEADLYSIGNAL
=================================================================
==16==ERROR: AddressSanitizer: SEGV on unknown address 0x000000564510 (pc 0x0000004203a4 bp 0x000000000000 sp 0x7ffe20e7b580 T0)
==16==The signal is caused by a WRITE memory access.
SCARINESS: 30 (wild-addr-write)
    #0 0x4203a4 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:80:10
    #1 0x4203a4 in AtomicallySetQuarantineFlagIfAllocated /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:570:10
    #2 0x4203a4 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:647:10
    #3 0x497a61 in free /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:128:3
    #4 0x4ce544 in dhcp_server_handle_message /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:988:17
    #5 0x4d3330 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-dhcp-server.c:53:16
    #6 0x52c076 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:556:15
    #7 0x528690 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:470:3
    #8 0x52dc6f in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:698:19
    #9 0x5314ad in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/libfuzzer/FuzzerLoop.cpp:830:5
    #10 0x4ea731 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:824:6
    #11 0x4dbea7 in main /src/libfuzzer/FuzzerMain.cpp:19:10
    #12 0x7f3dce48382f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #13 0x41f078 in _start (/out/fuzz-dhcp-server+0x41f078)

DEDUP_TOKEN: atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>--AtomicallySetQuarantineFlagIfAllocated--__asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:80:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
==16==ABORTING
MS: 1 ChangeBit-; base unit: 29162b0d3ba3ffea813cca8ad7f94d8bf4190fc1
0x1,0x1,0x6,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x8,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x63,0x82,0x53,0x63,0x35,0x1,0x3,0x3d,0x2,0x2,0x2,0x32,0x4,0xa,0x0,0x0,0x2,0xff,
\x01\x01\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00c\x82Sc5\x01\x03=\x02\x02\x022\x04\x0a\x00\x00\x02\xff
artifact_prefix='./'; Test unit written to ./crash-c95b08926f42e836300ddb89aa2f7805fdad8d4e
Base64: AQEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDAwMDAwMDAwMDAwMDAwMAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjglNjNQEDPQICAjIECgAAAv8=
```
so I'd say it has something to do with the runtime

**Comment by evverx** [comment]
FWIW when I pass `ASAN_OPTIONS="alloc_dealloc_mismatch=0:allocator_may_return_null=1:allocator_release_to_os_interval_ms=500:check_malloc_usable_size=0:detect_container_overflow=1:detect_odr_violation=0:detect_leaks=1:detect_stack_use_after_return=1:fast_unwind_on_fatal=0:handle_abort=1:handle_segv=1:handle_sigill=1:max_uar_stack_size_log=16:print_scariness=1:quarantine_size_mb=10:strict_memcmp=1:strip_path_prefix=/workspace/:symbolize=1:use_sigaltstack=1:dedup_token_length=3"` to `./build/out/systemd/fuzz-dhcp-server` it seems to start missing the bug as well (without infra/helper.py)

**Comment by jonathanmetzman** [comment]
Very interesting. 
I would guess alloc_dealloc_mismatch is responsible (or maybe one of the other *alloc* options. Narrowing this down might help (it may be that we need the option for a reason and cant get rid of it though).
@kcc @morehouse any ideas why these ASAN options might cause us to miss bugs?

**Comment by jonathanmetzman** [comment]
@evverx 
Do you mind if I change the title?

**Comment by evverx** [comment]
Looks like detect_stack_use_after_return=1 is the culprit

**Comment by evverx** [comment]
> Do you mind if I change the title?

@jonathanmetzman not at all

**Comment by evverx** [comment]
What's weird though is that on Travis CI [`detect_stack_use_after_return=1` is passed to the fuzz target](https://github.com/systemd/systemd/blob/master/travis-ci/managers/debian.sh#L75) as well so it seems it's a combination of `detect_stack_use_after_return=1` with something else causing this

**Comment by inferno-chromium** [comment]
It might be hiding this one bug due to some weird memory layout difference, but i dont see why you should just disable it, this means it will actually not find any stack use after return bugs. I dont see anything on this to track on cifuzz side, we enable all these flags to find all sort of bugs.

**Comment by evverx** [comment]
I wouldn't say it's the only bug that wasn't caught by OSS-Fuzz but I agree it should be tracked elsewhere.
