### ISSUE TITLE
Clang hasn't been updated since November 19th

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#3805]
The current clang is built from [e84b7a5fe230e42b8e6fe451369874a773bf1867](https://github.com/llvm/llvm-project/commit/e84b7a5fe230e42b8e6fe451369874a773bf1867) (clang 10).
This was a few days after we (I) switched builds to checkout LLVM using git: https://github.com/google/oss-fuzz/commit/5668cc422c2c92d38a370545d3591039fb5bb8d4#diff-2ac6f4fc7d326765c42e2f3f30d5f2d5

Chromium's clang build is 4e0d9925d6a3561449bdd8def27fd3f3f1b3fb9f: (clang 11)

**Comment by evverx** [comment]
@jonathanmetzman given that https://github.com/google/oss-fuzz/issues/3798 seems to be a clang regression I wonder how long it usually takes for the `base-clang` image to get updated. I tried to rebuild it myself but it took git too long to clone llvm so I decided to not wait :-)

**Comment by jonathanmetzman** [comment]
>I wonder how long it usually takes for the base-clang image to get updated

Without this bug? It's usually every 2 weeks. It tracks Chrome's clang which tracks ToT pretty closely.

If you mean to ask how long from now will OSS-Fuzz's clang update, I'd say it will happen in tonight's build (a few hours from now I think).

**Comment by evverx** [comment]
> I'd say it will happen in tonight's build (a few hours from now I think).

Got it. I'll try to rebuild the fuzz target tomorrow morning then.

**Comment by evverx** [comment]
With the latest clang images (clang version 11.0.0 (https://github.com/llvm/llvm-project.git 99ac9ce7016d701b43b8f0c308dc3463da57d983)) the fuzzer seems to either keep going 
 or failing sporadically (more often than earlier though) with
```
#1246	NEW    cov: 339 ft: 441 corp: 30/7356b lim: 259 exec/s: 0 rss: 42Mb L: 259/259 MS: 3 ChangeBit-ShuffleBytes-ChangeByte-
AddressSanitizer:DEADLYSIGNAL
=================================================================
==16==ERROR: AddressSanitizer: SEGV on unknown address 0x00000055c9b0 (pc 0x000000420514 bp 0x000000000000 sp 0x7ffe7e1e4990 T0)
==16==The signal is caused by a WRITE memory access.
SCARINESS: 30 (wild-addr-write)
    #0 0x420514 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:80:10
    #1 0x420514 in AtomicallySetQuarantineFlagIfAllocated /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:570:10
    #2 0x420514 in __asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:647:10
    #3 0x497751 in free /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:128:3
    #4 0x4ce953 in freep /work/build/../../src/systemd/src/basic/alloc-util.h:83:9
    #5 0x4ce0a7 in dhcp_server_handle_message /work/build/../../src/systemd/src/libsystemd-network/sd-dhcp-server.c:988:17
    #6 0x4d2fa0 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/fuzz/fuzz-dhcp-server.c:53:16
    #7 0x527e36 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:556:15
    #8 0x524430 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool*) /src/libfuzzer/FuzzerLoop.cpp:470:3
    #9 0x52987f in fuzzer::Fuzzer::MutateAndTestOne() /src/libfuzzer/FuzzerLoop.cpp:698:19
    #10 0x52c7bd in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/libfuzzer/FuzzerLoop.cpp:832:5
    #11 0x4e9b9f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:826:6
    #12 0x4dbb67 in main /src/libfuzzer/FuzzerMain.cpp:19:10
    #13 0x7f7b01faf82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x41f1a8 in _start (/out/fuzz-dhcp-server+0x41f1a8)

DEDUP_TOKEN: atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>--AtomicallySetQuarantineFlagIfAllocated--__asan::Allocator::Deallocate(void*, unsigned long, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType)
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /src/llvm-project/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:80:10 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
==16==ABORTING
```
so it looks like it's a clang regression that hasn't been fixed yet unfotrunately
