### ISSUE TITLE
presubmit infra_tests seems to be failing

### ISSUE THREAD

**Issue by Dor1s** [google/oss-fuzz#4112]
see https://github.com/google/oss-fuzz/runs/859508209

also reproduces locally:

```
$ infra/presubmit.py infra-tests
<...>
======================================================================
ERROR: test_build_fuzzers_from_commit (build_specified_commit_test.BuildImageIntegrationTests)
Tests if the fuzzers can build at a proper commit.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<...>/projects/oss-fuzz/infra/build_specified_commit_test.py", line 59, in test_build_fuzzers_from_commit
    build_specified_commit.build_fuzzers_from_commit(test_case.old_commit,
  File "<...>/projects/oss-fuzz/infra/build_specified_commit.py", line 215, in build_fuzzers_from_commit
    build_repo_manager.checkout_commit(commit, clean=False)
  File "<...>/projects/oss-fuzz/infra/repo_manager.py", line 193, in checkout_commit
    self.fetch_unshallow()
  File "<...>/projects/oss-fuzz/infra/repo_manager.py", line 171, in fetch_unshallow
    self.git(['fetch', '--unshallow'], check_result=True)
  File "<...>/projects/oss-fuzz/infra/repo_manager.py", line 57, in git
    return utils.execute(['git'] + cmd,
  File "<...>/projects/oss-fuzz/infra/utils.py", line 63, in execute
    raise RuntimeError(
RuntimeError: Executing command 'git fetch --unshallow' failed with error: error: cannot open .git/FETCH_HEAD: Permission denied
.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'Makefile.am'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<...>/projects/oss-fuzz/infra/build_specified_commit_test.py", line 71, in test_build_fuzzers_from_commit
    self.assertNotEqual(new_error_code, old_error_code)
  File "/usr/lib/python3.8/tempfile.py", line 967, in __exit__
    self.cleanup()
  File "/usr/lib/python3.8/tempfile.py", line 971, in cleanup
    self._rmtree(self.name)
  File "/usr/lib/python3.8/tempfile.py", line 953, in _rmtree
    _rmtree(name, onerror=onerror)
  File "/usr/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.8/shutil.py", line 652, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.8/tempfile.py", line 938, in onerror
    resetperms(_os.path.dirname(path))
  File "/usr/lib/python3.8/tempfile.py", line 934, in resetperms
    _os.chmod(path, 0o700)
PermissionError: [Errno 1] Operation not permitted: '/tmp/tmpdi02cq48/src/usrsctp'

----------------------------------------------------------------------
Ran 43 tests in 391.295s

FAILED (errors=1, skipped=2)
Failed.

```

**Comment by Dor1s** [comment]
@oliverchang @jonathanmetzman in case you've been changing `build_specified_commit_test` functionality recently

**Comment by oliverchang** [comment]
These pass locally for me, but require sudo. I guess that's the issue here.

**Comment by jonathanmetzman** [comment]
I haven't changed it. My best guess is that some of the other tests added or github actions migration did this. But I think @oliverchang is right.

**Comment by jonathanmetzman** [comment]
I fixed this.
