### ISSUE TITLE
libFuzzer should show deadly signal type or just let sanitizer handle the stack its own way.

### ISSUE THREAD

**Issue by inferno-chromium** [google/oss-fuzz#447]
Looks like libFuzzer now catches the signals like ABRT, ILL, etc and just shows "ERROR: libFuzzer: deadly signal". Previously we had the more descriptive output with  "AddressSanitizer: ABRT on unknown address 0x03e900003a17 (pc 0x7f46f02e8cc9 bp 0x7f46f0432830 sp 0x7ffee23b98a8 T0)" with signal type, pc, etc. That was the more preferred way. If we can't keep that, please switch libFuzzer to show signal type (and then we will add parsing signature on clusterfuzz side.).

New::
==98407== ERROR: libFuzzer: deadly signal
    #0 0x4d1af0 in __sanitizer_print_stack_trace (/usr/local/google/home/tanin/projects/chromium/src/out/clusterfuzz_4832553975676928_29d0ee0571a18cb30818f2c4288118e0a57142e7/pdf_jpx_fuzzer+0x4d1af0)
    #1 0x55db53 in fuzzer::Fuzzer::CrashCallback() third_party/libFuzzer/src/FuzzerLoop.cpp:280:5
    #2 0x55da66 in fuzzer::Fuzzer::StaticCrashSignalCallback() third_party/libFuzzer/src/FuzzerLoop.cpp:264:6
    #3 0x61be47 in fuzzer::CrashHandler(int, siginfo*, void*) third_party/libFuzzer/src/FuzzerUtilPosix.cpp:37:3

Old::
==14871==ERROR: AddressSanitizer: ABRT on unknown address 0x03e900003a17 (pc 0x7f46f02e8cc9 bp 0x7f46f0432830 sp 0x7ffee23b98a8 T0)
SCARINESS: 10 (signal)
#0 0x7f46f02e8cc8 in gsignal /build/buildd/eglibc-2.19/nptl/sysdeps/unix/sysv/linux/raise.c:56
#1 0x7f46f02ec0d7 in abort /build/buildd/eglibc-2.19/stdlib/abort.c:89
#2 0x7f46f02e1b85 in __assert_fail_base /build/buildd/eglibc-2.19/assert/assert.c:92
#3 0x7f46f02e1c31 in __assert_fail /build/buildd/eglibc-2.19/assert/assert.c:101

**Comment by inferno-chromium** [comment]
Also, caused some developer pain on chromium side - https://bugs.chromium.org/p/chromium/issues/detail?id=700485

**Comment by inferno-chromium** [comment]
WontFix, i think Tanin forgot to read this.
NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
| Return code is non-zero (77).

The tool is wrong. Sorry for false positive.
