### ISSUE TITLE
Coverage failure in FLAC

### ISSUE THREAD

**Issue by erikd** [google/oss-fuzz#4490]
In this coverage failure https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24040

The failure is: https://oss-fuzz-build-logs.storage.googleapis.com/log-087f5d1b-e972-4751-9132-4eef2aaab2f4.txt

```
Step #5: [0;31merror: /workspace/out/coverage/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h: No such file or directory
Step #5: [0m[0;31mwarning: The file '/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h' isn't covered.
Step #5: [0m[2020-09-22 10:06:43,513 DEBUG] Finished generating per-file code coverage summary.
Step #5: [2020-09-22 10:06:43,513 DEBUG] Generating file view html index file as: "/workspace/out/coverage/report/linux/file_view_index.html".
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #5:     return _CmdPostProcess(args)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #5:     processor.PrepareHtmlReport()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 578, in PrepareHtmlReport
Step #5:     self.file_view_path)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 450, in GenerateFileViewHtmlIndexFile
Step #5:     self.GetCoverageHtmlReportPathForFile(file_path),
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 423, in GetCoverageHtmlReportPathForFile
Step #5:     self._MapToLocal(file_path)), '"%s" is not a file.' % file_path
Step #5: AssertionError: "/usr/lib/jvm/java-8-openjdk-amd64/include/jni.h" is not a file.
```
That error has nothing to do with my project which does not use **any** Java.

**Comment by Dor1s** [comment]
Did you mean to report this for `libsndfile` or `flac` project?

**Comment by erikd** [comment]
Project name is not even important. Neither FLAC nor libsndfile use Java.

**Comment by Dor1s** [comment]
flac project does install `default-jdk` (https://github.com/google/oss-fuzz/blob/master/projects/flac/Dockerfile#L18) and passes jni headers to to the build (https://github.com/google/oss-fuzz/blob/master/projects/flac/build.sh#L56).

To fix that failure, we should exclude those files from the coverage report generation: https://github.com/google/oss-fuzz/pull/4496
