### ISSUE TITLE
Uninitialised msan memory passed to LLVMFuzzerCustomMutator

### ISSUE THREAD

**Issue by mkj** [google/oss-fuzz#4605]
It seems libfuzzer passes uninitialised memory as input to `LLVMFuzzerCustomMutator()`? The simple testcase below hits it, I see the same thing in Dropbear. https://oss-fuzz.com/gcs-redirect?path=%2Fdropbear-logs.clusterfuzz-external.appspot.com%2FlibFuzzer_dropbear_fuzzer-preauth_nomaths%2Flibfuzzer_msan_dropbear%2F2020-11-04%2F01%3A33%3A04%3A973098.log

```c
// fuzz-simple.c
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdio.h>

int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    setlinebuf(stdout);
    return 0;
}

size_t LLVMFuzzerCustomMutator(uint8_t *Data, size_t Size, size_t MaxSize, unsigned int Seed) {
    for (size_t i = 0; i < Size; i++) {
        printf("dat %zu 0x%hhx\n", i, Data[i]);
        if (Data[i] % 15 == 0) {
            printf("fuzz\n");
        }
    }
    return Size;
}
```

```shell
#building inside  './infra/helper.py shell --sanitizer memory'
clang -O1 -fno-omit-frame-pointer -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -Wno-pointer-sign -fno-strict-overflow -o fuzz-simple.o fuzz-simple.c -c
clang++ -O1 -fno-omit-frame-pointer -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=memory -fsanitize-memory-track-origins -fsanitize=fuzzer-no-link -stdlib=libc++ -o fuzz-simple fuzz-simple.o   -fsanitize=fuzzer
```

```
./fuzz-simple 
INFO: found LLVMFuzzerCustomMutator (0x522890). Disabling -len_control by default.
INFO: Seed: 2814934507
INFO: Loaded 1 modules   (7 inline 8-bit counters): 7 [0x77fe10, 0x77fe17), 
INFO: Loaded 1 PC tables (7 PCs): 7 [0x540018,0x540088), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 1 ft: 1 corp: 1/1b exec/s: 0 rss: 69Mb
dat 0 0xa
==4199==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x522b35 in LLVMFuzzerCustomMutator /out/m/fuzz-simple.c:14:13
    #1 0x46acc4 in fuzzer::MutationDispatcher::MutateImpl(unsigned char*, unsigned long, unsigned long, std::__Fuzzer::vector<fuzzer::MutationDispatcher::Mutator, fuzzer::fuzzer_allocator<fuzzer::MutationDispatcher::Mutator> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMutate.cpp:525:22
    #2 0x4592d1 in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:733:20
    #3 0x459d95 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:879:5
    #4 0x449114 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:902:6
    #5 0x471282 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #6 0x7ff07387f83f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/../csu/libc-start.c:291
    #7 0x41e4b8 in _start (/out/m/fuzz-simple+0x41e4b8)

  Uninitialized value was stored to memory at
    #0 0x4cace9 in __msan_memcpy /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:1558:3
    #1 0x45920a in fuzzer::Fuzzer::MutateAndTestOne() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:713:3
    #2 0x459d95 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:879:5
    #3 0x449114 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:902:6
    #4 0x471282 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #5 0x7ff07387f83f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/../csu/libc-start.c:291

  Uninitialized value was created by a heap allocation
    #0 0x4d13ed in malloc /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:901:3
    #1 0x431d67 in operator new(unsigned long) (/out/m/fuzz-simple+0x431d67)
    #2 0x4586c1 in operator= /work/llvm-stage2/projects/compiler-rt/lib/fuzzer/libcxx_fuzzer_x86_64/include/c++/v1/vector:1408:9
    #3 0x4586c1 in fuzzer::InputCorpus::AddToCorpus(std::__Fuzzer::vector<unsigned char, fuzzer::fuzzer_allocator<unsigned char> > const&, unsigned long, bool, bool, bool, std::__Fuzzer::chrono::duration<long long, std::__Fuzzer::ratio<1l, 1000000l> >, std::__Fuzzer::vector<unsigned int, fuzzer::fuzzer_allocator<unsigned int> > const&, fuzzer::DataFlowTrace const&, fuzzer::InputInfo const*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerCorpus.h:218:10
    #4 0x45795b in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:526:16
    #5 0x4597f2 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:793:5
    #6 0x459a99 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:841:3
    #7 0x449114 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:902:6
    #8 0x471282 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #9 0x7ff07387f83f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/../csu/libc-start.c:291

SUMMARY: MemorySanitizer: use-of-uninitialized-value /out/m/fuzz-simple.c:14:13 in LLVMFuzzerCustomMutator
Exiting
MS: 0 ; base unit: adc83b19e793491b1c6ea0fd8b46cd9f32e592fc


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
```

**Comment by jonathanmetzman** [comment]
@morehouse could you please take a look?
CC @kcc @hctim

**Comment by guidovranken** [comment]
I also got this one today: https://oss-fuzz.com/testcase-detail/6112782397341696

**Comment by morehouse** [comment]
Fixed upstream in https://github.com/llvm/llvm-project/commit/423024904825d147c69e8999537b6b813bc24999.

Tossing this back to @jonathanmetzman to close when OSS-Fuzz rolls past the fix.

**Comment by jonathanmetzman** [comment]
@inferno-chromium this is blocked because of https://github.com/google/oss-fuzz/pull/5131
@vanhauser-thc are we still stuck on clang-12 for now?

**Comment by vanhauser-thc** [comment]
no ... I mentioned that in the another issue 2 weeks ago or so.

**Comment by guidovranken** [comment]
This is how you can solve it as an OSS-Fuzz user until the fix arrives: https://github.com/guidovranken/cryptofuzz/commit/3cd5cc3b1f9fff65787fdf1cb385743232e120b1
