### ISSUE TITLE
Coverage builds failing for all projects (revert is in, should show on Nov 7 builds)

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#4608]
Per https://oss-fuzz-build-logs.storage.googleapis.com/ every single project's coverage build failed yesterday, ones I checked have

```
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #5:     return _CmdPostProcess(args)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #5:     processor.PrepareHtmlReport()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 572, in PrepareHtmlReport
Step #5:     self.RenameDefaultCoverageDirectory()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 556, in RenameDefaultCoverageDirectory
Step #5:     MergeTwoDirectories(default_report_subdir_path, self.report_root_dir)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 727, in MergeTwoDirectories
Step #5:     for filename in os.listdir(src_dir_path):
```

Sorry if a dup but I didn't see any related issues or PRs.

**Comment by inferno-chromium** [comment]
```
Step #5: [2020-11-05 09:01:02,111 INFO] Finished finding shared libraries for targets.
Step #5: [0;31merror: /workspace/out/coveragesrc/bzip2/blocksort.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/blocksort.c' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2_decompress_target.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2_decompress_target.c' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2/bzlib.h: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/bzlib.h' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2/compress.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/compress.c' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2/bzlib_private.h: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/bzlib_private.h' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2/decompress.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/decompress.c' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2/huffman.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/huffman.c' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2_compress_target.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2_compress_target.c' isn't covered.
Step #5: [0m[0;31merror: /workspace/out/coveragesrc/bzip2/bzlib.c: No such file or directory
Step #5: [0m[0;31mwarning: The file '/src/bzip2/bzlib.c' isn't covered.
Step #5: [0m[2020-11-05 09:01:02,237 ERROR] Default coverage report dir does not exist: /workspace/out/coverage/report/coverage.
Step #5: Traceback (most recent call last):
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 829, in <module>
Step #5:     sys.exit(Main())
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 823, in Main
Step #5:     return _CmdPostProcess(args)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 780, in _CmdPostProcess
Step #5:     processor.PrepareHtmlReport()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 572, in PrepareHtmlReport
Step #5:     self.RenameDefaultCoverageDirectory()
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 556, in RenameDefaultCoverageDirectory
Step #5:     MergeTwoDirectories(default_report_subdir_path, self.report_root_dir)
Step #5:   File "/opt/code_coverage/coverage_utils.py", line 727, in MergeTwoDirectories
Step #5:     for filename in os.listdir(src_dir_path):
Step #5: FileNotFoundError: [Errno 2] No such file or directory: '/workspace/out/coverage/report/coverage'
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image bzip2
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage bzip2
Step #5: python infra/helper.py coverage bzip2
Step #5: ********************************************************************************
Finished Step #5
ERROR
ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: step exited with non-zero status: 1
```

Something broke with path equivalence use in llvm coverage, switching to symlink. tested this works. builds will be fixed tmrw.

**Comment by inferno-chromium** [comment]
That fix was wrong, so will have to freeze clang to older version for now.

**Comment by inferno-chromium** [comment]
Looks like this sys::path::removedots removes the trailing /
https://github.com/llvm/llvm-project/commit/e92eeaf3c21923151cf86c706e396b613145f142#diff-4d7af1cc97339eef69e32df0f0d8107dd921b5384e05261eec1509676032144d
@Dor1s - on monday, any thoughts on what we should do here, should be revert or ask author to remove that call.

For now, i will freeze older clang.

**Comment by ZequanWu** [comment]
Do you have the exact command invocation for llvm-cov so I can debug on it?

**Comment by inferno-chromium** [comment]
> Do you have the exact command invocation for llvm-cov so I can debug on it?

```
llvm-cov show -format=html -output-dir=/out/report -Xdemangler c++filt -Xdemangler -n -instr-profile=/out/dumps/merged.profdata bzip2_decompress_target -object=bzip2_compress_target -path-equivalence=/,/out  
error: /outsrc/bzip2/blocksort.c: No such file or directory
```
Basically, now we cant do `-path-equivalence=/,/out` so paths like /src -> /out/src now become /outsrc as the trailing / is stripped by your sys::path::removedots calls, can you please remove those two calls @ZequanWu

**Comment by ZequanWu** [comment]
Some existing tests failed due change of the behavior, and those tests didn't test the real things they want to test before the change. 

I'll try to remove the two calls and find a way to fix the broken tests.

**Comment by ZequanWu** [comment]
I put a fix here: https://github.com/llvm/llvm-project/commit/c75a0a1e9dc29be4e00d37d0d00288afc1a6153f

**Comment by inferno-chromium** [comment]
> I put a fix here: [llvm/llvm-project@c75a0a1](https://github.com/llvm/llvm-project/commit/c75a0a1e9dc29be4e00d37d0d00288afc1a6153f)

We can only test after 2 weeks, since we rely on clang rolled in chromium (since chromium clang roll confirms that rolled version is stable, otherwise can break our 350+ integrated projects in unexpected ways). Thanks @ZequanWu for the fix, it does look right.

**Comment by Dor1s** [comment]
Thanks @ZequanWu !

Ideally, we should also put up a test upstream that would verify the expected behavior. There is https://github.com/llvm/llvm-project/blob/master/llvm/test/tools/llvm-cov/path_equivalence.c, which perhaps can be extended

**Comment by ZequanWu** [comment]
I put a test case: https://github.com/llvm/llvm-project/commit/78b48426a28255b55f1dae5e94adede37886c1e2

**Comment by Dor1s** [comment]
Thanks again @ZequanWu

**Comment by Dor1s** [comment]
Looks like Chromium's clang is now rolled past the fix (up to https://github.com/llvm/llvm-project/commit/6ef07111a402a87fda096b6b8d7327e4aa89d4d6).

**Comment by jonathanmetzman** [comment]
I think we fixed this issue.
