### ISSUE TITLE
CI Fuzz doesn't detect a problem it should

### ISSUE THREAD

**Issue by kroeckx** [google/oss-fuzz#4767]
In https://github.com/openssl/openssl/pull/13591, the existing tests going over our fuzz corpus found a problem, but CI-Fuzz job https://github.com/openssl/openssl/actions/runs/395609838 didn't rerport any problem.

**Comment by jonathanmetzman** [comment]
Thanks for this report. I can't think of an obvious reason. Let me try to repro this locally and look into it.

**Comment by jonathanmetzman** [comment]
I'm looking into this now. I can repro a sanitizer issue on the testcase in question.
My best guess is that we aren't using seed corpora correctly. Lemme check this to be sure.

**Comment by jonathanmetzman** [comment]
Weirdly I get an error when I run CIFuzz locally on this PR:
```
#512    pulse  cov: 4473 ft: 12689 corp: 480/4632b exec/s: 102 rss: 76Mb                                                                                      
AddressSanitizer:DEADLYSIGNAL                                                                                                                                 
=================================================================                                                                                             
==558==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x0000006afcbf bp 0x7ffc6eb1bf40 sp 0x7ffc6eb1bf20 T0)                             
==558==The signal is caused by a READ memory access.                                                                                                          
==558==Hint: address points to the zero page.                                                                                                                 
SCARINESS: 10 (null-deref)                                                                                                                                    
    #0 0x6afcbf in BN_num_bits /src/openssl/crypto/bn/bn_lib.c:180:16
    #1 0x6e2077 in DSA_bits /src/openssl/crypto/dsa/dsa_lib.c:338:12
    #2 0x934ed7 in dsa_get_params /src/openssl/providers/implementations/keymgmt/dsa_kmgmt.c:281:35
    #3 0x770f2a in evp_keymgmt_get_params /src/openssl/crypto/evp/keymgmt_meth.c:371:12
    #4 0x76d841 in evp_keymgmt_util_cache_keyinfo /src/openssl/crypto/evp/keymgmt_lib.c:225:13
    #5 0x76d436 in evp_keymgmt_util_assign_pkey /src/openssl/crypto/evp/keymgmt_lib.c:62:5
    #6 0x76dadc in evp_keymgmt_util_make_pkey /src/openssl/crypto/evp/keymgmt_lib.c:73:13
    #7 0x73b2a5 in decoder_construct_EVP_PKEY /src/openssl/crypto/encode_decode/decoder_pkey.c:166:21
    #8 0x735bfc in decoder_process /src/openssl/crypto/encode_decode/decoder_lib.c:536:16
    #9 0x8dcdcd in der2key_decode /src/openssl/providers/implementations/encode_decode/decode_der2key.c:370:14
    #10 0x7360b0 in decoder_process /src/openssl/crypto/encode_decode/decoder_lib.c:627:14
    #11 0x735946 in OSSL_DECODER_from_bio /src/openssl/crypto/encode_decode/decoder_lib.c:47:10
    #12 0x7366ac in OSSL_DECODER_from_data /src/openssl/crypto/encode_decode/decoder_lib.c:93:9
    #13 0x67f61d in d2i_PrivateKey_ex /src/openssl/crypto/asn1/d2i_pr.c:53:15
    #14 0x67fe31 in d2i_AutoPrivateKey_ex /src/openssl/crypto/asn1/d2i_pr.c:149:12
    #15 0x67fe65 in d2i_AutoPrivateKey /src/openssl/crypto/asn1/d2i_pr.c:155:12 
    #16 0x4cf116 in FuzzerTestOneInput /src/openssl/fuzz/asn1.c:355:5
    #17 0x4cf690 in LLVMFuzzerTestOneInput /src/openssl/fuzz/driver.c:28:12
    #18 0x51bb56 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:599:15
    #19 0x519b01 in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) /src/libfuzzer/FuzzerLoop.cpp:505:3
    #20 0x51ea01 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/libfuzz
er/FuzzerLoop.cpp:814:7
    #21 0x51f385 in fuzzer::Fuzzer::Loop(std::__1::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/libfuzzer/FuzzerLoop.cpp:845
:3
    #22 0x4de207 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:906:6
    #23 0x4cf777 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #24 0x7f6d5bda783f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #25 0x41fd58 in _start (/out/asn1+0x41fd58)
```

Maybe the time limits prevents the fuzzer from executing the testcase.
One definite bug I can identify here is that check_build doesn't discover this issue.

**Comment by jonathanmetzman** [comment]
And I get the same crash when I run CIFuzz on my own repo: https://github.com/jonathanmetzman/openssl/runs/1520850069?check_suite_focus=true 

@kroeckx could you try rerunning the job? My best guess at this point is cosmic radiation :-(

**Comment by jonathanmetzman** [comment]
Probably too late, but maybe @kroeckx could you please retry this for me.

**Comment by kroeckx** [comment]
I'm not sure how to test this. The only thing I can think of is to
create a PR with broken code. I can't find the old commit that was
broken.
