### ISSUE TITLE
Build function unittests don't work consistently

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5025]
I suspect it has something to do with not importing like this `build.functions.datastore_entities` and instead importing `datastore_entities`.
If I run all unittests (using `python infra/presubmit.py infra-tests --all-files`
```
ImportError: Failed to import test module: functions.update_build_status_test
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.8/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/tmp/oss-fuzz/infra/build/functions/update_build_status_test.py", line 23, in <module>
    from datastore_entities import BuildsHistory
ModuleNotFoundError: No module named 'datastore_entities'
```

**Comment by jonathanmetzman** [comment]
cc @oliverchang

**Comment by inferno-chromium** [comment]
Need to remember to remove blocklist after this is fixed.
