### ISSUE TITLE
Issues with new git diffing

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#5068]
1. Fails on new repo:
```
$ cd /tmp
$ git clone https://github.com/google/oss-fuzz
$ cd oss-fuzz
$ python infra/presubmit.py
fatal: Not a valid object name FETCH_HEAD
Traceback (most recent call last):
  File "infra/presubmit.py", line 427, in <module>
    sys.exit(main())
  File "infra/presubmit.py", line 399, in main
    relevant_files = get_changed_files()
  File "infra/presubmit.py", line 326, in get_changed_files
    branch_commit_hash = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'merge-base', 'FETCH_HEAD', 'origin/HEAD']' returned non-zero exit status 128.
```
2. Gives false positives on: master when behind origin/master (on my main repo).
```
$ git checkout master
$ git reset HEAD~
M       projects/poppler/Dockerfile
$ git reset --hard
python infra/presubmit.py
Changed files: projects/poppler/Dockerfile
```
2 is slightly worrying since I suspect it means that the issue I reported where changes in master that weren't pulled into a PR affect the results.

**Comment by inferno-chromium** [comment]
On a new repo, previous code fails as well

```
$ git diff FETCH_HEAD
fatal: ambiguous argument 'FETCH_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

I don't understand 2), can you explain this more.

**Comment by jonathanmetzman** [comment]
> I don't understand 2), can you explain this more.

What do you think the expected behavior should be in 2? I don't expect it to say Dockerfile is changed, there should be no difference from master since I'm on master right?

**Comment by inferno-chromium** [comment]
> > I don't understand 2), can you explain this more.
> 
> What do you think the expected behavior should be in 2? I don't expect it to say Dockerfile is changed, there should be no difference from master since I'm on master IMO.

Is this a common occurrence, i dont usually do this, like pull to an earlier revision on a branch? Expected behavior is not that bad if we are checking out a slightly old revision (like N-1, N-2).

I dont have any other ideas to fix this, current behavior takes care of the stale PR problem and avoid unnecessary diffs, project builds, etc.

**Comment by jonathanmetzman** [comment]
> > > I don't understand 2), can you explain this more.
> > 
> > 
> > What do you think the expected behavior should be in 2? I don't expect it to say Dockerfile is changed, there should be no difference from master since I'm on master IMO.
> 
> Is this a common occurrence, 

Probably not.

> I dont have any other ideas to fix this, current behavior takes care of the stale PR problem and avoid unnecessary diffs, project builds, etc.

Yeah, probably best to leave then.
