### ISSUE TITLE
Running shell subcommand results in backtrace...

### ISSUE THREAD

**Issue by sebras** [google/oss-fuzz#5300]
According to the [documentation](https://google.github.io/oss-fuzz/advanced-topics/debugging/) one ought to be able to run

```
python infra/helper.py shell base-runner-debug
```

in order to end up in a shell with gdb available. Bisecting reveals commit 433ddc2337bf58d1973231c1a644357bbd557257 as being the culprit. After this commit the command results in a backtrace like so:

```
python infra/helper.py shell base-runner-debug
Running: docker build -t gcr.io/oss-fuzz-base/base-runner-debug infra/base-images/base-runner-debug
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM gcr.io/oss-fuzz-base/base-runner
 ---> 2cf39c222ae7
Step 2/2 : RUN apt-get update && apt-get install -y gdb valgrind zip
 ---> Using cache
 ---> 0d84356946dc
Successfully built 0d84356946dc
Successfully tagged gcr.io/oss-fuzz-base/base-runner-debug:latest
Traceback (most recent call last):
  File "infra/helper.py", line 1003, in <module>
    sys.exit(main())
  File "infra/helper.py", line 223, in main
    return shell(args)
  File "infra/helper.py", line 962, in shell
    'FUZZING_LANGUAGE=' + _get_project_language(args.project_name),
  File "infra/helper.py", line 317, in _get_project_language
    with open(project_yaml_path) as file_handle:
IOError: [Errno 2] No such file or directory: '/home/user/src/oss-fuzz/projects/base-runner-debug/project.yaml'
```

I will provide two commits fixing this in a short while.

**Comment by sebras** [comment]
Since #5301 was merged this issue is resolved now...
