### ISSUE TITLE
bad_build_check --sanitizer=memory seems to be broken

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#5349]
```sh
$ sudo ./infra/helper.py build_fuzzers  --clean --sanitizer=memory selinux
...
Running: docker run --rm --privileged -i -v /home/vagrant/oss-fuzz/build/out/selinux:/out -v /home/vagrant/oss-fuzz/build/work/selinux:/work -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c -e MSAN_LIBS_PATH=/work/msan gcr.io/oss-fuzz-base/base-sanitizer-libs-builder patch_build.py /out
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libpthread.so.0
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/librt.so.1
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libdl.so.2
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libm.so.6
WARNING: Instrumented library not found for /usr/lib/x86_64-linux-gnu/libstdc++.so.6
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libgcc_s.so.1
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libm.so.6
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libpthread.so.0
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/librt.so.1
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libdl.so.2
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libgcc_s.so.1
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6
WARNING: Instrumented library not found for /lib/x86_64-linux-gnu/libc.so.6
Copying instrumented lib to /out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1
Patching rpath for /out/llvm-symbolizer from $ORIGIN/../lib to $ORIGIN/instrumented_libraries/lib/x86_64-linux-gnu:$ORIGIN/../lib
```
```sh
$ sudo ./infra/helper.py check_build --sanitizer=memory selinux
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c -v /home/vagrant/oss-fuzz/build/out/selinux:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py
INFO: performing bad build checks for /tmp/not-out/secilc-fuzzer
Broken fuzz targets 1
/tmp/not-out/secilc-fuzzer
BAD BUILD: /tmp/not-out/secilc-fuzzer seems to have either startup crash or exit:
/tmp/not-out/secilc-fuzzer -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1337
INFO: Loaded 1 modules   (14853 inline 8-bit counters): 14853 [0x9c6248, 0x9c9c4d),
INFO: Loaded 1 PC tables (14853 PCs): 14853 [0x9c9c50,0xa03ca0),
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
At least one initial sid must be defined in the policy
INFO: A corpus is not provided, starting from an empty corpus
At least one initial sid must be defined in the policy
#2	INITED cov: 285 ft: 286 corp: 1/1b exec/s: 0 rss: 66Mb
Symbol not inside parenthesis at line 1 of fuzz
	NEW_FUNC[1/1]: llvm-symbolizer: symbol lookup error: /tmp/not-out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1: undefined symbol: __msan_va_arg_overflow_size_tls
==45==WARNING: external symbolizer didn't start up correctly!

ERROR: 100.0% of fuzz targets seem to be broken. See the list above for a detailed information.
Check build failed.
```

Looking at "Patching rpath for /out/llvm-symbolizer", I think the culprit is the script patching `rpath`. Looks like it is a side effect of fba71c70ca7bfc6aeed.

**Comment by inferno-chromium** [comment]
Can you please add steps to reproduce. I dont know why builds are not failing in the builders, is it just local?

**Comment by evverx** [comment]
I just ran
```sh
./infra/helper.py pull_images
./infra/helper.py build_fuzzers --sanitizer=memory selinux
./infra/helper.py check_build --sanitizer=memory selinux
```

**Comment by inferno-chromium** [comment]
> I just ran
> 
> ```shell
> ./infra/helper.py pull_images
> ./infra/helper.py build_fuzzers --sanitizer=memory selinux
> ./infra/helper.py check_build --sanitizer=memory selinux
> ```

We are running really low on cycles, can you try debugging this, fix should go in somewhere in https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-sanitizer-libs-builder/patch_build.py
to build
infra/helper.py build_image base-sanitizer-libs-builder
then 
> ./infra/helper.py build_fuzzers --sanitizer=memory selinux
> ./infra/helper.py check_build --sanitizer=memory selinux

**Comment by evverx** [comment]
I'll try to take a look next week. Until then I'm just going to keep passing `MSAN_SYMBOLIZER_PATH` to `check_build` to make it work:
```sh
sudo ./infra/helper.py check_build -e MSAN_SYMBOLIZER_PATH=/usr/local/bin/llvm-symbolizer --sanitizer=memory selinux
```

**Comment by jonathanmetzman** [comment]
Has this been fixed?

**Comment by evverx** [comment]
No, it hasn't. I just keep using the workaround to get it to work.

**Comment by MarcoFalke** [comment]
I can also reproduce this issue and can confirm that `MSAN_SYMBOLIZER_PATH` fixes it.

<details><summary>Example output with and without `MSAN_SYMBOLIZER_PATH`:</summary>

```
# python infra/helper.py check_build  --sanitizer memory --engine libfuzzer  $PROJECT_NAME 
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -v /root/oss-fuzz/build/out/bitcoin-core:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py
INFO: performing bad build checks for /tmp/not-out/process_message_filterclear
INFO: performing bad build checks for /tmp/not-out/coins_view
Check build passed.
root@ubuntu-32gb-hel1-1:~/oss-fuzz# python infra/helper.py reproduce $PROJECT_NAME coins_view ./6e13b65b-6648-47dd-b1ff-b6f005ecf8dc\?testcase_id\=6289089386119168 
Running: docker run --rm --privileged -i -v /root/oss-fuzz/build/out/bitcoin-core:/out -v '/root/oss-fuzz/6e13b65b-6648-47dd-b1ff-b6f005ecf8dc?testcase_id=6289089386119168:/testcase' -t gcr.io/oss-fuzz-base/base-runner reproduce coins_view -runs=100
+ FUZZER=coins_view
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer coins_view -runs=100 /testcase
/out/coins_view -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 755239154
INFO: Loaded 1 modules   (176398 inline 8-bit counters): 176398 [0x55b3a5db8f38, 0x55b3a5de4046), 
INFO: Loaded 1 PC tables (176398 PCs): 176398 [0x55b3a5de4048,0x55b3a6095128), 
/out/coins_view: Running 1 inputs 100 time(s) each.
Running: /testcase
==13==WARNING: MemorySanitizer: use-of-uninitialized-value
llvm-symbolizer: symbol lookup error: /out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1: undefined symbol: __msan_va_arg_overflow_size_tls
==13==WARNING: Can't read from symbolizer at fd 3
llvm-symbolizer: symbol lookup error: /out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1: undefined symbol: __msan_va_arg_overflow_size_tls
==13==WARNING: Can't read from symbolizer at fd 3
llvm-symbolizer: symbol lookup error: /out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1: undefined symbol: __msan_va_arg_overflow_size_tls
==13==WARNING: Can't read from symbolizer at fd 3
llvm-symbolizer: symbol lookup error: /out/instrumented_libraries/lib/x86_64-linux-gnu/libz.so.1: undefined symbol: __msan_va_arg_overflow_size_tls
==13==WARNING: Can't read from symbolizer at fd 3
==13==WARNING: Failed to use and restart external symbolizer!
    #0 0x55b3a312a6fc  (/out/coins_view+0x7296fc)
    #1 0x55b3a3128ecd  (/out/coins_view+0x727ecd)
    #2 0x55b3a310c3fb  (/out/coins_view+0x70b3fb)
    #3 0x55b3a310ab84  (/out/coins_view+0x709b84)
    #4 0x55b3a2fc5146  (/out/coins_view+0x5c4146)
    #5 0x55b3a2fc4f62  (/out/coins_view+0x5c3f62)
    #6 0x55b3a2fc4df2  (/out/coins_view+0x5c3df2)
    #7 0x55b3a2fc0d04  (/out/coins_view+0x5bfd04)
    #8 0x55b3a47fa5a9  (/out/coins_view+0x1df95a9)
    #9 0x55b3a47ef4b3  (/out/coins_view+0x1dee4b3)
    #10 0x55b3a47ef0cd  (/out/coins_view+0x1dee0cd)
    #11 0x55b3a2eef613  (/out/coins_view+0x4ee613)
    #12 0x55b3a2edaa92  (/out/coins_view+0x4d9a92)
    #13 0x55b3a2ee0767  (/out/coins_view+0x4df767)
    #14 0x55b3a2f0a3d2  (/out/coins_view+0x5093d2)
    #15 0x7f1fc1d5183f  (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #16 0x55b3a2eb5e18  (/out/coins_view+0x4b4e18)

  Uninitialized value was created by an allocation of 'tx_fee_out' in the stack frame of function '_ZZ22coins_view_fuzz_target4SpanIKhEENK4$_12clEv'
    #0 0x55b3a3128b00  (/out/coins_view+0x727b00)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/out/coins_view+0x7296fc) 
Unique heap origins: 146262
Stack depot allocated bytes: 26519192
Unique origin histories: 17561
History depot allocated bytes: 421464
Exiting




# python infra/helper.py reproduce -e MSAN_SYMBOLIZER_PATH=/usr/local/bin/llvm-symbolizer $PROJECT_NAME coins_view ./6e13b65b-6648-47dd-b1ff-b6f005ecf8dc\?testcase_id\=6289089386119168 
Running: docker run --rm --privileged -i -e MSAN_SYMBOLIZER_PATH=/usr/local/bin/llvm-symbolizer -v /root/oss-fuzz/build/out/bitcoin-core:/out -v '/root/oss-fuzz/6e13b65b-6648-47dd-b1ff-b6f005ecf8dc?testcase_id=6289089386119168:/testcase' -t gcr.io/oss-fuzz-base/base-runner reproduce coins_view -runs=100
+ FUZZER=coins_view
+ shift
+ '[' '!' -v TESTCASE ']'
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export RUN_FUZZER_MODE=interactive
+ RUN_FUZZER_MODE=interactive
+ export FUZZING_ENGINE=libfuzzer
+ FUZZING_ENGINE=libfuzzer
+ export SKIP_SEED_CORPUS=1
+ SKIP_SEED_CORPUS=1
+ run_fuzzer coins_view -runs=100 /testcase
/out/coins_view -rss_limit_mb=2560 -timeout=25 -runs=100 /testcase < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 767452933
INFO: Loaded 1 modules   (176398 inline 8-bit counters): 176398 [0x562474ec2f38, 0x562474eee046), 
INFO: Loaded 1 PC tables (176398 PCs): 176398 [0x562474eee048,0x56247519f128), 
/out/coins_view: Running 1 inputs 100 time(s) each.
Running: /testcase
==13==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5624722346fc in MoneyRange(long const&) /src/bitcoin-core/src/./amount.h:26:69
    #1 0x562472232ecd in coins_view_fuzz_target(Span<unsigned char const>)::$_12::operator()() const /src/bitcoin-core/src/test/fuzz/coins_view.cpp:240:17
    #2 0x5624722163fb in void CallOneOf<coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16>(FuzzedDataProvider&, coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16) /src/bitcoin-core/src/./test/fuzz/util.h:47:34
    #3 0x562472214b84 in coins_view_fuzz_target(Span<unsigned char const>) /src/bitcoin-core/src/test/fuzz/coins_view.cpp:192:9
    #4 0x5624720cf146 in decltype(std::__1::forward<void (*&)(Span<unsigned char const>)>(fp)(std::__1::forward<Span<unsigned char const> >(fp0))) std::__1::__invoke<void (*&)(Span<unsigned char const>), Span<unsigned char const> >(void (*&)(Span<unsigned char const>), Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/type_traits:3679:1
    #5 0x5624720cef62 in void std::__1::__invoke_void_return_wrapper<void>::__call<void (*&)(Span<unsigned char const>), Span<unsigned char const> >(void (*&)(Span<unsigned char const>), Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/__functional_base:348:9
    #6 0x5624720cedf2 in std::__1::__function::__alloc_func<void (*)(Span<unsigned char const>), std::__1::allocator<void (*)(Span<unsigned char const>)>, void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/functional:1558:16
    #7 0x5624720cad04 in std::__1::__function::__func<void (*)(Span<unsigned char const>), std::__1::allocator<void (*)(Span<unsigned char const>)>, void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) /usr/local/bin/../include/c++/v1/functional:1732:12
    #8 0x5624739045a9 in std::__1::__function::__value_func<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>&&) const /usr/local/bin/../include/c++/v1/functional:1885:16
    #9 0x5624738f94b3 in std::__1::function<void (Span<unsigned char const>)>::operator()(Span<unsigned char const>) const /usr/local/bin/../include/c++/v1/functional:2560:12
    #10 0x5624738f90cd in LLVMFuzzerTestOneInput /src/bitcoin-core/src/test/fuzz/fuzz.cpp:82:5
    #11 0x562471ff9613 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #12 0x562471fe4a92 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
    #13 0x562471fea767 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
    #14 0x5624720143d2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #15 0x7f400f8fe83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #16 0x562471fbfe18 in _start (/out/coins_view+0x4b4e18)

DEDUP_TOKEN: MoneyRange(long const&)--coins_view_fuzz_target(Span<unsigned char const>)::$_12::operator()() const--void CallOneOf<coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16>(FuzzedDataProvider&, coins_view_fuzz_target(Span<unsigned char const>)::$_10, coins_view_fuzz_target(Span<unsigned char const>)::$_11, coins_view_fuzz_target(Span<unsigned char const>)::$_12, coins_view_fuzz_target(Span<unsigned char const>)::$_13, coins_view_fuzz_target(Span<unsigned char const>)::$_14, coins_view_fuzz_target(Span<unsigned char const>)::$_15, coins_view_fuzz_target(Span<unsigned char const>)::$_16)
  Uninitialized value was created by an allocation of 'tx_fee_out' in the stack frame of function '_ZZ22coins_view_fuzz_target4SpanIKhEENK4$_12clEv'
    #0 0x562472232b00 in coins_view_fuzz_target(Span<unsigned char const>)::$_12::operator()() const /src/bitcoin-core/src/test/fuzz/coins_view.cpp:225

DEDUP_TOKEN: coins_view_fuzz_target(Span<unsigned char const>)::$_12::operator()() const
SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/bitcoin-core/src/./amount.h:26:69 in MoneyRange(long const&)
Unique heap origins: 146261
Stack depot allocated bytes: 26519072
Unique origin histories: 17560
History depot allocated bytes: 421440
Exiting
```

</details>
