### ISSUE TITLE
Grouping of Rust bugs can place distinct failures into the same group

### ISSUE THREAD

**Issue by alexcrichton** [google/oss-fuzz#5516]
I looked into wasmtime's fuzz bugs yesterday and was surprised to learn that [one of the reported issues](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=31740#c2) had a [very large group of bugs behind it](https://oss-fuzz.com/testcases?q=group%3A5922050055208960). It seems like oss-fuzz tries to deduplicate separate crashes into one bug if possible (yay!) but it also seems like the current logic isn't handling Rust crashes well by lumping too many distinct issues into one bucket.

For example within that "group" these bugs were all actually distinct issues in wasmtime:

* https://oss-fuzz.com/testcase-detail/5139475819790336
* https://oss-fuzz.com/testcase-detail/6633198940454912
* https://oss-fuzz.com/testcase-detail/5647627896094720
* https://oss-fuzz.com/testcase-detail/5735163356119040
* https://oss-fuzz.com/testcase-detail/5895265744715776
* https://oss-fuzz.com/testcase-detail/6300407300227072
* https://oss-fuzz.com/testcase-detail/6202971571486720
* https://oss-fuzz.com/testcase-detail/5831344342040576

Is it possible the the heuristic used for C++ or otherwise could be tweaked for Rust projects? I'm not actually sure how the automatic grouping works, but I figured I'd raise this! I originally ignored our fuzz bugs for awhile since the reported issue seemed benign, but upon looking into things I saw the rabbit hole went much deeper :)

**Comment by inferno-chromium** [comment]
ah we need to exclude these frames to avoid incorrect grouping.

std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bfNUMBER
core::panicking::panic_fmt::h5322a082d19786c3

can fix early next week.

**Comment by alexcrichton** [comment]
Ah ok! FWIW with one of the faulting stack traces:

```

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: resource limit exceeded: instance count too high at 101', crates/fuzzing/src/oracles/dummy.rs:80:40
--
  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
  | ==3606== ERROR: libFuzzer: deadly signal
  | #0 0x55f8fe3072d1 in __sanitizer_print_stack_trace /rustc/llvm/src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:86:3
  | #1 0x55f902380768 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
  | #2 0x55f902363de3 in fuzzer::Fuzzer::CrashCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:233:3
  | #3 0x7f4a39dd038f in libpthread.so.0
  | #4 0x7f4a3951d437 in raise /build/glibc-e6zv40/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
  | #5 0x7f4a3951f039 in abort /build/glibc-e6zv40/glibc-2.23/stdlib/abort.c:89
  | #6 0x55f90241da79 in std::sys::unix::abort_internal::h411dc3861a5cb281 /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/std/src/sys/unix/mod.rs:237:14
  | #7 0x55f8fe27fa08 in std::process::abort::hd257d0bc0ddb140c /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/std/src/process.rs:1814:5
  | #8 0x55f9023b62ee in libfuzzer_sys::initialize::_$u7b$$u7b$closure$u7d$$u7d$::h8a22640c22e97ee8 /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.0/src/lib.rs:51:9
  | #9 0x55f90240da7f in std::panicking::rust_panic_with_hook::h70db735e3a6e70cb /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/std/src/panicking.rs:595:17
  | #10 0x55f90240d5f6 in std::panicking::begin_panic_handler::_$u7b$$u7b$closure$u7d$$u7d$::h777c71c8e5a7e25c /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/std/src/panicking.rs:497:13
  | #11 0x55f902409a9b in std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554 /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/std/src/sys_common/backtrace.rs:141:18
  | #12 0x55f90240d558 in rust_begin_unwind /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/std/src/panicking.rs:493:5
  | #13 0x55f8fe281b80 in core::panicking::panic_fmt::h5322a082d19786c3 /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/core/src/panicking.rs:92:14
  | #14 0x55f8fe281a72 in core::result::unwrap_failed::hbee7d9f7831678f0 /rustc/1705a7d64b833d1c4b69958b0627bd054e6d764b/library/core/src/option.rs:1329:5
  | #15 0x55f8fe5063f8 in core::result::Result$LT$T$C$E$GT$::unwrap::h8bb8aa497881e415 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
  | #16 0x55f8fe5063f8 in wasmtime_fuzzing::oracles::dummy::dummy_instance::h9ea171d80e24ac3d wasmtime/crates/fuzzing/src/oracles/dummy.rs:80:5
  | #17 0x55f8fe504273 in wasmtime_fuzzing::oracles::dummy::dummy_imports::_$u7b$$u7b$closure$u7d$$u7d$::h6fef77dc4c0cb074 wasmtime/crates/fuzzing/src/oracles/dummy.rs:18:34
  | #18 0x55f8fe3538fd in core::iter::adapters::map::map_fold::_$u7b$$u7b$closure$u7d$$u7d$::hb41e0297ba81bd1b /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:81:28
  | #19 0x55f8fe3538fd in core::iter::traits::iterator::Iterator::fold::h39f4c802aa4fece2 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2123:21
  | #20 0x55f8fe3538fd in _$LT$core..iter..adapters..map..Map$LT$I$C$F$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::fold::h6a6746270d137e1f /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:121:9
  | #21 0x55f8fe376055 in core::iter::traits::iterator::Iterator::for_each::h6bc7f4b15530702f /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:775:9
  | #22 0x55f8fe376055 in _$LT$alloc..vec..Vec$LT$T$C$A$GT$$u20$as$u20$alloc..vec..spec_extend..SpecExtend$LT$T$C$I$GT$$GT$::spec_extend::hfdfa849b00966092 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_extend.rs:42:17
  | #23 0x55f8fe376055 in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$alloc..vec..spec_from_iter_nested..SpecFromIterNested$LT$T$C$I$GT$$GT$::from_iter::he1396017e224ce90 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/spec_from_iter_nested.rs:53:9
  | #24 0x55f8fe51f6ed in alloc::vec::source_iter_marker::_$LT$impl$u20$alloc..vec..spec_from_iter..SpecFromIter$LT$T$C$I$GT$$u20$for$u20$alloc..vec..Vec$LT$T$GT$$GT$::from_iter::hc84a96044a6ee1d2 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/source_iter_marker.rs:41:20
  | #25 0x55f8fe51f6ed in _$LT$alloc..vec..Vec$LT$T$GT$$u20$as$u20$core..iter..traits..collect..FromIterator$LT$T$GT$$GT$::from_iter::hfa8a338afd3c764b /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2401:9
  | #26 0x55f8fe51f6ed in core::iter::traits::iterator::Iterator::collect::h77abea8a9aedf2ad /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1764:9
  | #27 0x55f8fe51f6ed in wasmtime_fuzzing::oracles::dummy::dummy_imports::hf094b1195412fd53 wasmtime/crates/fuzzing/src/oracles/dummy.rs:11:5
  | #28 0x55f8fe51f6ed in wasmtime_fuzzing::oracles::make_api_calls::hf8afb861539e765d wasmtime/crates/fuzzing/src/oracles.rs:357:31
  | #29 0x55f8fe34bfdb in rust_fuzzer_test_input wasmtime/fuzz/fuzz_targets/api_calls.rs:7:5
  | #30 0x55f9023b6330 in __rust_try
  | #31 0x55f9023b5f8f in std::panicking::try::h88270102441d9383 /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  | #32 0x55f9023b5f8f in std::panic::catch_unwind::h3f9fd73d7e24a8da /rust/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  | #33 0x55f9023b5f8f in LLVMFuzzerTestOneInput /rust/registry/src/github.com-1ecc6299db9ec823/libfuzzer-sys-0.4.0/src/lib.rs:25:22
  | #34 0x55f902365583 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
  | #35 0x55f90234f3e2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
  | #36 0x55f90235522a in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
  | #37 0x55f902380f42 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #38 0x7f4a3950883f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/libc-start.c:291
  | #39 0x55f8fe282ef8 in _start
```

the top 15 frames can all be ignored since they're common in Rust panic traces with assertion failures and such.

**Comment by inferno-chromium** [comment]
you will probably see some bugs get closely and then reopened with right crash state.
