### ISSUE TITLE
Authorization for getting the detailed report from oss-fuzz

### ISSUE THREAD

**Issue by aqjune** [google/oss-fuzz#5575]
Hello all,

I got a news that [my patch](https://reviews.llvm.org/D93990) in LLVM is causing a regression.

To see the detailed report (https://oss-fuzz.com/testcase?key=6326361553764352), I'd like to gain access permission to it.
Can I get permission for this?
My email is aqjune@gmail.com .

Thanks!

**Comment by inferno-chromium** [comment]
llvm bugs and reproducers are all public, so you can download testcase from https://oss-fuzz.com/download?testcase_id=6326361553764352 [in c#0] link. 

to reproduce, see steps in https://google.github.io/oss-fuzz/advanced-topics/reproducing/, fuzz target is llvm-opt-fuzzer

```
/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_llvm_57c8a5774aad76f8b036530878be040aa4fb2c2c/revisions/llvm-opt-fuzzer: Injected args: -mtriple=x86_64 -passes=instcombine
--
  | INFO: found LLVMFuzzerCustomMutator (0x8e2830). Disabling -len_control by default.
  | INFO: Running with entropic power schedule (0xFF, 100).
  | INFO: Seed: 479322060
  | INFO: Loaded 1 modules   (1802569 inline 8-bit counters): 1802569 [0x10850cb0, 0x10a08df9),
  | INFO: Loaded 1 PC tables (1802569 PCs): 1802569 [0x10a08e00,0x1258a290),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_llvm_57c8a5774aad76f8b036530878be040aa4fb2c2c/revisions/llvm-opt-fuzzer--x86_64-instcombine: Running 1 inputs 100 time(s) each.
  | Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-2f6e95e933c11e38d719037d6b1ed5aa36cdb67b
  | llvm-opt-fuzzer--x86_64-instcombine: /src/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:5278: static llvm::Optional<std::pair<CmpInst::Predicate, Constant *>> llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(CmpInst::Predicate, llvm::Constant *): Assertion `SafeReplacementConstant && "Replacement constant not set"' failed.
  | AddressSanitizer:DEADLYSIGNAL
  | =================================================================
  | ==5844==ERROR: AddressSanitizer: ABRT on unknown address 0x0539000016d4 (pc 0x7f2048af1438 bp 0x00000daead40 sp 0x7ffffe2c8188 T0)
  | SCARINESS: 10 (signal)
  | #0 0x7f2048af1438 in raise /build/glibc-e6zv40/glibc-2.23/sysdeps/unix/sysv/linux/raise.c:54
  | #1 0x7f2048af3039 in abort /build/glibc-e6zv40/glibc-2.23/stdlib/abort.c:89
  | #2 0x7f2048ae9be6 in __assert_fail_base /build/glibc-e6zv40/glibc-2.23/assert/assert.c:92
  | #3 0x7f2048ae9c91 in __assert_fail /build/glibc-e6zv40/glibc-2.23/assert/assert.c:101
  | #4 0x77248f1 in llvm::InstCombiner::getFlippedStrictnessPredicateAndConstant(llvm::CmpInst::Predicate, llvm::Constant*) llvm-project/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:5278:5
  | #5 0x774da3e in canonicalizeCmpWithConstant llvm-project/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:5307:7
  | #6 0x774da3e in llvm::InstCombinerImpl::visitICmpInst(llvm::ICmpInst&) llvm-project/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp:5575:26
  | #7 0x75639e4 in llvm::InstCombinerImpl::run() llvm-project/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:3733:31
  | #8 0x756f730 in combineInstructionsOverFunction(llvm::Function&, llvm::InstCombineWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::ProfileSummaryInfo*, unsigned int, llvm::LoopInfo*) llvm-project/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:4023:13
  | #9 0x7569a9f in llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) llvm-project/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp:4054:8
  | #10 0x95a7b9c in llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:85:17
  | #11 0x6c8f5df in llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) llvm-project/llvm/include/llvm/IR/PassManager.h:517:21
  | #12 0xffa5ac in llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function> >, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function> >::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:85:17
  | #13 0x6ca2c11 in llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) llvm-project/llvm/lib/IR/PassManager.cpp:117:22
  | #14 0xff9b8c in llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:85:17
  | #15 0x6c8a997 in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) llvm-project/llvm/include/llvm/IR/PassManager.h:517:21
  | #16 0x8e4bbe in LLVMFuzzerTestOneInput llvm-project/llvm/tools/llvm-opt-fuzzer/llvm-opt-fuzzer.cpp:162:7
  | #17 0x7e3723 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
  | #18 0x7cd582 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
  | #19 0x7d33ca in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:856:9
  | #20 0x7ff102 in main llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #21 0x7f2048adc83f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/libc-start.c:291
  | #22 0x7a8218 in _start
  |  
  | AddressSanitizer can not provide additional info.
  | SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35438)
  | ==5844==ABORTING
````

**Comment by aqjune** [comment]
Oh, I was missing the link. Thank you so much! :)
