### ISSUE TITLE
[CIFuzz] Timeout and python exceptions

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#5621]
From https://github.com/OISF/suricata/pull/6055/checks?check_run_id=2335789563
```
2021-04-13 18:01:07,341 - root - WARNING - Command timed out: docker run --rm --privileged --cidfile /tmp/tmp90jabo8s/cidfile --volumes-from e388543721fa -e OUT=/github/workspace/out -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e CIFUZZ=True -e RUN_FUZZER_MODE=interactive gcr.io/oss-fuzz-base/base-runner bash -c run_fuzzer fuzz_siginit -seed=1337 -len_control=0 -max_total_time=18 /github/workspace/out/cifuzz-corpus/fuzz_siginit
24255b8a2e7938d1090e95363e5d5b0194cae55360eef2af11e1a8a228c43ea0
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/docker.py", line 92, in run_container_command
    stdout, stderr = process.communicate(timeout=timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['docker', 'run', '--rm', '--privileged', '--cidfile', '/tmp/tmp90jabo8s/cidfile', '--volumes-from', 'e388543721fa', '-e', 'OUT=/github/workspace/out', '-e', 'FUZZING_ENGINE=libfuzzer', '-e', 'SANITIZER=address', '-e', 'CIFUZZ=True', '-e', 'RUN_FUZZER_MODE=interactive', 'gcr.io/oss-fuzz-base/base-runner', 'bash', '-c', 'run_fuzzer fuzz_siginit -seed=1337 -len_control=0 -max_total_time=18 /github/workspace/out/cifuzz-corpus/fuzz_siginit']' timed out after 28 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 97, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 83, in main
    result = run_fuzzers.run_fuzzers(config)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 205, in run_fuzzers
    if not fuzz_target_runner.run_fuzz_targets():
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 136, in run_fuzz_targets
    result = self.run_fuzz_target(target)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 94, in run_fuzz_target
    result = fuzz_target_obj.fuzz()
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 120, in fuzz
    timeout=self.duration + BUFFER_TIME)
  File "/opt/oss-fuzz/infra/cifuzz/docker.py", line 96, in run_container_command
    process, cid_file_path)
  File "/opt/oss-fuzz/infra/cifuzz/docker.py", line 73, in _handle_timed_out_container_process
    return process.communicate(timeout=1)
  File "/usr/lib/python3.5/subprocess.py", line 1072, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1716, in _communicate
    self._check_timeout(endtime, orig_timeout)
  File "/usr/lib/python3.5/subprocess.py", line 1098, in _check_timeout
    raise TimeoutExpired(self.args, orig_timeout)
subprocess.TimeoutExpired: Command '['docker', 'run', '--rm', '--privileged', '--cidfile', '/tmp/tmp90jabo8s/cidfile', '--volumes-from', 'e388543721fa', '-e', 'OUT=/github/workspace/out', '-e', 'FUZZING_ENGINE=libfuzzer', '-e', 'SANITIZER=address', '-e', 'CIFUZZ=True', '-e', 'RUN_FUZZER_MODE=interactive', 'gcr.io/oss-fuzz-base/base-runner', 'bash', '-c', 'run_fuzzer fuzz_siginit -seed=1337 -len_control=0 -max_total_time=18 /github/workspace/out/cifuzz-corpus/fuzz_siginit']' timed out after 1 seconds
```

Did CIFuzz find a timeout ? bug encountered an exception while trying to report it ?

**Comment by catenacyber** [comment]
Thanks Johnathan, looks fixed indeed
