### ISSUE TITLE
New project libecc doesn't show up at oss-fuzz.com

### ISSUE THREAD

**Issue by guidovranken** [google/oss-fuzz#5629]
libecc was recently merged: https://github.com/google/oss-fuzz/pull/5613

According to https://oss-fuzz-build-logs.storage.googleapis.com/index.html it's building fine.

But I don't see it at https://oss-fuzz.com/

**Comment by inferno-chromium** [comment]
we have a cron exception we have to look into
```
<HttpError 400 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/***:setIamPolicy?alt=json returned "The number of members in the policy (1,502) is larger than the maximum allowed size 1,500."> Traceback (most recent call last): File "/srv/handlers/base_handler.py", line 271, in dispatch_request return super(Handler, self).dispatch_request(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/views.py", line 163, in dispatch_request return meth(*args, **kwargs) File "/srv/libs/handler.py", line 100, in wrapper result = func(self) File "/srv/handlers/cron/project_setup.py", line 995, in get result = config.set_up(projects) File "/srv/handlers/cron/project_setup.py", line 888, in set_up self._create_service_accounts_and_buckets(project, info)) File "/srv/handlers/cron/project_setup.py", line 625, in _create_service_accounts_and_buckets service_accounts.set_service_account_roles(service_account) File "/srv/handlers/cron/service_accounts.py", line 152, in set_service_account_roles request.execute() File "third_party/googleapiclient/_helpers.py", line 134, in positional_wrapper return wrapped(*args, **kwargs) File "third_party/googleapiclient/http.py", line 907, in execute raise HttpError(resp, content, uri=self.uri) googleapiclient.errors.HttpError: <HttpError 400 when requesting https://cloudresourcemanager.googleapis.com/v1/projects/***:setIamPolicy?alt=json returned "The number of members in the policy (1,502) is larger than the maximum allowed size 1,500.">
```

**Comment by inferno-chromium** [comment]
@oliverchang - thoughts on mitigating this?

**Comment by inferno-chromium** [comment]
right now, 470 members in each of [which makes up majority of this 1500 limit]

```
  policy_changed |= _add_service_account_role(policy, 'roles/logging.logWriter',
                                              service_account['email'])
  policy_changed |= _add_service_account_role(
      policy, 'roles/prodx.metricPublisher', service_account['email'])
  policy_changed |= _add_service_account_role(
      policy, 'roles/monitoring.metricWriter', service_account['email'])
```

i think we can get rid of 'roles/prodx.metricPublisher' [monarch, unused?]

**Comment by inferno-chromium** [comment]
i will wait on @oliverchang to confirm this and then can make the change.

**Comment by oliverchang** [comment]
Yes I think we can remove the prox.metricPublisher. But this will come back again as we get more projects. In the future we may need to create groups instead to reduce the number of bindings.

**Comment by guidovranken** [comment]
I now have access to the libecc project at oss-fuzz.com. Feel free to close this issue.

**Comment by oliverchang** [comment]
I've also removed the unused binding so that should buy us quite a bit of time.
