### ISSUE TITLE
Cloud function timeout limit is 540 sec is not scalable.

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#5968]
Hi,

looking at https://oss-fuzz-build-logs.storage.googleapis.com/index.html , no project was built today and only six were built yesterday. Do I need to worry?

Cheers,
Robert

**Comment by inferno-chromium** [comment]
Deploying now, to see if it fixes.

**Comment by inferno-chromium** [comment]
Builds are working fine, just this status page was ooming out, default instance memory was 256mb.

**Comment by inferno-chromium** [comment]
Now hitting

```
Traceback (most recent call last): File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise raise value File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/layers/google.python.functions-framework/functions-framework/lib/python3.8/site-packages/functions_framework/__init__.py", line 102, in view_func function(data, context) File "/workspace/main.py", line 47, in builds_status update_build_status.update_status(event, context) File "/workspace/update_build_status.py", line 270, in update_status update_build_status(tag, status_filename) File "/workspace/update_build_status.py", line 185, in update_build_status project = future.result() File "/opt/python3.8/lib/python3.8/concurrent/futures/_base.py", line 437, in result return self.__get_result() File "/opt/python3.8/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result raise self._exception File "/opt/python3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/workspace/update_build_status.py", line 173, in process_project project = get_build_history(project_build.build_ids) File "/workspace/update_build_status.py", line 137, in get_build_history project_build = get_build(cloudbuild, image_project, build_id) File "/workspace/update_build_status.py", line 93, in get_build return cloudbuild.projects().builds().get(projectId=image_project, File "/layers/google.python.pip/pip/lib/python3.8/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper return wrapped(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/googleapiclient/http.py", line 907, in execute raise HttpError(resp, content, uri=self.uri) googleapiclient.errors.HttpError: <HttpError 429 when requesting https://cloudbuild.googleapis.com/v1/projects/oss-fuzz/builds/d1e0a0f1-adbb-426e-8497-d4f762ec6f63?alt=json returned "Quota exceeded for quota metric 'Build and Operation Get requests' and limit 'Build and Operation Get requests per minute' of service 'cloudbuild.googleapis.com' for consumer 'project_number:608308004811'.". Details: "[{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'RATE_LIMIT_EXCEEDED', 'domain': 'googleapis.com', 'metadata': {'quota_metric': 'cloudbuild.googleapis.com/get_requests', 'consumer': 'projects/608308004811', 'service': 'cloudbuild.googleapis.com', 'quota_limit': 'GetRequestsPerMinutePerProject'}}]">
```

**Comment by inferno-chromium** [comment]
Trying https://github.com/google/oss-fuzz/commit/13a076b275217d3ced1d205ada2288c67eb37663

**Comment by inferno-chromium** [comment]
Trying https://github.com/google/oss-fuzz/commit/db33cc2c38f4ba2459fc9ceec459b9192d5b8755

**Comment by inferno-chromium** [comment]
A cloud bug is filed to increase GetRequestsPerMinutePerProject quota (as oss-fuzz scale, we need higher quota for this).

till then this workaround https://github.com/google/oss-fuzz/commit/53eff028799911477f216eb94d330eacfb3e071c worked
only look back last three days of logs
5 executors
2 sec delay.
bad part is we use cloud function which has 540 sec timeout, we should sometime move to cloud run.

this bug is fixed now, but lets still track the issue.

**Comment by inferno-chromium** [comment]
https://oss-fuzz-build-logs.storage.googleapis.com/index.html is now updated.

**Comment by oliverchang** [comment]
+1 to moving this to cloud run. This will just require some work to set up some Dockerfiles + some boilerplate http server code.

**Comment by rlohning** [comment]
> https://oss-fuzz-build-logs.storage.googleapis.com/index.html is now updated.

It was, but now the newest builds I see are from June 29th, nearly a week ago.

**Comment by inferno-chromium** [comment]
> > https://oss-fuzz-build-logs.storage.googleapis.com/index.html is now updated.
> 
> It was, but now the newest builds I see are from June 29th, nearly a week ago.

There was an issue with quota not fixed properly (filed another cloud bug), so bringing back fix in https://github.com/google/oss-fuzz/pull/5997
