### ISSUE TITLE
AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2 seems to cause fuzz targets to crash as soon as they start

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#6037]
I haven't figured out what's going on yet so I'll just leave a couple of links to build failures (where fuzz targets were compiled with `AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2`):

`selinux`: https://oss-fuzz-build-logs.storage.googleapis.com/log-e70a0b72-e756-4cae-8cea-fcbf192572a8.txt
`systemd`: https://oss-fuzz-build-logs.storage.googleapis.com/log-cc176a50-d8f8-4c4c-b1bf-db3a46061d57.txt

```
[+] All test cases processed.

[-] PROGRAM ABORT : We need at least one valid input seed that does not crash!
         Location : main(), src/afl-fuzz.c:1881
```

Without `AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2` both `systemd` and `selinux` seem to pass the "bad build" check.

I built `selinux` and `systemd` with `AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2` to take a look at backtraces and it seems `AFL_LLVM_INSTRUMENT=CLASSIC,CTX-2` somehow triggers dynamic-stack-buffer-overflows like:
```
# /out/fuzz-journal-remote CORPUS/input
Reading 6 bytes from CORPUS/input
=================================================================
==20==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffd8e4088e0 at pc 0x000000497c4c bp 0x7ffd8e4087d0 sp 0x7ffd8e407f98
WRITE of size 358 at 0x7ffd8e4088e0 thread T0
    #0 0x497c4b in __asan_memset /src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3
    #1 0x7f6b94a60a9f in journal_file_open /work/build/../../src/systemd/src/libsystemd/sd-journal/journal-file.c:3428:14
    #2 0x7f6b94ab249a in add_any_file /work/build/../../src/systemd/src/libsystemd/sd-journal/sd-journal.c:1340:13
    #3 0x7f6b94ab140e in sd_journal_open_files /work/build/../../src/systemd/src/libsystemd/sd-journal/sd-journal.c:2049:21
    #4 0x4ccd73 in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/journal-remote/fuzz-journal-remote.c:67:13
    #5 0x4d8ac0 in ExecuteFilesOnyByOne /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:191:7
    #6 0x4d8890 in main /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c
    #7 0x7f6b9313883f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #8 0x41da48 in _start (/out/fuzz-journal-remote+0x41da48)

Address 0x7ffd8e4088e0 is located in stack of thread T0 at offset 256 in frame
    #0 0x7f6b94a6035f in journal_file_open /work/build/../../src/systemd/src/libsystemd/sd-journal/journal-file.c:3408

  This frame has 9 object(s):
    [32, 40) 'h' (line 3412)
    [64, 68) '.compoundliteral.sroa.0'
    [80, 92) '.compoundliteral.sroa.3'
    [112, 116) '.compoundliteral.sroa.3451'
    [128, 132) '.compoundliteral.sroa.4'
    [144, 146) '.compoundliteral.sroa.5'
    [160, 518) '.compoundliteral.sroa.7' <== Memory access at offset 256 partially overflows this variable
    [592, 600) '.compoundliteral.sroa.7456' <== Memory access at offset 256 partially underflows this variable
    [624, 640) '.compoundliteral183'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow /src/llvm-project/compiler-rt/lib/asan/asan_interceptors_memintrinsics.cpp:26:3 in __asan_memset
Shadow bytes around the buggy address:
  0x100031c790c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100031c790d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100031c790e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100031c790f0: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
  0x100031c79100: 00 f2 f2 f2 04 f2 00 04 f2 f2 04 f2 04 f2 02 f2
=>0x100031c79110: 00 00 00 00 00 00 00 00 00 00 00 00[cb]cb cb cb
  0x100031c79120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100031c79130: ca ca ca ca f8 f8 f8 f8 f8 f8 cb cb 06 f2 f2 f2
  0x100031c79140: f2 f2 f2 f2 f2 f2 00 f2 f2 f2 00 00 f3 f3 f3 f3
  0x100031c79150: ca ca ca ca f8 f8 f8 f8 f8 f8 cb cb cb cb cb cb
  0x100031c79160: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==20==ABORTING
```
```
# /out/secilc-fuzzer /tmp/secilc-fuzzer_corpus/input
Reading 6 bytes from /tmp/secilc-fuzzer_corpus/input
Symbol not inside parenthesis at line 1 of fuzz
=================================================================
==56==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffda66dffc0 at pc 0x000000610a10 bp 0x7ffda66dff70 sp 0x7ffda66dff68
WRITE of size 8 at 0x7ffda66dffc0 thread T0
    #0 0x610a0f in cil_tree_subtree_destroy /src/selinux/libsepol/src/../cil/src/cil_tree.c
    #1 0x61085b in cil_tree_destroy /src/selinux/libsepol/src/../cil/src/cil_tree.c:172:2
    #2 0x4f006c in cil_db_destroy /src/selinux/libsepol/src/../cil/src/cil.c:454:2
    #3 0x4cbe30 in LLVMFuzzerTestOneInput /src/secilc-fuzzer.c:83:2
    #4 0x4cb950 in ExecuteFilesOnyByOne /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:191:7
    #5 0x4cb720 in main /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c
    #6 0x7f7e477eb83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #7 0x41cbc8 in _start (/out/secilc-fuzzer+0x41cbc8)

Address 0x7ffda66dffc0 is located in stack of thread T0
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow /src/selinux/libsepol/src/../cil/src/cil_tree.c in cil_tree_subtree_destroy
Shadow bytes around the buggy address:
  0x100034cd3fa0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd3fb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd3fc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd3fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd3fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x100034cd3ff0: 00 00 00 00 ca ca ca ca[ca]cb cb cb cb cb cb cb
  0x100034cd4000: cb cb cb cb 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd4010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd4020: f1 f1 f1 f1 00 f2 f2 f2 00 f2 f2 f2 00 f3 f3 f3
  0x100034cd4030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100034cd4040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==56==ABORTING
```
```
Reading 6 bytes from CORPUS/input
=================================================================
==19==ERROR: AddressSanitizer: dynamic-stack-buffer-overflow on address 0x7ffcbca607a0 at pc 0x7fd21e2a42af bp 0x7ffcbca60750 sp 0x7ffcbca60748
WRITE of size 8 at 0x7ffcbca607a0 thread T0
    #0 0x7fd21e2a42ae in path_startswith_full /work/build/../../src/systemd/src/basic/path-util.c
    #1 0x7fd21e1af377 in path_startswith /work/build/../../src/systemd/src/basic/path-util.h:62:16
    #2 0x7fd21e1afbcc in cg_shift_path /work/build/../../src/systemd/src/basic/cgroup-util.c:1035:13
    #3 0x7fd21e1b0036 in cg_pid_get_path_shifted /work/build/../../src/systemd/src/basic/cgroup-util.c:1056:13
    #4 0x531922 in client_context_read_cgroup /work/build/../../src/systemd/src/journal/journald-context.c:278:13
    #5 0x52d471 in client_context_really_refresh /work/build/../../src/systemd/src/journal/journald-context.c:525:16
    #6 0x52f4fb in client_context_get_internal /work/build/../../src/systemd/src/journal/journald-context.c:705:9
    #7 0x52ecb7 in client_context_get /work/build/../../src/systemd/src/journal/journald-context.c:719:16
    #8 0x4d15fa in server_process_native_message /work/build/../../src/systemd/src/journal/journald-native.c:310:21
    #9 0x4d4e93 in server_process_native_file /work/build/../../src/systemd/src/journal/journald-native.c:400:17
    #10 0x4d079f in LLVMFuzzerTestOneInput /work/build/../../src/systemd/src/journal/fuzz-journald-native-fd.c:36:9
    #11 0x53fc10 in ExecuteFilesOnyByOne /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:191:7
    #12 0x53f9e0 in main /src/aflplusplus/utils/aflpp_driver/aflpp_driver.c
    #13 0x7fd21cca983f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #14 0x421a48 in _start (/out/fuzz-journald-native-fd+0x421a48)

Address 0x7ffcbca607a0 is located in stack of thread T0 at offset 64 in frame
    #0 0x7fd21e2a3a8f in path_startswith_full /work/build/../../src/systemd/src/basic/path-util.c:426

  This frame has 4 object(s):
    [32, 40) 'path.addr'
    [64, 72) 'prefix.addr' <== Memory access at offset 64 is inside this variable
    [96, 104) 'p' (line 444)
    [128, 136) 'q' (line 444)
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: dynamic-stack-buffer-overflow /work/build/../../src/systemd/src/basic/path-util.c in path_startswith_full
Shadow bytes around the buggy address:
  0x1000179440a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000179440b0: 00 00 00 00 ca ca ca ca 00 00 cb cb cb cb cb cb
  0x1000179440c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000179440d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1000179440e0: 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1 f1 f1
=>0x1000179440f0: 00 f2 f2 f2[ca]f2 f2 f2 f8 f2 f2 f2 f8 f3 f3 f3
  0x100017944100: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100017944110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100017944120: 00 00 00 00 f1 f1 f1 f1 00 f3 f3 f3 00 00 00 00
  0x100017944130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100017944140: 00 00 00 00 f1 f1 f1 f1 00 f2 f2 f2 00 f3 f3 f3
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==19==ABORTING
```
cc @vanhauser-thc

**Comment by vanhauser-thc** [comment]
I can reproduce this when CTX + CMPLOG are combined. on its own they both work fine in both targets.
I fear that somehow asan gets bugged due to the instrumentation. because it reports for selinux a buffer overrun on the address that simply does "push rbp" in the function prologue. and for systemd it reports stack-use-after-scope in a function where there is no local variable (neither in the source code nor in the machine code).

I will push a workaround that does not allow CTX together with CMPLOG until I have figured this out ... currently I am cluesless what could be going wrong.

**Comment by vanhauser-thc** [comment]
#6039

**Comment by evverx** [comment]
@vanhauser-thc thanks!

@inferno-chromium @jonathanmetzman I'm not sure if it's possible but it would probably help if you could take a look at the build history of the selinux project to see when it started happening to figure out what changed around that time. Given that I had never seen backtraces like that my guess would be that it regressed in June or July.

**Comment by vanhauser-thc** [comment]
Workaround is merged, @andreafioraldi  is investigating and it looks like it is a bug in llvm

**Comment by evverx** [comment]
I think this issue can be closed. If it resurfaces it can always be reopened.
