### ISSUE TITLE
Use libc++'s debug mode in ubsan build

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#610]
libc++ has a debug mode that reports some bugs better than asan does;
in some cases it may even find bugs not reported by asan at all. 
http://libcxx.llvm.org/docs/DesignDocs/DebugMode.html
To enable this mode we need to add `-D_LIBCPP_DEBUG=1` to `CXXFLAGS`. 
Most likely we should enable this in ubsan builds, where it will not interfere with asan/msan. 

No urgency, filing FTR, or in case someone wants to try it. 
I have not tested it in oss-fuzz setting. 

Example report on the 'example' project:
```
/usr/local/bin/../include/c++/v1/vector:1497: _LIBCPP_ASSERT '__n < size()' failed. vector[] index out of bounds
==273== ERROR: libFuzzer: deadly signal
    #0 0x4e8cf3 in __sanitizer_print_stack_trace /src/llvm/projects/compiler-rt/lib/asan/asan_stack.cc:38
    #1 0x542175 in fuzzer::Fuzzer::CrashCallback() /src/libfuzzer/FuzzerLoop.cpp:195:5
    #2 0x54210c in fuzzer::Fuzzer::StaticCrashSignalCallback() /src/libfuzzer/FuzzerLoop.cpp:179:6
    #3 0x7f7a4596938f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1138f)
    #4 0x7f7a44fa2427 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
    #5 0x7f7a44fa4029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #6 0x59cc1c in std::__1::__libcpp_abort_debug_function(std::__1::__libcpp_debug_info const&) (/out/do_stuff_fuzzer+0x59cc1c)
    #7 0x51a344 in operator[] /usr/local/bin/../include/c++/v1/vector:1497:5
    #8 0x51a344 in DoStuff(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /src/my-git-repo/projects/example/my-api-repo/my_api.cpp:24
    #9 0x5184b7 in LLVMFuzzerTestOneInput /src/my-git-repo/projects/example/my-api-repo/do_stuff_fuzzer.cpp:11:3

```

**Comment by inferno-chromium** [comment]
In addition to enabling -D_LIBCPP_DEBUG=1, we need to add a parsing signature for _LIBCPP_ASSERT.
