### ISSUE TITLE
Unreproducible issue keeps coming back

### ISSUE THREAD

**Issue by rlohning** [google/oss-fuzz#6147]
Hi,

in Qt, I keep getting a failure report which I'm unable to reproduce even in the Docker image, see below. The reports are labelled "Reliably Reproduces: | YES". After a couple of weeks, the current report is being closed as "Verified" and a new one appears a few days after.

Can you please give me any hints how to reproduce or - even better - solve this problem?

Cheers,
Robert

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32867
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34953
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36776

**Comment by inferno-chromium** [comment]
From stacktrace, it seems stuck in some decoding loop leading to OOM. running locally, you might not run into oom, but do you see lot of decoding work leading to high memory use, that probably needs fixing. we wont have cycles to debug at our end, but some parts of stacktrace interesting are:

```
==15151==ERROR: AddressSanitizer failed to allocate 0xb0000 (720896) bytes of LargeMmapAllocator (error code: 1)
```

```
#9 0x83fbcbb in allocateData /src/qt/qtbase/src/corelib/tools/qarraydata.cpp:178:52
--
  | #10 0x83fbcbb in QArrayData::allocate(QArrayData**, int, int, int, QArrayData::AllocationOption) /src/qt/qtbase/src/corelib/tools/qarraydata.cpp:227:26
  | #11 0x81cc4b6 in allocate /src/qt/qtbase/src/corelib/tools/qarraydata.h:141:24
  | #12 0x81cc4b6 in QList<QtCbor::Element>::reserve(int) /src/qt/qtbase/src/corelib/tools/qlist.h:685:26
  | #13 0x81d544d in createContainerFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1503:25
  | #14 0x81d3ddb in QCborContainerPrivate::decodeValueFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1689:33
  | #15 0x81d5545 in createContainerFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1515:12
  | #16 0x81d3ddb in QCborContainerPrivate::decodeValueFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1689:33
  | #17 0x81d5545 in createContainerFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1515:12
  | #18 0x81d3ddb in QCborContainerPrivate::decodeValueFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1689:33
  | #19 0x81d5545 in createContainerFromCbor(QCborStreamReader&, int) /src/qt/qtbase/src/corelib/serialization/qcborvalue.cpp:1515:12
```

**Comment by MarcoFalke** [comment]
OOM might be harder to reproduce, as the memory usage can vary per run. Some fuzzing engines keep state in memory that accumulates over the fuzzing campaign. So if you are close to the memory limit, you might not reproduce by running the input alone, but only as part of a longer running campaign.

Have you tried reproducing locally by reducing the max memory setting? For libfuzzer the setting would be `rss_limit_mb`
