### ISSUE TITLE
"Merging new testcases failed:" without a reason

### ISSUE THREAD

**Issue by mkj** [google/oss-fuzz#627]
The dropbear fuzzer-preauth isn't working properly, all the logs have "Merging new testcases failed:" without an obvious explanation. Any ideas?
```
Command: /mnt/scratch0/clusterfuzz/slave-bot/builds/clusterfuzz-builds_dropbear_c12a2686d052ab7b8f1226333b58ae391cc875ba/revisions/fuzzer-preauth -max_len=50000 -timeout=25 -rss_limit_mb=2048 -use_value_profile=1 -artifact_prefix=/ -max_total_time=2950 -print_final_stats=1 /new /subset
Bot: oss-fuzz-linux-zone1-pre-dropbear-brjz
Time ran: 0.027143

INFO: Seed: 3974193989
INFO: Loaded 1 modules (4388 guards): [0x9379f0, 0x93be80),
Loading corpus dir: /new
Loading corpus dir: /subset
#0	READ units: 2

cf::fuzzing_strategies: corpus_subset_2,value_profile
Merging new testcases failed:
```

**Comment by oliverchang** [comment]
Sorry for the misleading ":" in "Merging new testcases failed:" -- it's not meant to output anything here.

I haven't taken a close look into this one yet, but our environment has a few restrictions -- please see [this](https://github.com/google/oss-fuzz/blob/master/docs/fuzzer_environment.md) page.

I looks like this target is crashing on startup. @kcc any idea why we see "AddressSanitizer: nested bug in the same thread, aborting." with no stack?

```
Loading corpus dir: /new
Loading corpus dir: /dropbear_fuzzer-preauth
Loading corpus dir: /mutations
Loaded 1024/2000 files from /mutations
#0	READ units: 2003
ASAN:DEADLYSIGNAL
=================================================================
==1==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fbe3bafc2f0 bp 0x96db411a70eb6aed sp 0x96db411a70eb6aed T0)
==1==The signal is caused by a READ memory access.
==1==Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
ASAN:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.

cf::fuzzing_strategies: corpus_mutations
Merging new testcases failed:
```

**Comment by mkj** [comment]
Oh I didn't see the logs with segv, somehow I picked ones without that.

Let me try removing my segv handler, that might sort it out.

**Comment by mkj** [comment]
There actually isn't any segv handler for Dropbear, and removing the longjmp in fuzzer-preauth.c doesn't avoid the nested bug either.

**Comment by oliverchang** [comment]
Looking at this in gdb, it's crashing in longjmp.

```
#0      READ units: 1
#1      INITED cov: 298 ft: 27 corp: 1/1b exec/s: 0 rss: 54Mb
#2      NEW    cov: 299 ft: 33 corp: 2/62b exec/s: 0 rss: 54Mb L: 61 MS: 1 InsertRepeatedBytes-

Thread 1 "fuzzer-preauth" hit Breakpoint 1, __longjmp () at ../sysdeps/x86_64/__longjmp.S:29
29      ../sysdeps/x86_64/__longjmp.S: No such file or directory.
(gdb) bt
#0  __longjmp () at ../sysdeps/x86_64/__longjmp.S:29
#1  0x00007ffff6ac0289 in __libc_siglongjmp (env=0x2880cb8 <fuzz+80>, val=1) at longjmp.c:38
#2  0x0000000000553424 in svr_dropbear_exit () at svr-session.c:189
#3  0x0000000000518e41 in dropbear_close () at dbutil.c:100
#4  0x000000000052f4a1 in read_session_identification () at common-session.c:384
#5  0x000000000052e44b in session_loop () at common-session.c:237
#6  0x0000000000552cd5 in svr_session () at svr-session.c:140
#7  0x0000000000518993 in LLVMFuzzerTestOneInput () at fuzzer-preauth.c:44
#8  0x00000000005c3fda in ExecuteCallback () at /src/libfuzzer/FuzzerLoop.cpp:458
#9  0x00000000005c480b in RunOne () at /src/libfuzzer/FuzzerLoop.cpp:397
#10 0x00000000005c6132 in MutateAndTestOne () at /src/libfuzzer/FuzzerLoop.cpp:596
#11 0x00000000005c68f8 in Loop () at /src/libfuzzer/FuzzerLoop.cpp:624
#12 0x00000000005a7369 in FuzzerDriver () at /src/libfuzzer/FuzzerDriver.cpp:744
#13 0x000000000059ad49 in main () at /src/libfuzzer/FuzzerMain.cpp:20
```

**Comment by mkj** [comment]
The problem was getpwnam() and I assume no /etc/passwd, removing the following fixed it. Maybe something is odd with getpwnam interception.

```
pw = getpwuid(getuid());
dropbear_assert(pw);
fuzz.pw_name = m_strdup(pw->pw_name);
```
