### ISSUE TITLE
qcms coverage build broke

### ISSUE THREAD

**Issue by jrmuizel** [google/oss-fuzz#6283]
```
Step #5: warning: /workspace/out/coverage/dumps/fuzz.10014153449864872338_0.profraw: Unsupported instrumentation profile format version
Step #5: error: No profiles could be merged.
Step #5: [2021-08-23 12:48:22,009 INFO] Finding shared libraries for targets (if any).
Step #5: [2021-08-23 12:48:22,019 INFO] Finished finding shared libraries for targets.
Step #5: error: fuzz: Failed to load coverage: No such file or directory
Step #5: error: Could not load coverage information
Step #5: error: /workspace/out/coverage/dumps/*.profdata: No such file or directory
```

**Comment by jrmuizel** [comment]
From https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37526

**Comment by DavidKorczynski** [comment]
I think this is the same as here: https://github.com/google/oss-fuzz/issues/6283 

All Rust projects seem affected.

**Comment by catenacyber** [comment]
Just fixed by https://github.com/google/oss-fuzz/pull/6551

**Comment by MarcoFalke** [comment]
Can be closed as per https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37526#c6?

**Comment by phretor** [comment]
I'm still getting this. Here are the steps to reproduce:

```
$ git clone https://github.com/phretor/oss-fuzz
$ git clone https://github.com/phretor/cyclonedds /tmp/cyclonedds
$ cd oss-fuzz
$ export PROJECT_NAME=cyclonedds
$ export FUZZ_TARGET=fuzz_config_init
$ python3 infra/helper.py build_image $PROJECT_NAME
$ python3 infra/helper.py build_fuzzers --sanitizer coverage $PROJECT_NAME /tmp/cyclonedds
$ python3 infra/helper.py run_fuzzer $PROJECT_NAME $FUZZ_TARGET
$ # ... runs good
$ python3 infra/helper.py build_fuzzers --sanitizer coverage $PROJECT_NAME /tmp/cyclonedds
$ unzip -d build/out/cyclonedds/fuzz_config_init_seed_corpus build/out/cyclonedds/fuzz_config_init_seed_corpus.zip
$ python3 infra/helper.py coverage $PROJECT_NAME --fuzz-target=$FUZZ_TARGET --corpus-dir="build/out/"$PROJECT_NAME/$FUZZ_TARGET"_seed_corpus"
INFO:root:Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e FUZZING_LANGUAGE=c -e PROJECT=cyclonedds -e SANITIZER=coverage -e HTTP_PORT=8008 -e COVERAGE_EXTRA_ARGS= -p 8008:8008 -v /Users/phretor/Sync/Projects/Prj-OSSFuzz/oss-fuzz/build/out/cyclonedds/fuzz_config_init_seed_corpus:/corpus/fuzz_config_init -v /Users/phretor/Sync/Projects/Prj-OSSFuzz/oss-fuzz/build/out/cyclonedds:/out -t gcr.io/oss-fuzz-base/base-runner coverage fuzz_config_init.
Running fuzz_config_init
Error occured while running fuzz_config_init:
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1243846769
MERGE-OUTER: 1 files, 0 in the initial corpus, 0 processed earlier
MERGE-OUTER: attempt 1
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1243877399
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge28.txt'
MERGE-INNER: 1 total files; 0 processed earlier; will process 1 files now
#1      pulse  exec/s: 0 rss: 29Mb
#1      DONE   exec/s: 0 rss: 29Mb
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==31==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address (pc 0x00000055c670 bp 0x0000005e0b50 sp 0x7fffb0a15f10 T31)
==31==The signal is caused by a READ memory access.
==31==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x55c670 in __llvm_write_binary_ids (/out/fuzz_config_init+0x55c670)
    #1 0x55bd19 in lprofWriteDataImpl (/out/fuzz_config_init+0x55bd19)
    #2 0x55bc6b in lprofWriteData (/out/fuzz_config_init+0x55bc6b)
    #3 0x55a62d in writeFile InstrProfilingFile.c
    #4 0x55a391 in __llvm_profile_write_file (/out/fuzz_config_init+0x55a391)
    #5 0x7f177cc5ea26  (/out/lib/libc.so.6+0x49a26)
    #6 0x7f177cc5ebdf in exit (/out/lib/libc.so.6+0x49bdf)
    #7 0x431796 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
    #8 0x45a7e2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #9 0x7f177cc3c0b2 in __libc_start_main (/out/lib/libc.so.6+0x270b2)
    #10 0x4090bd in _start (/out/fuzz_config_init+0x4090bd)

DEDUP_TOKEN: __llvm_write_binary_ids--lprofWriteDataImpl--lprofWriteData
UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV (/out/fuzz_config_init+0x55c670) in __llvm_write_binary_ids
==31==ABORTING
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
MERGE-OUTER: the control file has 95 bytes
MERGE-OUTER: consumed 0Mb (30Mb rss) to parse the control file
MERGE-OUTER: 0 new files with 0 new features added; 0 new coverage edges
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==28==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address (pc 0x00000055c670 bp 0x0000005e0b50 sp 0x7ffff6e68f10 T28)
==28==The signal is caused by a READ memory access.
==28==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
    #0 0x55c670 in __llvm_write_binary_ids (/out/fuzz_config_init+0x55c670)
    #1 0x55bd19 in lprofWriteDataImpl (/out/fuzz_config_init+0x55bd19)
    #2 0x55bc6b in lprofWriteData (/out/fuzz_config_init+0x55bc6b)
    #3 0x55a62d in writeFile InstrProfilingFile.c
    #4 0x55a391 in __llvm_profile_write_file (/out/fuzz_config_init+0x55a391)
    #5 0x7f333a072a26  (/out/lib/libc.so.6+0x49a26)
    #6 0x7f333a072bdf in exit (/out/lib/libc.so.6+0x49bdf)
    #7 0x42e05b in fuzzer::Merge(fuzzer::Fuzzer*, fuzzer::FuzzingOptions&, std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, std::__Fuzzer::allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&, std::__Fuzzer::vector<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> >, std::__Fuzzer::allocator<std::__Fuzzer::basic_string<char, std::__Fuzzer::char_traits<char>, std::__Fuzzer::allocator<char> > > > const&, char const*) cxa_noexception.cpp
    #8 0x43172e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
    #9 0x45a7e2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #10 0x7f333a0500b2 in __libc_start_main (/out/lib/libc.so.6+0x270b2)
    #11 0x4090bd in _start (/out/fuzz_config_init+0x4090bd)

DEDUP_TOKEN: __llvm_write_binary_ids--lprofWriteDataImpl--lprofWriteData
UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV (/out/fuzz_config_init+0x55c670) in __llvm_write_binary_ids
==28==ABORTING
error: /out/dumps/*.profdata: No such file or directory
ERROR:root:Failed to generate clang code coverage report.
```
