### ISSUE TITLE
CIFuzz seems to fail due to "UnicodeDecodeError" from time to time

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#6438]
My guess would be that it started happening when https://github.com/google/oss-fuzz/pull/6375 was merged because as far as I can tell that bug had been fixed in https://github.com/google/oss-fuzz/pull/4537
```
2021-09-13T13:45:37.5090808Z INFO: seed corpus: files: 13562 min: 1b max: 4194301b total: 55527791b rss: 48Mb
2021-09-13T13:45:37.5122400Z Traceback (most recent call last):
2021-09-13T13:45:37.5123585Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 104, in <module>
2021-09-13T13:45:37.5124229Z     sys.exit(main())
2021-09-13T13:45:37.5124979Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 100, in main
2021-09-13T13:45:37.5125833Z     return run_fuzzers_entrypoint()
2021-09-13T13:45:37.5126741Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 63, in run_fuzzers_entrypoint
2021-09-13T13:45:37.5127483Z     result = run_fuzzers.run_fuzzers(config)
2021-09-13T13:45:37.5128298Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 297, in run_fuzzers
2021-09-13T13:45:37.5128938Z     if not fuzz_target_runner.run_fuzz_targets():
2021-09-13T13:45:37.5129769Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 139, in run_fuzz_targets
2021-09-13T13:45:37.5130402Z     result = self.run_fuzz_target(target)
2021-09-13T13:45:37.5131207Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 234, in run_fuzz_target
2021-09-13T13:45:37.5131816Z     return fuzz_target_obj.fuzz()
2021-09-13T13:45:37.5132541Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 151, in fuzz
2021-09-13T13:45:37.5133220Z     result = engine_impl.fuzz(self.target_path, options,
2021-09-13T13:45:37.5134306Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 266, in fuzz
2021-09-13T13:45:37.5135114Z     fuzz_result = runner.fuzz(
2021-09-13T13:45:37.5136086Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py", line 411, in fuzz
2021-09-13T13:45:37.5137069Z     return LibFuzzerCommon.fuzz(self, corpus_directories, fuzz_timeout,
2021-09-13T13:45:37.5138244Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py", line 228, in fuzz
2021-09-13T13:45:37.5138989Z     return self.run_and_wait(
2021-09-13T13:45:37.5139954Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/system/new_process.py", line 407, in run_and_wait
2021-09-13T13:45:37.5140858Z     result = ProcessRunner.run_and_wait(self, *args, **kwargs)
2021-09-13T13:45:37.5141946Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/system/new_process.py", line 391, in run_and_wait
2021-09-13T13:45:37.5142695Z     result = wait_process(
2021-09-13T13:45:37.5143645Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/system/new_process.py", line 98, in wait_process
2021-09-13T13:45:37.5144524Z     output = process.communicate(input_data)[0]
2021-09-13T13:45:37.5145889Z   File "/usr/local/lib/python3.8/site-packages/clusterfuzz/_internal/system/new_process.py", line 174, in communicate
2021-09-13T13:45:37.5146710Z     sys.stdout.write(line.decode())
2021-09-13T13:45:37.5147662Z UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 15: invalid start byte
2021-09-13T13:45:38.3733205Z ##[group]Run actions/upload-artifact@v1
2021-09-13T13:45:38.3733702Z with:
2021-09-13T13:45:38.3734117Z   name: address-artifacts
2021-09-13T13:45:38.3734555Z   path: ./out/artifacts
2021-09-13T13:45:38.3734939Z ##[endgroup]
2021-09-13T13:45:38.6480950Z Uploading artifact 'address-artifacts' from '/home/runner/work/selinux/selinux/out/artifacts' for run #355
2021-09-13T13:45:38.7470021Z Uploading 0 files
2021-09-13T13:45:38.7510458Z File upload complete.
2021-09-13T13:45:38.7521794Z Uploaded '0' bytes from '/home/runner/work/selinux/selinux/out/artifacts' to server
2021-09-13T13:45:39.0112500Z Associated artifact address-artifacts (18158771) with run #355
2021-09-13T13:45:39.0186376Z Cleaning up orphan processes
```

**Comment by oliverchang** [comment]
This particular issue should be fixed by https://github.com/google/oss-fuzz/pull/6445. Please let us know if it's the case.

**Comment by evverx** [comment]
Thanks! I've just opened https://github.com/SELinuxProject/selinux/pull/306 to trigger CIFuzz to make sure it works. I'll close the issue once CIFuzz is green there.

**Comment by evverx** [comment]
Looks like the issue is gone. Closing. Thanks!
