### ISSUE TITLE
autoconf fails to detect iconv()

### ISSUE THREAD

**Issue by rockdaboot** [google/oss-fuzz#648]
'make check' fails in the docker image because ./configure fails to detect iconv().
From config.log:
```
configure:12874: checking for working iconv
configure:13003: clang -o conftest -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-us
e-after-scope -fsanitize-coverage=trace-pc-guard,trace-cmp   conftest.c  >&5
configure:13003: $? = 0
configure:13003: ./conftest

=================================================================
==3256==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 112 byte(s) in 1 object(s) allocated from:
    #0 0x4d8488 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x7f86aa01c3e0  (/lib/x86_64-linux-gnu/libc.so.6+0x213e0)
    #2 0x7f86aa01be29 in iconv_open (/lib/x86_64-linux-gnu/libc.so.6+0x20e29)
    #3 0x51079e in main /src/wget2/conftest.c:278:7
    #4 0x7f86aa01b82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 32640 byte(s) in 1 object(s) allocated from:
    #0 0x4d8488 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x7f86aa01c44b  (/lib/x86_64-linux-gnu/libc.so.6+0x2144b)
    #2 0x7f86aa01be29 in iconv_open (/lib/x86_64-linux-gnu/libc.so.6+0x20e29)
    #3 0x51079e in main /src/wget2/conftest.c:278:7
    #4 0x7f86aa01b82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Indirect leak of 208 byte(s) in 1 object(s) allocated from:
    #0 0x4d8488 in __interceptor_malloc /src/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:66
    #1 0x7f86aa025314  (/lib/x86_64-linux-gnu/libc.so.6+0x2a314)

SUMMARY: AddressSanitizer: 32960 byte(s) leaked in 3 allocation(s).
configure:13003: $? = 1
configure: program exited with status 1
```

Of course I could ignore that result and set HAVE_ICONV 'manually', but since wget2 uses iconv() the test suite might not survive at a later point. What do you suggest ?

**Comment by rockdaboot** [comment]
Yeah, it's a bug in the iconv/libc version installed in the docker image.

Thanks for the pointer to those other projects ! Looks like the same issue.
