### ISSUE TITLE
Unreproducible issue related to __clang_call_terminate

### ISSUE THREAD

**Issue by rouault** [google/oss-fuzz#651]
I'm trying to investigate https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2114 / https://oss-fuzz.com/v2/testcase-detail/5721220311941120?noredirect=1 and I can't reproduce it, with a build of mine with ASAN enabled, nor with infra/helper.py reproduce

```
$ python infra/helper.py reproduce gdal ogr_fuzzer clusterfuzz-testcase-minimized-5721220311941120 
Running: docker run --rm -i --cap-add SYS_PTRACE -v /home/even/oss-fuzz/build/out/gdal:/out -v lusterfuzz-testcase-minimized-5721220311941120:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce ogr_fuzzer -runs=100
+ FUZZER=ogr_fuzzer
+ shift
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export PATH=/out:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out
+ PATH=/out:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out
+ cd /out
+ /out/ogr_fuzzer -rss_limit_mb=2048 -timeout=25 -runs=100 /testcase
INFO: Seed: 824812086
INFO: Loaded 1 modules (269739 guards): [0x4b37b10, 0x4c3f1bc), 
/out/ogr_fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
Executed /testcase in 86 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

**Comment by kcc** [comment]
I can get this to crash like this: 
```
python infra/helper.py build_image gdal 
python infra/helper.py build_fuzzers gdal 
python infra/helper.py reproduce gdal ogr_fuzzer INPUT 
```


```
Running: docker run --rm -i --cap-add SYS_PTRACE -v /usr/local/google/home/kcc/oss-fuzz/build/out/gdal:/out -v /usr/local/google/home/kcc/oss-fuzz/INPUT:/testcase -t gcr.io/oss-fuzz-base/base-runner reproduce ogr_fuzzer -runs=100
+ FUZZER=ogr_fuzzer
+ shift
+ TESTCASE=/testcase
+ '[' '!' -f /testcase ']'
+ export PATH=/out:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out
+ PATH=/out:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/out
+ cd /out
+ /out/ogr_fuzzer -rss_limit_mb=2048 -timeout=25 -runs=100 /testcase
INFO: Seed: 3593026416
INFO: Loaded 1 modules (286760 guards): [0x5014630, 0x512c6d0), 
/out/ogr_fuzzer: Running 1 inputs 100 time(s) each.
Running: /testcase
terminating with uncaught exception of type PCIDSK::PCIDSKException: File not open for update in WriteToFile()
ASAN:DEADLYSIGNAL
=================================================================
==6==ERROR: AddressSanitizer: ABRT on unknown address 0x000000000006 (pc 0x7ff648746428 bp 0x7ffd0074a1b0 sp 0x7ffd00749f78 T0)
SCARINESS: 10 (signal)
    #0 0x7ff648746427 in gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x35427)
    #1 0x7ff648748029 in abort (/lib/x86_64-linux-gnu/libc.so.6+0x37029)
    #2 0x2453426 in abort_message (/out/ogr_fuzzer+0x2453426)
    #3 0x2455065 in demangling_terminate_handler() (/out/ogr_fuzzer+0x2455065)
    #4 0x24530c5 in std::__terminate(void (*)()) (/out/ogr_fuzzer+0x24530c5)
    #5 0x2453130 in std::terminate() (/out/ogr_fuzzer+0x2453130)
    #6 0x534dca in __clang_call_terminate (/out/ogr_fuzzer+0x534dca)
    #7 0x144735f in PCIDSK::CPCIDSKGCP2Segment::~CPCIDSKGCP2Segment() /src/gdal/gdal/frmts/pcidsk/sdk/segment/cpcidskgcp2segment.cpp:77:1
    #8 0x1448133 in PCIDSK::CPCIDSKGCP2Segment::~CPCIDSKGCP2Segment() /src/gdal/gdal/frmts/pcidsk/sdk/segment/cpcidskgcp2segment.cpp:71:1
    #9 0x144823c in PCIDSK::CPCIDSKGCP2Segment::~CPCIDSKGCP2Segment() /src/gdal/gdal/frmts/pcidsk/sdk/segment/cpcidskgcp2segment.cpp:71:1
    #10 0x1433cb7 in PCIDSK::CPCIDSKFile::~CPCIDSKFile() /src/gdal/gdal/frmts/pcidsk/sdk/core/cpcidskfile.cpp:140:9
    #11 0x14346ec in PCIDSK::CPCIDSKFile::~CPCIDSKFile() /src/gdal/gdal/frmts/pcidsk/sdk/core/cpcidskfile.cpp:114:1
    #12 0xace63e in PCIDSK2Dataset::~PCIDSK2Dataset() /src/gdal/gdal/frmts/pcidsk/pcidskdataset2.cpp:837:13
    #13 0xace79c in PCIDSK2Dataset::~PCIDSK2Dataset() /src/gdal/gdal/frmts/pcidsk/pcidskdataset2.cpp:826:1
    #14 0x522b34 in LLVMFuzzerTestOneInput /src/gdal/gdal/./fuzzers/ogr_fuzzer.cpp:116:9
    #15 0x54bf29 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:458:13
    #16 0x54c75a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:397:3
    #17 0x523686 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/libfuzzer/FuzzerDriver.cpp:268:6
    #18 0x52ebf0 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/libfuzzer/FuzzerDriver.cpp:683:9
    #19 0x522c98 in main /src/libfuzzer/FuzzerMain.cpp:20:10
    #20 0x7ff64873182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #21 0x427a88 in _start (/out/ogr_fuzzer+0x427a88)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x35427) in gsignal
```


I think the key line here is 
```
terminating with uncaught exception of type PCIDSK::PCIDSKException: File not open for update in WriteToFile()
```

**Comment by rouault** [comment]
Oh, I understand what happens now. It is reproducible indeed on a freshly downloaded file. At the first execution on the file, the file is modified by the faulty destructor in such a way that the exception is not thrown in later executions... 

Sorry for the noise.
