### ISSUE TITLE
clusterfuzzlite doesn't support cron schedules

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#6576]
See  https://github.com/oliverchang/cifuzz-external-example/runs/3855865837?check_suite_focus=true

```
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 73, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 69, in main
    return build_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 31, in build_fuzzers_entrypoint
    config = config_utils.BuildFuzzersConfig()
  File "/opt/oss-fuzz/infra/cifuzz/config_utils.py", line 334, in __init__
    self._get_config_from_event_path(event)
  File "/opt/oss-fuzz/infra/cifuzz/config_utils.py", line 322, in _get_config_from_event_path
    self.git_url = event_data['repository']['html_url']
KeyError: 'repository'
```

**Comment by oliverchang** [comment]
Looks like cron schedule events don't provide any event payload: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
