### ISSUE TITLE
Issue with fuzzing run in Github actions

### ISSUE THREAD

**Issue by boxerab** [google/oss-fuzz#6685]
I have fuzzing enabled for one of my Github actions.
The action currently fails, but when I download the artifact and run it on my decoder,
I don't get the same output as is logged by the fuzzer. Also, the file name inside
the artifacts.zip file is the same for multiple actions, even after a new commit is pushed.
Also, even though both memory and address fuzzers fail, I only get a single artifact in the zip.

So, the artifacts file doesn't appear to be the one actually triggering the failed fuzz test.

https://github.com/GrokImageCompression/grok/runs/4001852962?check_suite_focus=true

Thanks!

**Comment by jonathanmetzman** [comment]
>I don't get the same output as is logged by the fuzzer.

I'm not sure why this. The OOM is from UndefinedBehaviorSanitizer by the way did you run it on a UBSAN build.

>Also, the file name inside the artifacts.zip file is the same for multiple actions, even after a new commit is pushed.

It looks like the same crash is being hit again. I looked at https://github.com/GrokImageCompression/grok/runs/3955433969?check_suite_focus=true the ASAN build there hits the same oom: oom-14154dbf1a56eb62baaca66f1d86fd1f3c2d9253

>Also, even though both memory and address fuzzers fail, I only get a single artifact in the zip.

I'm not sure why this is. Maybe it's a regression in CIFuzz. Need to look into this.  Also weird how there isn't a summary file.
Another thing I noticed is that the MemorySanitizer run ran into this exception:
```
2021-10-25T20:25:57.9896666Z Traceback (most recent call last):
2021-10-25T20:25:57.9898027Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 104, in <module>
2021-10-25T20:25:57.9898623Z     sys.exit(main())
2021-10-25T20:25:57.9899388Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 100, in main
2021-10-25T20:25:57.9900044Z     return run_fuzzers_entrypoint()
2021-10-25T20:25:57.9900942Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 63, in run_fuzzers_entrypoint
2021-10-25T20:25:57.9901857Z     result = run_fuzzers.run_fuzzers(config)
2021-10-25T20:25:57.9902640Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 298, in run_fuzzers
2021-10-25T20:25:57.9903280Z     if not fuzz_target_runner.run_fuzz_targets():
2021-10-25T20:25:57.9904255Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 139, in run_fuzz_targets
2021-10-25T20:25:57.9904898Z     result = self.run_fuzz_target(target)
2021-10-25T20:25:57.9905706Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 235, in run_fuzz_target
2021-10-25T20:25:57.9906298Z     return fuzz_target_obj.fuzz()
2021-10-25T20:25:57.9907037Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 162, in fuzz
2021-10-25T20:25:57.9907676Z     if self.is_crash_reportable(crash.input_path):
2021-10-25T20:25:57.9908566Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 253, in is_crash_reportable
2021-10-25T20:25:57.9909323Z     reproducible_on_code_change = self.is_reproducible(
2021-10-25T20:25:57.9910216Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 220, in is_reproducible
2021-10-25T20:25:57.9910923Z     result = engine_impl.reproduce(target_path,
2021-10-25T20:25:57.9912018Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 391, in reproduce
2021-10-25T20:25:57.9913202Z     raise TimeoutError('Reproducing timed out\n' + result.output)
```
It's somewhat similar to #6703

Another thing I noticed: It's very hard to read the logs from your project because the fuzzers spam so much output. If you could turn this off, it would make things easier for me to debug. Thanks!

**Comment by jonathanmetzman** [comment]
When #6703 lands you can turn off OOM reporting so at least CI wont turn red. But it will negatively impact fuzzing it seems, since it is happening so often.

**Comment by jonathanmetzman** [comment]
I might not have time to resolve this so soon since I have a lot coming up this week. But I'll try to get to it at some point.

**Comment by boxerab** [comment]
@jonathanmetzman thanks for looking into this! I disabled fuzzer console spamming.
I now can see what is really happening - this is an OOM, which is a known issue for the library.
I will close this, and eventually fix that OOM :)
