### ISSUE TITLE
CIFuzz seems to have started reporting timeouts

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#6703]
I'm not sure what happened 10-11 days ago but since then CIFuzz has been failing at https://github.com/karelzak/util-linux/actions/workflows/cifuzz.yml . As far as I can remember timeouts were supposed to be ignored by default
```
2021-10-21T11:18:36.8621581Z INFO: Running with entropic power schedule (0xFF, 100).
2021-10-21T11:18:36.8622139Z INFO: Seed: 1337
2021-10-21T11:18:36.8623066Z INFO: Loaded 1 modules   (11453 inline 8-bit counters): 11453 [0x6de170, 0x6e0e2d),
2021-10-21T11:18:36.8623817Z INFO: Loaded 1 PC tables (11453 PCs): 11453 [0x6e0e30,0x70da00),
2021-10-21T11:18:36.8624590Z INFO:     3492 files found in /github/workspace/cifuzz-corpus/test_mount_fuzz
2021-10-21T11:18:36.8627422Z INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
2021-10-21T11:18:36.8628101Z INFO: seed corpus: files: 3492 min: 1b max: 5242879b total: 30364753b rss: 52Mb
2021-10-21T11:18:36.8628642Z ALARM: working on the last Unit for 30 seconds
2021-10-21T11:18:36.8629330Z        and the timeout value is 25 (use -timeout=N to change)
2021-10-21T11:18:36.8629819Z MS: 0 ; base unit: 0000000000000000000000000000000000000000
2021-10-21T11:18:36.8631066Z artifact_prefix='/github/workspace/out/artifacts/'; Test unit written to /github/workspace/out/artifacts/timeout-b0220df8b318e58497e8e4c336de487f471049e6
2021-10-21T11:18:36.8632140Z ==31== ERROR: libFuzzer: timeout after 30 seconds
2021-10-21T11:18:36.8633069Z     #0 0x52ff91 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
2021-10-21T11:18:36.8634189Z     #1 0x471788 in fuzzer::PrintStackTrace() cxa_noexception.cpp
2021-10-21T11:18:36.8634872Z     #2 0x4568b9 in fuzzer::Fuzzer::AlarmCallback() cxa_noexception.cpp
2021-10-21T11:18:36.8635753Z     #3 0x7fe076e5a3bf  (/lib/x86_64-linux-gnu/libpthread.so.0+0x153bf)
2021-10-21T11:18:36.8636579Z     #4 0x7fe076b96f21  (/lib/x86_64-linux-gnu/libc.so.6+0xbef21)
2021-10-21T11:18:36.8638369Z     #5 0x4a747a in __asan::Allocator::Reallocate(void*, unsigned long, __sanitizer::BufferedStackTrace*) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:736:7
2021-10-21T11:18:36.8640063Z     #6 0x4a7355 in __asan::asan_realloc(void*, unsigned long, __sanitizer::BufferedStackTrace*) /src/llvm-project/compiler-rt/lib/asan/asan_allocator.cpp:994:34
2021-10-21T11:18:36.8641345Z     #7 0x5263a5 in __interceptor_realloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:149:10
2021-10-21T11:18:36.8642277Z     #8 0x5a19c7 in strappend /src/util-linux/lib/strutils.c:1012:8
2021-10-21T11:18:36.8643121Z     #9 0x55fe30 in mnt_table_append_intro_comment /src/util-linux/libmount/src/tab.c:312:9
2021-10-21T11:18:36.8644606Z     #10 0x574c8f in append_comment /src/util-linux/libmount/src/tab_parse.c:523:8
2021-10-21T11:18:36.8645913Z     #11 0x56c351 in mnt_table_parse_next /src/util-linux/libmount/src/tab_parse.c:571:10
2021-10-21T11:18:36.8646990Z     #12 0x56c351 in mnt_table_parse_stream /src/util-linux/libmount/src/tab_parse.c:745:8
2021-10-21T11:18:36.8648538Z     #13 0x55edff in LLVMFuzzerTestOneInput /src/util-linux/libmount/src/fuzz.c:25:16
2021-10-21T11:18:36.8649425Z     #14 0x457ee3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) cxa_noexception.cpp
2021-10-21T11:18:36.8650602Z     #15 0x4576dd in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) cxa_noexception.cpp
2021-10-21T11:18:36.8652026Z     #16 0x459524 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
2021-10-21T11:18:36.8653329Z     #17 0x459759 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) cxa_noexception.cpp
2021-10-21T11:18:36.8654551Z     #18 0x449128 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) cxa_noexception.cpp
2021-10-21T11:18:36.8655974Z     #19 0x471f42 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
2021-10-21T11:18:36.8656852Z     #20 0x7fe076aff0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
2021-10-21T11:18:36.8657620Z     #21 0x420a2d in _start (build-out/test_mount_fuzz+0x420a2d)
2021-10-21T11:18:36.8657954Z
2021-10-21T11:18:36.8658985Z DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::AlarmCallback()
2021-10-21T11:18:36.8659705Z SUMMARY: libFuzzer: timeout
2021-10-21T11:18:36.8672184Z stat::number_of_executed_units: 3484
2021-10-21T11:18:36.8672616Z stat::average_exec_per_sec:     89
2021-10-21T11:18:36.8673018Z stat::new_units_added:          0
2021-10-21T11:18:36.8673397Z stat::slowest_unit_time_sec:    0
2021-10-21T11:18:36.8673805Z stat::peak_rss_mb:              314
2021-10-21T11:18:36.8674461Z INFO: Running with entropic power schedule (0xFF, 100).
2021-10-21T11:18:36.8675092Z INFO: Seed: 210127730
2021-10-21T11:18:36.8675938Z INFO: Loaded 1 modules   (11453 inline 8-bit counters): 11453 [0x6de170, 0x6e0e2d),
2021-10-21T11:18:36.8676542Z INFO: Loaded 1 PC tables (11453 PCs): 11453 [0x6e0e30,0x70da00),
2021-10-21T11:18:36.8677569Z /github/workspace/build-out/test_mount_fuzz: Running 1 inputs 100 time(s) each.
2021-10-21T11:18:36.8679080Z Running: /github/workspace/out/artifacts/timeout-b0220df8b318e58497e8e4c336de487f471049e6
```

**Comment by jonathanmetzman** [comment]
I'm not sure why this is.
My impression was we always reported timeouts (see https://github.com/google/oss-fuzz/issues/3432), but I thought it was a bad idea. 
Before I work on this, I'd like your opinion, do you think it's preferable to get timeouts reported or not?

**Comment by evverx** [comment]
Given that all the fuzz targets I've kept track of time out on GitHub one way or another I don't think timeouts should be reported by default. But as long as it's configurable I think it should be fine either way.

**Comment by jonathanmetzman** [comment]
> Given that all the fuzz targets I've kept track of time out on GitHub one way or another I don't think timeouts should be reported by default. But as long as it's configurable I think it should be fine either way.

Good point. I think the easiest way to fix this without doing violence to libClusterFuzz is to pass `-timeout=$MAX_TOTAL_TIME` as an argument when not reporting timeouts.
