### ISSUE TITLE
google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master hangs

### ISSUE THREAD

**Issue by eustas** [google/oss-fuzz#6831]
Example of action that timed-out: https://github.com/libjxl/libjxl/runs/4215983662?check_suite_focus=true

Report:
```
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 60, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 56, in main
    return build_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 39, in build_fuzzers_entrypoint
    if not build_fuzzers.build_fuzzers(config):
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers.py", line 171, in build_fuzzers
    return builder.build()
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers.py", line 134, in build
    if not method():
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers.py", line 101, in build_fuzzers
    if not helper.docker_run(docker_args):
  File "/opt/oss-fuzz/infra/helper.py", line 547, in docker_run
    subprocess.check_call(command, stdout=stdout, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 342, in call
    return p.wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.8/subprocess.py", line 1806, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.8/subprocess.py", line 1764, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
```

**Comment by eustas** [comment]
Seems to be project-specific issue.
