### ISSUE TITLE
CIFuzz crashes on timeout

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#6952]
In the openjpeg CIFuzz integration https://github.com/uclouvain/openjpeg/runs/4367633038?check_suite_focus=true it seems like a timeout is causing CIFuzz to crash:
```
stat::number_of_executed_units: 3495
stat::average_exec_per_sec:     9
stat::new_units_added:          0
stat::slowest_unit_time_sec:    0
stat::peak_rss_mb:              2676
2021-11-30 13:05:23,886 - root - INFO - Fuzzer: opj_decompress_fuzzer. Detected bug.
2021-11-30 13:05:23,888 - root - INFO - Trying to reproduce crash using: /tmp/tmpyigc4gnx/oom-1e97ab9f66f722be4c7503c7073ef09e737c0c4c.
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 95, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 91, in main
    return run_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 61, in run_fuzzers_entrypoint
    result = run_fuzzers.run_fuzzers(config)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 302, in run_fuzzers
    if not fuzz_target_runner.run_fuzz_targets():
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 130, in run_fuzz_targets
    result = self.run_fuzz_target(target)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 245, in run_fuzz_target
    return fuzz_target_obj.fuzz()
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 187, in fuzz
    if self.is_crash_reportable(crash.input_path,
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 289, in is_crash_reportable
    reproducible_on_code_change = self.is_reproducible(
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 250, in is_reproducible
    result = engine_impl.reproduce(target_path,
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 391, in reproduce
    raise TimeoutError('Reproducing timed out\n' + result.output)
TimeoutError: Reproducing timed out 
```

**Comment by jonathanmetzman** [comment]
Will try to fix this by Monday.

**Comment by jonathanmetzman** [comment]
CC @oliverchang
