### ISSUE TITLE
ubsan_GetStackTrace NULL dereference

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#7113]
From https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43483

The stack trace is 
```
UndefinedBehaviorSanitizer:DEADLYSIGNAL
--
  | ==1092==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7fffc3526fa0 sp 0x7fffc3526f68 T1092)
  | ==1092==Hint: pc points to the zero page.
  | ==1092==The signal is caused by a READ memory access.
  | ==1092==Hint: address points to the zero page.
  | #0 0x0  (<unknown module>)
  | #0 0x5a4272 in ubsan_GetStackTrace(__sanitizer::BufferedStackTrace*, unsigned long, unsigned long, unsigned long, void*, bool) /src/llvm-project/compiler-rt/lib/ubsan/ubsan_diag.cpp:0
  | #1 0x5a3845 in ReportDeadlySignalImpl /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:223:3
  | #2 0x5a3845 in __sanitizer::ReportDeadlySignal(__sanitizer::SignalContext const&, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:237:5
  | #3 0x5a3b6a in __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) /src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:246:3
  | #4 0x7f2015ffb3bf in libpthread.so.0
  |  
  | UndefinedBehaviorSanitizer can not provide additional info.
  | SUMMARY: UndefinedBehaviorSanitizer: SEGV (<unknown module>)
```

It appeared on September 9th looking at the stats...

**Comment by oliverchang** [comment]
@morehouse @hctim is this something you could help take a look at based on the stacktrace? Looks like a bug in UBSan (that isn't consistently reproducible all the time)

**Comment by hctim** [comment]
Managed to get a stack under GDB:

```
#0  0x0000000000000000 in ?? ()
#1  0x00000000005b0029 in AppLayerParserGetTx () at app-layer-parser.c:1065
#2  0x00000000007ff184 in ConfigApplyTx () at detect-config.c:92
#3  ConfigApply () at detect-config.c:136
#4  DetectConfigPostMatch () at detect-config.c:149
#5  0x000000000074d671 in DetectRunPostMatch () at detect.c:164
#6  0x000000000074aec0 in DetectRulePacketRules () at detect.c:789
#7  DetectRun () at detect.c:134
#8  0x0000000000748f52 in DetectFlow () at detect.c:1559
#9  Detect () at detect.c:1631
#10 0x0000000000627561 in FlowWorker () at flow-worker.c:551
#11 0x00000000005abc80 in LLVMFuzzerTestOneInput () at tests/fuzz/fuzz_sigpcap_aware.c:168
#12 0x00000000005354b4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) ()
#13 0x0000000000534c9b in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) ()
#14 0x000000000053624a in fuzzer::Fuzzer::MutateAndTestOne() ()
#15 0x0000000000536f16 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) ()
#16 0x0000000000526830 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) ()
#17 0x000000000054f753 in main () at /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20
```

So, looks like a null-pc bug in the actual code. As to why UBSan isn't being helpful here, not sure, still looking.

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43733 gets the right stack trace for this NULL deref

**Comment by hctim** [comment]
I reckon that's a slightly different manifestation. I can pull that testcase down and reproduce it 100% of the time, on the same build as this bug. I'm guessing that `f` is non-null in the flaky case, and so doesn't trip UBSan's null-member check.

**Comment by hctim** [comment]
As a side note, the problem I'm trying to solve here is "why is UBSan not giving a good error report". I'm guessing that we mishandle somewhere in the printing logic.

The other open question, for @catenacyber, is "why is this bug not reproducible deterministically". Is there some global state or programmatic randomness in this fuzz target?

I can reproduce it by grabbing the test case, putting it in a corpus directory by itself, and firing up the fuzz target with the following options. It triggers after maybe ~30 seconds.

```
UBSAN_OPTIONS=silence_unsigned_overflow=1 ./fuzz_sigpcap_aware -seed=2645215130 /tmp/corpus
```

**Comment by catenacyber** [comment]
>  Is there some global state or programmatic randomness in this fuzz target?

There is a known problem about a global state that is not reset
https://github.com/OISF/suricata/pull/6856 should fix this
I am not sure if this is the one you meet

**Comment by hctim** [comment]
Yeah, so UBSan doesn't like unwinding null-pcs, or through a signal handler (assumedly the former):

```
mitchp@mitch:/tmp/null$ cat code.c
typedef void (*fnptr)(void);

int main() {
  fnptr p = 0;
  p();
  return 0;
}
mitchp@mitch:/tmp/null$ clang code.c -fsanitize=undefined
mitchp@mitch:/tmp/null$ ./a.out
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==3979795==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffe3b45c260 sp 0x7ffe3b45c248 T3979795)
==3979795==Hint: pc points to the zero page.
==3979795==The signal is caused by a READ memory access.
==3979795==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x4213f2 in ubsan_GetStackTrace(__sanitizer::BufferedStackTrace*, unsigned long, unsigned long, unsigned long, void*, bool) /usr/local/google/home/mitchp/llvm/compiler-rt/lib/ubsan/ubsan_diag.cpp
    #2 0x4209c0 in ReportDeadlySignalImpl /usr/local/google/home/mitchp/llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:223:3
    #3 0x4209c0 in __sanitizer::ReportDeadlySignal(__sanitizer::SignalContext const&, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) /usr/local/google/home/mitchp/llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:237:5
    #4 0x420cea in __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) /usr/local/google/home/mitchp/llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:246:3
    #5 0x7f77e63391ff  (/lib/x86_64-linux-gnu/libpthread.so.0+0x131ff)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV (<unknown module>)
==3979795==ABORTING
```

But, GDB is totally fine with unwinding through it. Let me take a look at the unwinder behaviour and I'll send a patch to LLVM (which will take $AMOUNT_OF_TIME to trickle through to OSS-Fuzz).

**Comment by oliverchang** [comment]
> Yeah, so UBSan doesn't like unwinding null-pcs, or through a signal handler (assumedly the former):
> 
> ```
> mitchp@mitch:/tmp/null$ cat code.c
> typedef void (*fnptr)(void);
> 
> int main() {
>   fnptr p = 0;
>   p();
>   return 0;
> }
> mitchp@mitch:/tmp/null$ clang code.c -fsanitize=undefined
> mitchp@mitch:/tmp/null$ ./a.out
> UndefinedBehaviorSanitizer:DEADLYSIGNAL
> ==3979795==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffe3b45c260 sp 0x7ffe3b45c248 T3979795)
> ==3979795==Hint: pc points to the zero page.
> ==3979795==The signal is caused by a READ memory access.
> ==3979795==Hint: address points to the zero page.
>     #0 0x0  (<unknown module>)
>     #1 0x4213f2 in ubsan_GetStackTrace(__sanitizer::BufferedStackTrace*, unsigned long, unsigned long, unsigned long, void*, bool) /usr/local/google/home/mitchp/llvm/compiler-rt/lib/ubsan/ubsan_diag.cpp
>     #2 0x4209c0 in ReportDeadlySignalImpl /usr/local/google/home/mitchp/llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:223:3
>     #3 0x4209c0 in __sanitizer::ReportDeadlySignal(__sanitizer::SignalContext const&, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) /usr/local/google/home/mitchp/llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:237:5
>     #4 0x420cea in __sanitizer::HandleDeadlySignal(void*, void*, unsigned int, void (*)(__sanitizer::SignalContext const&, void const*, __sanitizer::BufferedStackTrace*), void const*) /usr/local/google/home/mitchp/llvm/compiler-rt/lib/sanitizer_common/sanitizer_symbolizer_report.cpp:246:3
>     #5 0x7f77e63391ff  (/lib/x86_64-linux-gnu/libpthread.so.0+0x131ff)
> 
> UndefinedBehaviorSanitizer can not provide additional info.
> SUMMARY: UndefinedBehaviorSanitizer: SEGV (<unknown module>)
> ==3979795==ABORTING
> ```
> 
> But, GDB is totally fine with unwinding through it. Let me take a look at the unwinder behaviour and I'll send a patch to LLVM (which will take $AMOUNT_OF_TIME to trickle through to OSS-Fuzz).

Thanks a lot @hctim for looking into this!! :)

**Comment by catenacyber** [comment]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44138 looks like the same
