### ISSUE TITLE
"RuntimeError: Failed to build" when using build_specified_commit.py

### ISSUE THREAD

**Issue by DenizScholz** [google/oss-fuzz#7174]
Build failed for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=10020 when trying to build the project from a specified commit via `build_specified_commit.py`. The specified commit hash was taken from the regressed url. 

````
~ sudo python3 infra/build_specified_commit.py --project_name skia  --commit a76f6161f1c2640302bb5fb1371b2ac14cf5c6d7 > error_10020.txt

INFO:root:Running: docker build -t gcr.io/oss-fuzz/skia --file /home/deniz/Documents/GitHub/oss-fuzz/projects/skia/Dockerfile /home/deniz/Documents/GitHub/oss-fuzz/projects/skia.
INFO:root:Running: docker run --rm --privileged -i -v /tmp/tmp9x1wf0by:/out gcr.io/oss-fuzz/skia cp -r -p /src /out.
INFO:root:Running: docker build -t gcr.io/oss-fuzz/skia --file /home/deniz/Documents/GitHub/oss-fuzz/projects/skia/Dockerfile /home/deniz/Documents/GitHub/oss-fuzz/projects/skia.
INFO:root:Cleaning existing build artifacts.
INFO:root:Running: docker run --rm --privileged -i -v /home/deniz/Documents/GitHub/oss-fuzz/build/out/skia:/out -t gcr.io/oss-fuzz/skia /bin/bash -c 'rm -rf /out/*'.
INFO:root:Running: docker run --rm --privileged -i -v /home/deniz/Documents/GitHub/oss-fuzz/build/work/skia:/work -t gcr.io/oss-fuzz/skia /bin/bash -c 'rm -rf /work/*'.
INFO:root:Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e GIT_REPO= -e FUZZING_LANGUAGE=c++ -v /tmp/tmp9x1wf0by/src:/src -v /home/deniz/Documents/GitHub/oss-fuzz/build/out/skia:/out -v /home/deniz/Documents/GitHub/oss-fuzz/build/work/skia:/work -t gcr.io/oss-fuzz/skia.
ERROR:root:Building fuzzers failed.
INFO:root:Build failed. Retrying on earlier OSS-Fuzz commit 5c88efdd281b8f8e3b140b2c3dae71599ec2ad8a.
INFO:root:Using base-builder with digest sha256:fe322eb57206504e7e52530d49f2673b2276f02dd1efe4a1ee68ef7231a1e300.
INFO:root:Running: docker build -t gcr.io/oss-fuzz/skia --file /home/deniz/Documents/GitHub/oss-fuzz/projects/skia/Dockerfile /home/deniz/Documents/GitHub/oss-fuzz/projects/skia.
The command '/bin/sh -c git apply skia.diff' returned a non-zero code: 1
ERROR:root:Docker build failed.
ERROR:root:Failed to rebuild image.
Traceback (most recent call last):
  File "/home/deniz/Documents/GitHub/oss-fuzz/infra/build_specified_commit.py", line 411, in <module>
    main()
  File "/home/deniz/Documents/GitHub/oss-fuzz/infra/build_specified_commit.py", line 407, in main
    raise RuntimeError('Failed to build.')
RuntimeError: Failed to build.
````

You can find the build output in the error_10020.txt file.
[error_10020.txt](https://github.com/google/oss-fuzz/files/7918745/error_10020.txt)

Furthermore I'm also not able to build some other projects with this script. I can provide more examples later on if thats helpful.

**Comment by jonathanmetzman** [comment]
The file you linked to isn't accessible for me.
Here's my guess about what's happening.
Skia's dockerfile build depended on the contents of the skia.diff file. It applied it to the repo.
It no longer does this because that pattern breaks OSS-Fuzz's hacky methods for changing the checkout of the repo from master to a specified branch/PR (this feature is used by CIFuzz and build_specified_commit).
You see, the repo at the point that this patch is being applied is not at the state when the patch worked, the repo at that point is at HEAD.

So I'm not really sure how to fix this without doing something hacky and specific for skia (something that I'm not going to commit to this repo).

Do you need this case to work? or can you skip it? I guess with build_specified_commit, it isn't guaranteed to work on every project.
