### ISSUE TITLE
java coverage issues

### ISSUE THREAD

**Issue by DavidKorczynski** [google/oss-fuzz#7507]
Java projects coverage build started having some troubles:
```
Step #5: Error occured while running FuzzStreamParser:
Step #5: Exception in thread "main" java.lang.NoClassDefFoundError: com/code_intelligence/jazzer/runtime/JazzerInternal
Step #5: Caused by: java.lang.ClassNotFoundException: com.code_intelligence.jazzer.runtime.JazzerInternal
Step #5: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
Step #5: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
Step #5: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Step #5: libc++abi: terminating with uncaught exception of type std::runtime_error: Could not find class com/code_intelligence/jazzer/runtime/JazzerInternal
Step #5: Aborted (core dumped)
```

@fmeum -- is this something in the set up or is it something in the individual projects that need to be updated?

**Comment by fmeum** [comment]
I believe it's a regression in Jazzer that should be easy to fix. I will keep you updated.

**Comment by fmeum** [comment]
@DavidKorczynski Should be fixed by https://github.com/CodeIntelligenceTesting/jazzer/pull/384, which has just been merged. If you rebuild the images, the issue should be gone.

**Comment by DavidKorczynski** [comment]
Resolved -- thanks @fmeum !
