### ISSUE TITLE
builds status job is broken

### ISSUE THREAD

**Issue by oliverchang** [google/oss-fuzz#7552]
```
2022-04-11 23:05:59.158 GMTStep #1: Failed to find build log log-d545455d-d54e-40a0-a302-c27f361f3be8.txt
Info
2022-04-11 23:05:59.171 GMTStep #1: Traceback (most recent call last):
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/opt/oss-fuzz/infra/build_status/update_build_status.py", line 358, in <module>
Info
2022-04-11 23:05:59.171 GMTStep #1: main()
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/opt/oss-fuzz/infra/build_status/update_build_status.py", line 351, in main
Info
2022-04-11 23:05:59.171 GMTStep #1: update_build_status(tag, filename)
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/opt/oss-fuzz/infra/build_status/update_build_status.py", line 196, in update_build_status
Info
2022-04-11 23:05:59.171 GMTStep #1: project = future.result()
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
Info
2022-04-11 23:05:59.171 GMTStep #1: return self.__get_result()
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
Info
2022-04-11 23:05:59.171 GMTStep #1: raise self._exception
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
Info
2022-04-11 23:05:59.171 GMTStep #1: result = self.fn(*self.args, **self.kwargs)
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/opt/oss-fuzz/infra/build_status/update_build_status.py", line 184, in process_project
Info
2022-04-11 23:05:59.171 GMTStep #1: project = get_build_history(project_build.build_ids)
Info
2022-04-11 23:05:59.171 GMTStep #1: File "/opt/oss-fuzz/infra/build_status/update_build_status.py", line 160, in get_build_history
Info
2022-04-11 23:05:59.171 GMTStep #1: raise MissingBuildLogError(f'Missing build log file {log_name}')
Info
2022-04-11 23:05:59.171 GMTStep #1: __main__.MissingBuildLogError: Missing build log file log-d545455d-d54e-40a0-a302-c27f361f3be8
```

**Comment by Navidem** [comment]
Interestingly there is a build with id `d545455d-d54e-40a0-a302-c27f361f3be8` which times out without producing any log! 

This breaks the build-status as it cannot fetch such log.

**Comment by Navidem** [comment]
Not all failures are caused by the missing log file, I also see `socket.timeout: The read operation timed out` error (for example build `e02f5dc0-644e-46d6-80b5-bdfdce285cc5`)

**Comment by oliverchang** [comment]
> Not all failures are caused by the missing log file, I also see `socket.timeout: The read operation timed out` error (for example build `e02f5dc0-644e-46d6-80b5-bdfdce285cc5`)

That seems more like network flake, unless it's happening very frequently?

**Comment by Navidem** [comment]
Did a quick experiment by uploading a dummy log with the expected name `log-d545455d-d54e-40a0-a302-c27f361f3be8`. Still builds are failing with the same error.

**Comment by Navidem** [comment]
> Where did you upload it to? I couldn't find the expected file.

Wrong bucket: I used status bucket to upload it to `oss-fuzz-build-logs`!

> by logging an error and continuing.

will make a PR for this.
