### ISSUE TITLE
How to ignore leaks for a project

### ISSUE THREAD

**Issue by arirubinstein** [google/oss-fuzz#7708]
Hey oss-fuzz team - I'm attempting to disable leak detection for our target (xs) as it doesn't behave well with the xs allocator, however even with the xst.options file, I'm unable to get the setting to stay.  It appears that the options file is considered for `check_build` and `run_fuzzer`, but not for the actual run (bug  the `-detect_leaks=0` flag in the invocation in the [bug](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=47432).  Any tips on how to proceed?

```
Command: /mnt/scratch0/clusterfuzz/resources/platform/linux/unshare -c -n /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_xs_1ffa6a536ec3ca52d5b174208bbec24c24c3c194/revisions/xst -detect_leaks=0 -rss_limit_mb=2560 -timeout=60 -runs=100 /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Time ran: 6.084621906280518
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1103899258
INFO: Loaded 1 modules   (34422 inline 8-bit counters): 34422 [0xb04720, 0xb0cd96),
INFO: Loaded 1 PC tables (34422 PCs): 34422 [0x9e90e0,0xa6f840),
/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_xs_1ffa6a536ec3ca52d5b174208bbec24c24c3c194/revisions/xst: Running 1 inputs 100 time(s) each.
Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709
Executed /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-da39a3ee5e6b4b0d3255bfef95601890afd80709 in 6030 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
=================================================================
==281035==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 7200 byte(s) in 100 object(s) allocated from:
    #0 0x536cdd in __interceptor_malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:129:3
    #1 0x5d5546 in fxParserCode [moddable/xs/sources/xsCode.c:210](https://github.com/Moddable-OpenSource/moddable/blob/0983f59650960fb7a806a48c1ce5dd7da300ca44/xs/sources/xsCode.c#L210):11
    #2 0x78d8bb in fxParseScript [moddable/xs/sources/xsPlatforms.c:304](https://github.com/Moddable-OpenSource/moddable/blob/0983f59650960fb7a806a48c1ce5dd7da300ca44/xs/sources/xsPlatforms.c#L304):12
    #3 0x92a18f in fuzz_oss [moddable/xs/tools/xst.c:1854](https://github.com/Moddable-OpenSource/moddable/blob/0983f59650960fb7a806a48c1ce5dd7da300ca44/xs/tools/xst.c#L1854):21
    #4 0x9292a0 in LLVMFuzzerTestOneInput [moddable/xs/tools/xst.c:236](https://github.com/Moddable-OpenSource/moddable/blob/0983f59650960fb7a806a48c1ce5dd7da300ca44/xs/tools/xst.c#L236):5
    #5 0x4683f3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #6 0x454082 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #7 0x4598cc in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #8 0x4824c2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #9 0x7f2fc017b0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
```

**Comment by jonathanmetzman** [comment]
Ugh. I think you need to do something like this: https://github.com/google/oss-fuzz/blob/30f3a8f1c0f5b072e77d5bea82709db04c53453d/projects/firefox/target.c#L58
