### ISSUE TITLE
OOMs issues reported from ubsan build are less useful than from asan build

### ISSUE THREAD

**Issue by kcc** [google/oss-fuzz#774]
E.g. https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2710
ubsan can not provide a heap profile to show why we OOM. 
Should we report OOMs only from asan builds?

**Comment by Dor1s** [comment]
Would it be hard to implement heap profiling in UBSan?

**Comment by Dor1s** [comment]
One more question, why don't we call `__sanitizer_print_stack_trace` from `void Fuzzer::RssLimitCallback()`. I assume that we might get different stacktraces, as we would be crashing in a different places for different runs, but having that would allow us to collect some examples and probably implement some grouping for OOMs (https://github.com/google/oss-fuzz/issues/553).

**Comment by kcc** [comment]
asan's heap profiling is implemented in asan's heap allocator. 
ubsan is linked against the regular glibc allocator, which can't produce help profiles (AFIACT)
It's possible to link ubsan against asan's allocator but that will bring extra RAM overhead to the ubsan builds. Besides, it's still interesting to have a build with the glibc malloc in case there are bugs that only trigger with it.

**Comment by kcc** [comment]
RssLimitCallback is called from a separate thread, so you will only see that thread's stack trace (useless). 

BTW, for non-asan/msan builds we could use `ulimit -v 2048` instead of libFuzzer's rss_imit_mb and then rely on sig handlers to report a stack trace.

**Comment by Dor1s** [comment]
Ah, so we cannot get the stacktrace from another thread. Makes sense, thanks!

**Comment by kcc** [comment]
BTW, using `ulimit -v 2048` for ubsan builds is in fact a good idea. 
It will give us precise stack traces for OOMs (not heap allocations though) and it will catch cases when users mistakenly build with asan when SANITIZER=undefined (e.g. here: https://github.com/google/oss-fuzz/pull/765#issuecomment-322549161)

**Comment by Dor1s** [comment]
Using `ulimit` sounds reasonable! @oliverchang, is it doable with the current architecture?

**Comment by kcc** [comment]
`ulimit -v 2048000` of course. 
Example: 

```
clang -g -std=c++11 -fsanitize=undefined,fuzzer ~/Fuzzer/test/OutOfMemoryTest.cpp && (ulimit -v 2048000; ./a.out -rss_limit_mb=0)

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
==9506== ERROR: libFuzzer: deadly signal
    #0 0x411531 in fuzzer::Fuzzer::CrashCallback() (/usr/local/google/home/kcc/llvm-build/a.out+0x411531)
    #1 0x4114f0 in fuzzer::Fuzzer::StaticCrashSignalCallback()
    #2 0x7f1ba486d32f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1032f)
    #3 0x7f1ba3ba2c36 in gsignal 
    #4 0x7f1ba3ba6027 in abort 
    #5 0x7f1ba4adb534 in __gnu_cxx::__verbose_terminate_handler() 
    #6 0x7f1ba4ad96d5 in __cxxabiv1::__terminate(void (*)())v3/libsupc++/eh_terminate.cc:38
    #7 0x7f1ba4ad9702 in std::terminate()
    #8 0x7f1ba4ad9921 in __cxa_throw 
    #9 0x7f1ba4ad9e0c in operator new(unsigned long) 
    #10 0x7f1ba4ad9ea8 in operator new[](unsigned long) 
    #11 0x443b3b in LLVMFuzzerTestOneInput 
```

This is not the same as a heap profile, but still would often show where the RAM-hungry code is

**Comment by Dor1s** [comment]
That looks awesome!

**Comment by oliverchang** [comment]
Sure, we can do this. @Dor1s, may I ask you to take this?

And asking just in case, does it make sense to do this on libFuzzer's side instead?

**Comment by kcc** [comment]
Hmm... Yea, we could setrlimit inside libFuzzer too, if we see that there is no asan/msan. 
It will be a bit different result, e.g. if we see asan we won't set it. That's ok too. 

A caveat: libFuzzer may not necessary recognize the crash as OOM. 
But I'll see.

**Comment by oliverchang** [comment]
> A caveat: libFuzzer may not necessary recognize the crash as OOM.

Hmm, being able to distinguish easily is indeed important to us for reporting and performance analysis purposes. If libFuzzer can recognize it somehow it would be perfect.

I guess we'll have this problem too even if we set it on our side, unless we only do this to generate the final report, at which point we may as well use an  ASan build? (we have an existing mechanism in place for this).

**Comment by kcc** [comment]
Actually, giving this to @morehouse 

if rss_limit_mb != 0:
 * check if we don't have any tools that use shadow (check vm size?)
 * setrlimit for AS to rss_limit_mb
 * in the appropriate sig handler check if we died due to OOM and if so report OOM, not the signal.

**Comment by LebedevRI** [comment]
Just to add my 5 cent. There is a [heaptrack](https://github.com/KDE/heaptrack) tool, which can record memory allocations into file, and that file then can be processed and pretty-printed:
```
$ heaptrack ./src/utilities/rstest/rstest ~/raw-camera-samples/compressed-raf/20170525_0037TEST.RAF -f
heaptrack output will be written to "/home/lebedevri/rawspeed/build/heaptrack.rstest.8411.gz"
starting application, this might take some time...
/home/lebedevri/raw-camera-samples/compressed-raf/20170525_0037TEST.RAF: starting decoding ... 
/home/lebedevri/raw-camera-samples/compressed-raf/20170525_0037TEST.RAF:  50 MB /  596 ms
Total decoding time: 0.596s

All good, no tests failed!
heaptrack stats:
        allocations:            9357
        leaked allocations:     11
        temporary allocations:  10
Heaptrack finished! Now run the following to investigate the data:

  heaptrack_gui "/home/lebedevri/rawspeed/build/heaptrack.rstest.8411.gz"
$ heaptrack_print -f heaptrack.rstest.8411.gz --peak-limit=1 --sub-peak-limit=1
reading file "heaptrack.rstest.8411.gz" - please wait, this might take some time...
Debuggee command was: ./src/utilities/rstest/rstest /home/lebedevri/raw-camera-samples/compressed-raf/20170525_0037TEST.RAF -f
finished reading file, now analyzing data:

MOST CALLS TO ALLOCATION FUNCTIONS
1520 calls to allocation functions with 146.29KB peak consumption from
std::_Rb_tree_iterator<> std::_Rb_tree<>::_M_emplace_hint_unique<>(std::_Rb_tree_const_iterator<>, std::piecewise_construct_t const&, std::tuple<>&&, std::tuple<>&&)
  at /usr/include/c++/7/bits/stl_tree.h:2398
  in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
898 calls with 122.13KB peak consumption from:
    rawspeed::CameraMetaData::addCamera(std::unique_ptr<>)
      at /home/lebedevri/rawspeed/src/librawspeed/metadata/CameraMetaData.cpp:125
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::CameraMetaData::CameraMetaData(char const*)
      at /home/lebedevri/rawspeed/src/librawspeed/metadata/CameraMetaData.cpp:54
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    main
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:533
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
  and 622 from 6 other places


PEAK MEMORY CONSUMERS

WARNING - the data below is not an accurate calculation of the total peak consumption and can easily be wrong.
 For an accurate overview, disable backtrace merging.
164.57MB peak memory consumed over 2 calls from
rawspeed::alignedMalloc(unsigned long, unsigned long)
  at /home/lebedevri/rawspeed/src/librawspeed/common/Memory.cpp:62
  in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
114.46MB consumed over 1 calls from:
    rawspeed::RawImageData::createData()
      at /home/lebedevri/rawspeed/src/librawspeed/common/RawImage.cpp:94
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::RafDecoder::decodeRawInternal()
      at /home/lebedevri/rawspeed/src/librawspeed/decoders/RafDecoder.cpp:115
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::RawDecoder::decodeRaw()
      at /home/lebedevri/rawspeed/src/librawspeed/decoders/RawDecoder.cpp:304
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::rstest::process(std::__cxx11::basic_string<> const&, rawspeed::CameraMetaData const*, rawspeed::rstest::options const&)
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:379
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    main._omp_fn.0
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:543
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    GOMP_parallel
      in /usr/lib/x86_64-linux-gnu/libgomp.so.1
    main
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:562
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
  and 50.11MB from 1 other places

MOST TEMPORARY ALLOCATIONS
4 temporary allocations of 1184 allocations in total (0.34%) from
std::__cxx11::basic_string<>::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)
  in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
1 temporary allocations of 1 allocations in total (100.00%) from:
    std::__cxx11::basic_string<>::_M_append(char const*, unsigned long)
      in /usr/lib/x86_64-linux-gnu/libstdc++.so.6
    rawspeed::ColorFilterArray::asString[abi:cxx11]() const
      at /home/lebedevri/rawspeed/src/librawspeed/metadata/ColorFilterArray.cpp:125
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::ColorFilterArray::getDcrawFilter() const
      at /home/lebedevri/rawspeed/src/librawspeed/metadata/ColorFilterArray.cpp:219
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::RawImageData::subFrame(rawspeed::iRectangle2D)
      at /home/lebedevri/rawspeed/src/librawspeed/common/RawImage.cpp:240
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::RafDecoder::decodeMetaDataInternal(rawspeed::CameraMetaData const*)
      at /home/lebedevri/rawspeed/src/librawspeed/decoders/RafDecoder.cpp:317
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::RawDecoder::decodeMetaData(rawspeed::CameraMetaData const*)
      at /home/lebedevri/rawspeed/src/librawspeed/decoders/RawDecoder.cpp:327
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    rawspeed::rstest::process(std::__cxx11::basic_string<> const&, rawspeed::CameraMetaData const*, rawspeed::rstest::options const&)
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:381
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    main._omp_fn.0
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:543
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
    GOMP_parallel
      in /usr/lib/x86_64-linux-gnu/libgomp.so.1
    main
      at /home/lebedevri/rawspeed/src/utilities/rstest/rstest.cpp:562
      in /home/lebedevri/rawspeed/build/src/utilities/rstest/rstest
  and 3B from 10 other places


total runtime: 0.94s.
bytes allocated in total (ignoring deallocations): 167.75MB (178.84MB/s)
calls to allocation functions: 9357 (9975/s)
temporary memory allocations: 10 (10/s)
peak heap memory consumption: 165.60MB
peak RSS (including heaptrack overhead): 25.27MB
total memory leaked: 5.81KB
```

Something like that would be nicer to have.
But i do understand that it is rather specific and unlikely to happen :)

**Comment by morehouse** [comment]
>- check if we don't have any tools that use shadow (check vm size?)

Are you suggesting we check the RSS at some point in the libFuzzer startup and try to guess from that whether we have UBSan instrumentation or not?  This seems prone to breakage.

>- in the appropriate sig handler check if we died due to OOM and if so report OOM, not the signal.

We should be able to handle OOMs caused by `new` by setting a custom terminate handler to check for `std::bad_alloc`.

**Comment by kcc** [comment]
VSZ -- yes, RSS --no. 
ASAN uses 20Tb of VSZ, and MSAN more than that. So such check would be pretty reliable. 
If VSZ at startup is less than e.g. 1Gb we can safely assume that there is no asan and libFuzzer can use setrlimit(AS)

I'm not sure how bad_alloc will help us. setrlimit should be enough.

**Comment by morehouse** [comment]
> I'm not sure how bad_alloc will help us. setrlimit should be enough.

The problem is that the signal we get from OOM (typically SIGABRT) contains no indication as to what caused the signal.  We could call `GetPeakRSSMb` in the sig handler, but since the memory allocation just failed, the peak RSS will be less than the limit we set, so we won't be able to tell if we failed due to OOM or some other reason.  If we see a `bad_alloc` exception, then we will know that the memory allocation failed and can report OOM.

**Comment by kcc** [comment]
bad_alloc won't help in many cases (e.g. for all C targets). Besides, using bad_alloc means that it will collide with the user's bad_alloc. I would still try to do this w/o relying on bad alloc.

**Comment by morehouse** [comment]
I have an implementation for this on Linux.  But we only get a trace when `std::bad_alloc` is thrown (i.e. when the VSZ limit is hit during a `new`).  I get a backtrace on libFuzzer's OutOfMemoryTest.cpp, but only one of the benchmarks I've tried in https://github.com/google/fuzzer-test-suite/ gives a backtrace.  Instead, most give the below errors.
```
==186856==UndefinedBehaviorSanitizer's allocator is terminating the process instead of returning 0
==186856==If you don't like this behavior set allocator_may_return_null=1
==186856==Sanitizer CHECK failed: /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:225 ((0)) != (0) (0, 0)
```
```
==235411==ERROR: UndefinedBehaviorSanitizer failed to allocate 0x1000 (4096) bytes of ReadFileToBuffer (error code: 12)
ERROR: Failed to mmap
```

Is this still worthwhile to change in libFuzzer?  I don't think we would get a backtrace for the FFmpeg case in the OP.

**Comment by morehouse** [comment]
Also, now that I look at it... UBSan does implement `__sanitizer_print_stack_trace`.  Why don't we just use that?

**Comment by kcc** [comment]
>> ==186856==UndefinedBehaviorSanitizer's allocator is terminating 

How do you build? 
Looks like you have both asan and ubsan in the same process.

**Comment by morehouse** [comment]
```shell
FUZZING_ENGINE=fsanitize_fuzzer CFLAGS="-O2 -fno-omit-frame-pointer -g -fsanitize=undefined,fuzzer-no-link" CXXFLAGS="-O2 -fno-omit-frame-pointer -g -fsanitize=undefined,fuzzer-no-link" ../fuzzer-test-suite/freetype2-2017/build.sh 2>&1 | tee build.log
```
Doing `grep 'address' build.log` confirms no ASan.

**Comment by kcc** [comment]
can you reproduce `UndefinedBehaviorSanitizer's allocator is terminating` on a standalone small example?

**Comment by morehouse** [comment]
```c++
$ cat oom.cpp
#include <assert.h>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <thread>

static volatile char *SinkPtr;

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
  if (Size > 0 && Data[0] == 'H') {
    if (Size > 1 && Data[1] == 'i') {
      if (Size > 2 && Data[2] == '!') {
        while (true) {
          size_t kSize = 1 << 28;
          char *p = (char *) malloc(kSize);
          memset(p, 0, kSize);
          SinkPtr = p;
          std::this_thread::sleep_for(std::chrono::seconds(1));
        }
      }
    }
  }
  return 0;
}
$ clang++ -fsanitize=undefined,fuzzer oom.cpp -o oom
$ ./oom -rss_limit_mb=80
INFO: Seed: 1472089378
INFO: Loaded 1 modules   (78 inline 8-bit counters): 78 [0x667240, 0x66728e), 
INFO: Loaded 1 PC tables (78 PCs): 78 [0x458068,0x458548), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: A corpus is not provided, starting from an empty corpus
#2	INITED cov: 3 ft: 4 corp: 1/1b exec/s: 0 rss: 32Mb
#240	NEW    cov: 6 ft: 7 corp: 2/6b exec/s: 0 rss: 32Mb L: 5/5 MS: 3 ShuffleBytes-ChangeBit-CMP- DE: "H\x00\x00\x00"-
#276	REDUCE cov: 6 ft: 7 corp: 2/5b exec/s: 0 rss: 32Mb L: 4/4 MS: 1 EraseBytes-
#352	REDUCE cov: 6 ft: 7 corp: 2/3b exec/s: 0 rss: 32Mb L: 2/2 MS: 1 EraseBytes-
#488	REDUCE cov: 7 ft: 8 corp: 3/4b exec/s: 0 rss: 32Mb L: 1/2 MS: 1 EraseBytes-
#1305	NEW    cov: 8 ft: 9 corp: 4/6b exec/s: 0 rss: 32Mb L: 2/2 MS: 2 ShuffleBytes-InsertByte-
#1361	NEW    cov: 11 ft: 12 corp: 5/12b exec/s: 0 rss: 32Mb L: 6/6 MS: 1 PersAutoDict- DE: "H\x00\x00\x00"-
#1475	REDUCE cov: 11 ft: 12 corp: 5/11b exec/s: 0 rss: 32Mb L: 5/5 MS: 4 InsertByte-ChangeBit-InsertByte-EraseBytes-
#1577	REDUCE cov: 11 ft: 12 corp: 5/10b exec/s: 0 rss: 32Mb L: 4/4 MS: 2 ChangeBit-EraseBytes-
#1638	REDUCE cov: 11 ft: 12 corp: 5/9b exec/s: 0 rss: 32Mb L: 3/3 MS: 1 EraseBytes-
oom.cpp:18:18: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:62:62: note: nonnull attribute specified here
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==62707==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fa0d1a7d1cd bp 0x7ffdcda530d0 sp 0x7ffdcda52fd8 T62707)
==62707==The signal is caused by a WRITE memory access.
==62707==Hint: address points to the zero page.
==62707==UndefinedBehaviorSanitizer's allocator is terminating the process instead of returning 0
==62707==If you don't like this behavior set allocator_may_return_null=1
==62707==Sanitizer CHECK failed: /usr/local/google/home/mascasa/code/llvm/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_allocator.cc:225 ((0)) != (0) (0, 0)
MS: 1 InsertByte-; base unit: 94dd9e08c129c785f7f256e82fbe0a30e6d1ae40
0x48,0x69,0x21,
Hi!
artifact_prefix='./'; Test unit written to ./crash-c0a0ad26a634840c67a210fefdda76577b03a111
Base64: SGkh
```

**Comment by morehouse** [comment]
Without my `setrlimit` patch, you can reproduce by running
```shell
(ulimit -v 80000; ./oom -rss_limit_mb=0)
```

**Comment by kcc** [comment]
Ah, ok, I was afraid that somehow ubsan picks up asan's allocator or some such. 
Here, the `Sanitizer CHECK failed` is  not from a user malloc, but from an internal malloc which can't mmap due to rlimit. Yea, it's a bit of a problem indeed. If we set AS rlimit and actually reach it, we can't allocate any more memory inside the symbolizer... 

Bummer... Need to think more here. :(

**Comment by morehouse** [comment]
Can we automate the process of running UBSan OOM reproducers with ASan, then report the heap profile from ASan?

**Comment by alex** [comment]
FWIW, if you're considering automatically rerunning certain types of crashers with a different sanitizer, there's several other cases that would also be useful.
