### ISSUE TITLE
HttpError 400 when searching on crash-stats page

### ISSUE THREAD

**Issue by Lekensteyn** [google/oss-fuzz#789]
Visit https://oss-fuzz.com/v2/crash-stats?block=day&days=7&end=417632&group=platform&number=count&q=2&sort=total_count and observe the following trace:
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/v2/libs/handler.py", line 290, in wrapper
    return func(self, *args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/v2/handlers/crash_stats.py", line 208, in get
    result, params = get_result(self)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/v2/handlers/crash_stats.py", line 175, in get_result
    limit=PAGE_SIZE)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/v2/libs/crash_stats.py", line 50, in get
    limit=limit)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/common/crash_stats.py", line 149, in get
    query=sql, timeout=30, max_results=10000, offset=offset, limit=limit)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/common/big_query.py", line 176, in query
    result = self.raw_query(query, max_results=0)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/common/big_query.py", line 128, in raw_query
    projectId=self.project_id, body=body).execute()
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/common/lib/oauth2client/util.py", line 137, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/base/data/home/apps/s~clusterfuzz-external/1.403604842762202255/common/lib/googleapiclient/http.py", line 729, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 400 when requesting https://www.googleapis.com/bigquery/v2/projects/clusterfuzz-external/queries?alt=json returned "Syntax error: Expected "(" or keyword SELECT but got keyword AND at [16:287]">
```

**Comment by oliverchang** [comment]
@tanin47 could you please take a look at this?

**Comment by tanin47** [comment]
The fix for this error is being deployed.

**Comment by oliverchang** [comment]
Thanks! Looks like the fix has been deployed.
