### ISSUE TITLE
MSAN issue disappearing when adding -O0

### ISSUE THREAD

**Issue by ktmf01** [google/oss-fuzz#7898]
I'm having great difficulty debugging an MSAN crash, I hope someone here would be able to help.

In my local copy of libFLAC's metadata_iterators.c I have the following code

```
#include <sanitizer/msan_interface.h>
FLAC__bool copy_n_bytes_from_file_(FILE *file, FILE *tempfile, FLAC__off_t bytes, FLAC__Metadata_SimpleIteratorStatus *status)
{
        FLAC__byte buffer[8192];
        size_t n;

        FLAC__ASSERT(bytes >= 0);
        while(bytes > 0) {
                n = flac_min(sizeof(buffer), (size_t)bytes);
                if(fread(buffer, 1, n, file) != n) {
                        *status = FLAC__METADATA_SIMPLE_ITERATOR_STATUS_READ_ERROR;
                        return false;
                }
                __msan_print_shadow(buffer, 16);
                fprintf(stderr,"Read %u bytes of %u to do\n",n,bytes);
                if(local__fwrite(buffer, 1, n, tempfile) != n) {
                        *status = FLAC__METADATA_SIMPLE_ITERATOR_STATUS_WRITE_ERROR;
                        return false;
                }
                bytes -= n;
        }

        return true;
}
```

I reproduce with with ` python3 ~/bin/oss-fuzz/infra/helper.py reproduce flac fuzzer_metadata build/out/flac/minimized-from-822e6fb40928cc04fbe79632279605fe51e3dd4b` I get the following output:

```
Running: /testcase
Shadow map [0x2ffedfc8a630, 0x2ffedfc8a640) of [0x7ffedfc8a630, 0x7ffedfc8a640), 16 bytes:
0x2ffedfc8a630[0x7ffedfc8a630]: ffffffff ffffffff ffffffff ffffffff  |A A A A|

Origin A (origin_id 8000001e):
  Uninitialized value was created by an allocation of 'buffer.i.i' in the stack frame of function 'FLAC__metadata_chain_write'
    #0 0x5654f0 in FLAC__metadata_chain_write /src/flac/src/libFLAC/metadata_iterators.c:1739

DEDUP_TOKEN: FLAC__metadata_chain_write
Read 4 bytes of 4 to do
Uninitialized bytes in __interceptor_fwrite at offset 0 inside [0x7ffedfc8a630, 4)
==13==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x56689c in copy_n_bytes_from_file_ /src/flac/src/libFLAC/metadata_iterators.c:3278:6
    #1 0x56689c in chain_rewrite_file_ /src/flac/src/libFLAC/metadata_iterators.c:1447:6
    #2 0x56689c in FLAC__metadata_chain_write /src/flac/src/libFLAC/metadata_iterators.c:1770:7
    #3 0x554cf7 in FLAC::Metadata::Chain::write(bool, bool) /src/flac/src/libFLAC++/metadata.cpp:1619:29
    #4 0x52af70 in run_tests_with_level_2_interface /src/flac/oss-fuzz/fuzzer_metadata.cc:458:8
    #5 0x52af70 in LLVMFuzzerTestOneInput /src/flac/oss-fuzz/fuzzer_metadata.cc:83:2
    #6 0x454932 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #7 0x440ab2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #8 0x446214 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #9 0x46e212 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #10 0x7f92686dd0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
    #11 0x41f56d in _start (/out/fuzzer_metadata+0x41f56d)

DEDUP_TOKEN: copy_n_bytes_from_file_--chain_rewrite_file_--FLAC__metadata_chain_write
  Uninitialized value was created by an allocation of 'buffer.i.i' in the stack frame of function 'FLAC__metadata_chain_write'
    #0 0x5654f0 in FLAC__metadata_chain_write /src/flac/src/libFLAC/metadata_iterators.c:1739

DEDUP_TOKEN: FLAC__metadata_chain_write
SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/flac/src/libFLAC/metadata_iterators.c:3278:6 in copy_n_bytes_from_file_
Exiting
```

Notice that the stack frame of FLAC__metadata_chain_write is referenced. This is because this function is inlined. When inlining is disabled, the stack frame of copy_n_bytes_from_file_ is mentioned instead, but it crashes anyway.

When I add `-O0` to the CFLAGS and CXXFLAGS during compilation my output becomes:

```
[...]
Shadow map [0x2ffe6d01bff0, 0x2ffe6d01c000) of [0x7ffe6d01bff0, 0x7ffe6d01c000), 16 bytes:
0x2ffe6d01bff0[0x7ffe6d01bff0]: 00000000 ffffffff ffffffff ffffffff  |. A A A|

Origin A (origin_id 800001e4):
  Uninitialized value was created by an allocation of 'buffer' in the stack frame of function 'copy_n_bytes_from_file_'
    #0 0x5ff0d0 in copy_n_bytes_from_file_ /src/flac/src/libFLAC/metadata_iterators.c:3265

DEDUP_TOKEN: copy_n_bytes_from_file_
Read 4 bytes of 4 to do
Executed /testcase in 400 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```

I've added -O0 to the CFLAGS by adding this to the top of projects/flac/build.sh

```
export CFLAGS="$CFLAGS -O0"
export CXXFLAGS="$CXXFLAGS -O0"
```

I really do not understand how it is possible that the __msan_print_shadow output is different when -O0 is added.

**Comment by MarcoFalke** [comment]
You can try bisecting the optimization flags (all fine-grained flags that were disabled by `-O0`) to find the one that is responsible for the change in behaviour? This may allow a more educated guess.

**Comment by ktmf01** [comment]
@MarcoFalke This does not seem to be possible in general, [see this stackoverflow question](https://stackoverflow.com/questions/56010075/what-are-the-alternative-ways-to-customize-llvm-opt-pipeline)

**Comment by ktmf01** [comment]
Ok, found the solution. See https://github.com/google/sanitizers/issues/689 and https://github.com/google/sanitizers/issues/247 and in the [sanitizers FAQ](https://github.com/google/sanitizers/wiki/AddressSanitizer)

> - Q: I've compiled my code with -D_FORTIFY_SOURCE flag and ASan, or -D_FORTIFY_SOURCE is enabled by default in my distribution (most modern distributions). Now ASan misbehaves (either produces false warnings, or does not find some bugs).
> 
> - A: Currently ASan (and other sanitizers) doesn't support source fortification, see https://github.com/google/sanitizers/issues/247. The fix should most likely be on the glibc side, see the (stalled) discussion [here](http://www.sourceware.org/ml/libc-alpha/2016-09/msg00080.html).
