### ISSUE TITLE
golang: Different bugs for same stack trace

### ISSUE THREAD

**Issue by catenacyber** [google/oss-fuzz#7962]
It looks like the parsing of the stack trace is not so good 

cf
https://oss-fuzz.com/testcase-detail/5194651375108096
```
goroutine 17 [running, locked to thread]:
--
  | regexp.(*Regexp).Split(0x10c0000b2640, {0x10c000ac201f, 0x962c00}, 0xffffffffffffffff)
  | regexp/regexp.go:1266 +0x617
  | github.com/google/gonids.(*Rule).option(0x10c000066000, {0x0, {0x10c000ac2016, 0x10c000044000}}, 0x10c0001dc000)
  | github.com/google/gonids/parser.go:675 +0x36c5
  | github.com/google/gonids.parseRuleAux({0x10c000ac2000, 0x37a78}, 0x0)
  | github.com/google/gonids/parser.go:942 +0x6b3
  | github.com/google/gonids.ParseRule(...)
  | github.com/google/gonids/parser.go:971
  | github.com/google/gonids.FuzzParseRule({0x7f369cb75800, 0x0, 0x10c000000601})
  | github.com/google/gonids/fuzz.go:20 +0x54
  | main.LLVMFuzzerTestOneInput(...)
  | ./main.3953748960.go:21
```

Only the line `github.com/google/gonids.ParseRule(...)`is in red, recognized as a stack trace line if I understand correctly

vs
https://oss-fuzz.com/testcase-detail/5115516607397888
```
	
goroutine 17 [running, locked to thread]:
regexp.(*Regexp).Split(0x10c0000b6640, 0x10c000176a9f, 0x774bc0, 0xffffffffffffffff)
 regexp/regexp.go:1266 +0x61c
github.com/google/gonids.(*Rule).option(0x10c000084600, 0x1010000000050, 0x10c000176a96, 0x0, 0x7fb715876778)
 github.com/google/gonids/parser.go:675 +0x3705
github.com/google/gonids.parseRuleAux(0x10c000176a80, 0x62b0000cb200, 0x6600)
 github.com/google/gonids/parser.go:943 +0x6ce
github.com/google/gonids.ParseRule(...)
 github.com/google/gonids/parser.go:972
github.com/google/gonids.FuzzParseRule(0x62b0000cb200, 0x0, 0x1)
 github.com/google/gonids/fuzz.go:20 +0x54
main.LLVMFuzzerTestOneInput(...)
 ./main.834012382.go:21
AddressSanitizer:DEADLYSIGNAL
```

where 
```
regexp.(*Regexp).Split(0x10c0000b6640, 0x10c000176a9f, 0x774bc0, 0xffffffffffffffff)
github.com/google/gonids.(*Rule).option(0x10c000084600, 0x1010000000050, 0x10c000176a96, 0x0, 0x7fb715876778)
github.com/google/gonids.parseRuleAux(0x10c000176a80, 0x62b0000cb200, 0x6600)
```
are in red

cf https://github.com/golang/go/issues/49075
The changes in the stack trace format seems to come from https://github.com/golang/go/issues/49075

@oliverchang are you the one who knows about this stack trace parsing ?

**Comment by oliverchang** [comment]
I'll take a look tomorrow.
