### ISSUE TITLE
Github workflow hanging in clusterfuzz?

### ISSUE THREAD

**Issue by PJK** [google/oss-fuzz#8588]
I started seeing consistent repeated GH fuzzing workflow timeouts on https://github.com/PJK/libcbor caused by `google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master` overrunning `fuzz-seconds`, starting around September 23rd 2022.

Looking at the log, it seems that clusterfuzz is stuck waiting on input (??) 

```
[...]
/github/workspace/build-out/cbor_load_fuzzer -timeout=25 -rss_limit_mb=2560 -len_control=0 -seed=1337 -artifact_prefix=/tmp/tmpv98trfvl/ -max_total_time=14400 -print_final_stats=1 /github/workspace/cifuzz-corpus/cbor_load_fuzzer >fuzz-1.log 2>&1
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 96, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 92, in main
    return run_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 62, in run_fuzzers_entrypoint
    result = run_fuzzers.run_fuzzers(config)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 302, in run_fuzzers
    if not fuzz_target_runner.run_fuzz_targets():
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 130, in run_fuzz_targets
    result = self.run_fuzz_target(target)
  File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 245, in run_fuzz_target
    return fuzz_target_obj.fuzz()
  File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 188, in fuzz
    result = engine_impl.fuzz(self.target_path, options, artifacts_dir,
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 266, in fuzz
    fuzz_result = runner.fuzz(
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py", line 411, in fuzz
    return LibFuzzerCommon.fuzz(self, corpus_directories, fuzz_timeout,
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libfuzzer.py", line 228, in fuzz
    return self.run_and_wait(
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/system/new_process.py", line 406, in run_and_wait
    result = ProcessRunner.run_and_wait(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/system/new_process.py", line 390, in run_and_wait
    result = wait_process(
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/system/new_process.py", line 97, in wait_process
    output = process.communicate(input_data)[0]
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/system/new_process.py", line 164, in communicate
    line = self._popen.stdout.readline()
KeyboardInterrupt
Error: The operation was canceled.
```

- Workflow config: https://github.com/PJK/libcbor/blob/e87d5714e69214f187db225f23985aea51c52d28/.github/workflows/fuzz.yml
- Sample failed run: https://github.com/PJK/libcbor/actions/runs/3120941813/jobs/5061912055
- Logs attached: [logs_314.zip](https://github.com/google/oss-fuzz/files/9640922/logs_314.zip)

**Comment by jonathanmetzman** [comment]
Thanks for this report. Sorry but I have to be offline until the middle of this week but I can take a look after that

**Comment by PJK** [comment]
Any updates @jonathanmetzman ? Still seeing the same issue

**Comment by jonathanmetzman** [comment]
I think I can try a fix for this issue today.

**Comment by jonathanmetzman** [comment]
Or rather I can look into it.

**Comment by jonathanmetzman** [comment]
The code at fault seems to be ClusterFuzz's custom process handling code, which seems overly complex (i.e. intimidating to change) and calls process.stdout.readline which can hang http://thraxil.org/users/anders/posts/2008/03/13/Subprocess-Hanging-PIPE-is-your-enemy/ https://itecnote.com/tecnote/python-subprocess-readline-hangs-waiting-for-eof/

**Comment by oliverchang** [comment]
We don't call `process.stdout.readline`, and per https://docs.python.org/3/library/subprocess.html:

```
Warning Use communicate() rather than .stdin.write, .stdout.read or .stderr.read to avoid deadlocks due to any of the other OS pipe buffers filling up and blocking the child process.
```

It seems to imply that `communicate()` does not have such issues. Something else may be at play here.

**Comment by jonathanmetzman** [comment]
We do call readline directly as the stacktrace shows
```
  File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/system/new_process.py", line 164, in communicate
    line = self._popen.stdout.readline()
```
https://github.com/google/clusterfuzz/blob/ddfc7b6349406495e356b7c523076d23e4e0f182/src/clusterfuzz/_internal/system/new_process.py#L153
We are using our own version of communicate

**Comment by jonathanmetzman** [comment]
@alex Do you have any good python wizardry for getting a subprocess to write to a file and stdout (so a human can see something is running) simulatenously? Everything I can think of (find on stackoverflow) is kinda ugly or I'm not confident it will work.

**Comment by alex** [comment]
I think the two options I see are:

- Chain subprocess invocations so the stdout of your process goes to stdin of a `tee` process. Basically emulating `cmd | tee output.txt`
- Have a loop in python that reads stdout of your process and writes to both.

**Comment by PJK** [comment]
Works, thanks for the fast fix!
