### ISSUE TITLE
open62541 build is broken

### ISSUE THREAD

**Issue by jonathanmetzman** [google/oss-fuzz#903]
https://oss-fuzz-build-logs.storage.googleapis.com/log-ffcf3266-db08-4763-8e65-b085d8684b49.txt

Here is the failing build step:

```
Step #3: [ 15%] Generating src_generated/ua_namespace0.c, src_generated/ua_namespace0.h
Step #3: Traceback (most recent call last):
Step #3:   File "/src/open62541/tools/nodeset_compiler/nodeset_compiler.py", line 27, in <module>
Step #3:     from nodeset import *
Step #3:   File "/src/open62541/tools/nodeset_compiler/nodeset.py", line 28, in <module>
Step #3:     from nodes import *
Step #3:   File "/src/open62541/tools/nodeset_compiler/nodes.py", line 21, in <module>
Step #3:     from datatypes import *
Step #3:   File "/src/open62541/tools/nodeset_compiler/datatypes.py", line 29, in <module>
Step #3:     import six
Step #3: ImportError: No module named 'six'
Step #3: make[2]: *** [src_generated/ua_namespace0.c] Error 1
Step #3: CMakeFiles/open62541-generator-namespace.dir/build.make:68: recipe for target 'src_generated/ua_namespace0.c' failed
Step #3: CMakeFiles/Makefile2:301: recipe for target 'CMakeFiles/open62541-generator-namespace.dir/all' failed
Step #3: make[1]: *** [CMakeFiles/open62541-generator-namespace.dir/all] Error 2
Step #3: make: *** [all] Error 2
Step #3: Makefile:149: recipe for target 'all' failed
```

**Comment by oliverchang** [comment]
@Pro could you please take a look?
