### ISSUE TITLE
CIFuzz: hang while fetching coverage

### ISSUE THREAD

**Issue by kleisauke** [google/oss-fuzz#9079]
See: https://github.com/libvips/libvips/actions/runs/3559374300/jobs/5978684333. I cancelled it after 2+ hours running time.

The salient part of the log is:
<details>
  <summary>Details</summary>

```
[...]
2022-11-27 18:20:38,335 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): storage.googleapis.com:443
2022-11-27 18:20:38,462 - urllib3.connectionpool - DEBUG - [https://storage.googleapis.com:443](https://storage.googleapis.com/) "GET /oss-fuzz-coverage/libvips/fuzzer_stats/20221127/sharpen_fuzzer.json HTTP/1.1" 200 407499
Traceback (most recent call last):
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 60, in <module>
    sys.exit(main())
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 56, in main
    return build_fuzzers_entrypoint()
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers_entrypoint.py", line 39, in build_fuzzers_entrypoint
    if not build_fuzzers.build_fuzzers(config):
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers.py", line 171, in build_fuzzers
    return builder.build()
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers.py", line 134, in build
    if not method():
  File "/opt/oss-fuzz/infra/cifuzz/build_fuzzers.py", line 147, in remove_unaffected_fuzz_targets
    affected_fuzz_targets.remove_unaffected_fuzz_targets(
  File "/opt/oss-fuzz/infra/cifuzz/affected_fuzz_targets.py", line 58, in remove_unaffected_fuzz_targets
    affected_fuzz_targets = get_affected_fuzz_targets(coverage, fuzz_target_paths,
  File "/opt/oss-fuzz/infra/cifuzz/affected_fuzz_targets.py", line 110, in get_affected_fuzz_targets
    if is_fuzz_target_affected(coverage, fuzz_target_path, files_changed):
  File "/opt/oss-fuzz/infra/cifuzz/affected_fuzz_targets.py", line 82, in is_fuzz_target_affected
    covered_files = coverage.get_files_covered_by_target(fuzz_target)
  File "/opt/oss-fuzz/infra/cifuzz/get_coverage.py", line 50, in get_files_covered_by_target
    target_cov = self.get_target_coverage(target)
  File "/opt/oss-fuzz/infra/cifuzz/get_coverage.py", line 115, in get_target_coverage
    return http_utils.get_json_from_url(target_url)
  File "/opt/oss-fuzz/infra/cifuzz/http_utils.py", line 84, in get_json_from_url
    response = requests.get(url)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 697, in send
    r.content
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 831, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 753, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 628, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 567, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.8/dist-packages/urllib3/response.py", line 533, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "/usr/lib/python3.8/http/client.py", line 459, in read
    n = self.readinto(b)
  File "/usr/lib/python3.8/http/client.py", line 503, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
Error: The operation was canceled.
```
</details>

Which corresponds to this call stack:
https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/build_fuzzers.py#L147-L149
https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/affected_fuzz_targets.py#L58-L59
https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/affected_fuzz_targets.py#L82
https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/get_coverage.py#L115
https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/http_utils.py#L84

According to https://requests.readthedocs.io/en/stable/user/advanced/#timeouts, it seems that this may occur when the `timeout` parameter is omitted.
> Most requests to external servers should have a timeout attached, in case the server is not responding in a timely manner. By default, requests do not time out unless a timeout value is set explicitly. Without a timeout, your code may hang for minutes or more.

So, perhaps passing `timeout=10` to all `requests.get(...)` invocations in [`http_utils.py`](https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/http_utils.py) would prevent this? Given that this is fetching from Google Cloud Storage, a ten-second timeout is probably reasonable.

**Comment by jonathanmetzman** [comment]
> See: https://github.com/libvips/libvips/actions/runs/3559374300/jobs/5978684333. I cancelled it after 2+ hours running time.
> 
> The salient part of the log is:
> 
> Details
> Which corresponds to this call stack:
> 
> https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/build_fuzzers.py#L147-L149
> 
> 
> https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/affected_fuzz_targets.py#L58-L59
> 
> 
> https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/affected_fuzz_targets.py#L82
> 
> 
> https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/get_coverage.py#L115
> 
> 
> https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/http_utils.py#L84
> 
> According to https://requests.readthedocs.io/en/stable/user/advanced/#timeouts, it seems that this may occur when the `timeout` parameter is omitted.
> 
> > Most requests to external servers should have a timeout attached, in case the server is not responding in a timely manner. By default, requests do not time out unless a timeout value is set explicitly. Without a timeout, your code may hang for minutes or more.
> 
> So, perhaps passing `timeout=10` to all `requests.get(...)` invocations in [`http_utils.py`](https://github.com/google/oss-fuzz/blob/8114d2f85f5568ee3f549b767d250c4125489f5a/infra/cifuzz/http_utils.py) would prevent this? Given that this is fetching from Google Cloud Storage, a ten-second timeout is probably reasonable.

Thanks for this very thorough analysis. Let me try this!

**Comment by kleisauke** [comment]
Thanks!

> According to https://requests.readthedocs.io/en/stable/user/advanced/#timeouts, it seems that this may occur when the `timeout` parameter is omitted.
> 
> > [..] Without a timeout, your code may hang for minutes or more.

FWIW, it looks like https://requests.readthedocs.io/en/stable/user/quickstart/#timeouts emphasizes a indefinitely hang instead.
> [..] Failure to do so can cause your program to hang indefinitely
