### ISSUE TITLE
CIFuzz seems to be failing

### ISSUE THREAD

**Issue by evverx** [google/oss-fuzz#9151]
Looks like it fails to import `google.cloud.datastore_v1.services`

From https://github.com/systemd/systemd/pull/25653
```
2022-12-06T22:10:34.6460637Z 2022-12-06 22:10:34,645 - root - INFO - Running fuzzer: fuzz-dhcp-server-relay.
2022-12-06T22:10:34.6464986Z 2022-12-06 22:10:34,645 - root - INFO - Downloading corpus from OSS-Fuzz: https://storage.googleapis.com/systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/systemd_fuzz-dhcp-server-relay/public.zip
2022-12-06T22:10:34.6512787Z 2022-12-06 22:10:34,650 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): storage.googleapis.com:443
2022-12-06T22:10:34.7276096Z 2022-12-06 22:10:34,727 - urllib3.connectionpool - DEBUG - https://storage.googleapis.com:443 "GET /systemd-backup.clusterfuzz-external.appspot.com/corpus/libFuzzer/systemd_fuzz-dhcp-server-relay/public.zip HTTP/1.1" 200 1159042
2022-12-06T22:10:34.9439537Z 2022-12-06 22:10:34,943 - root - INFO - Starting fuzzing
2022-12-06T22:10:35.1642607Z Traceback (most recent call last):
2022-12-06T22:10:35.1643464Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 96, in <module>
2022-12-06T22:10:35.1643816Z     sys.exit(main())
2022-12-06T22:10:35.1644254Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 92, in main
2022-12-06T22:10:35.1644617Z     return run_fuzzers_entrypoint()
2022-12-06T22:10:35.1645377Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 62, in run_fuzzers_entrypoint
2022-12-06T22:10:35.1645778Z     result = run_fuzzers.run_fuzzers(config)
2022-12-06T22:10:35.1667229Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 302, in run_fuzzers
2022-12-06T22:10:35.1667645Z     if not fuzz_target_runner.run_fuzz_targets():
2022-12-06T22:10:35.1668356Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 130, in run_fuzz_targets
2022-12-06T22:10:35.1668711Z     result = self.run_fuzz_target(target)
2022-12-06T22:10:35.1669186Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 245, in run_fuzz_target
2022-12-06T22:10:35.1669562Z     return fuzz_target_obj.fuzz()
2022-12-06T22:10:35.1669992Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 175, in fuzz
2022-12-06T22:10:35.1670392Z     engine_impl = clusterfuzz.fuzz.get_engine(config_utils.DEFAULT_ENGINE)
2022-12-06T22:10:35.1670982Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/fuzz/__init__.py", line 38, in get_engine
2022-12-06T22:10:35.1671334Z     _initialize()
2022-12-06T22:10:35.1671809Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/fuzz/__init__.py", line 31, in _initialize
2022-12-06T22:10:35.1672236Z     init.run(include_private=False, include_lowercase=True)
2022-12-06T22:10:35.1672816Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/init.py", line 30, in run
2022-12-06T22:10:35.1673205Z     mod = importlib.import_module(
2022-12-06T22:10:35.1673539Z   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
2022-12-06T22:10:35.1673924Z     return _bootstrap._gcd_import(name[level:], package, level)
2022-12-06T22:10:35.1674293Z   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
2022-12-06T22:10:35.1674652Z   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
2022-12-06T22:10:35.1675038Z   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
2022-12-06T22:10:35.1675622Z   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
2022-12-06T22:10:35.1675997Z   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
2022-12-06T22:10:35.1676398Z   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2022-12-06T22:10:35.1677046Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 21, in <module>
2022-12-06T22:10:35.1677530Z     from clusterfuzz._internal.bot.fuzzers import dictionary_manager
2022-12-06T22:10:35.1678151Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/dictionary_manager.py", line 22, in <module>
2022-12-06T22:10:35.1678613Z     from clusterfuzz._internal.google_cloud_utils import storage
2022-12-06T22:10:35.1679227Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/google_cloud_utils/storage.py", line 30, in <module>
2022-12-06T22:10:35.1679679Z     from clusterfuzz._internal.datastore import locks
2022-12-06T22:10:35.1680243Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/datastore/locks.py", line 21, in <module>
2022-12-06T22:10:35.1680630Z     from google.cloud import ndb
2022-12-06T22:10:35.1681129Z   File "/usr/local/lib/python3.8/dist-packages/google/cloud/ndb/__init__.py", line 28, in <module>
2022-12-06T22:10:35.1681655Z     from google.cloud.ndb.client import Client
2022-12-06T22:10:35.1682188Z   File "/usr/local/lib/python3.8/dist-packages/google/cloud/ndb/client.py", line 26, in <module>
2022-12-06T22:10:35.1682693Z     from google.cloud.datastore_v1.services.datastore.transports import (
2022-12-06T22:10:35.1683261Z ModuleNotFoundError: No module named 'google.cloud.datastore_v1.services'
2022-12-06T22:10:35.4222009Z ##[group]Run actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
2022-12-06T22:10:35.4222273Z with:
2022-12-06T22:10:35.4222473Z   name: address-x86_64-artifacts
2022-12-06T22:10:35.4222683Z   path: ./out/artifacts
2022-12-06T22:10:35.4222871Z   if-no-files-found: warn
2022-12-06T22:10:35.4223066Z ##[endgroup]
2022-12-06T22:10:35.6713594Z ##[warning]No files were found with the provided path: ./out/artifacts. No artifacts will be uploaded.
2022-12-06T22:10:35.6863532Z Cleaning up orphan processes
```

**Comment by jonathanmetzman** [comment]
Thanks!
Can you retry this job. I think I've mitigated the issue.
However my mitigation will break CIFuzz for any project that depends on changes made to oss-fuzz in the last 4 days.

**Comment by jonathanmetzman** [comment]
Oliver here's a repro:
```
docker run -it --entrypoint /bin/bash gcr.io/oss-fuzz-base/cifuzz-base@sha256:f3e3c81ed35c8884c876b375eea68d3d0f489206a6d1d9489fc61d4c52c9ce5c
# python3
>>> import clusterfuzz.fuzz; engine_impl = clusterfuzz.fuzz.get_engine('libfuzzer')
...
ModuleNotFoundError: No module named 'google.cloud.datastore_v1.services'
```

**Comment by jonathanmetzman** [comment]
CC @oliverchang

**Comment by evverx** [comment]
Looking at https://github.com/systemd/systemd/actions/runs/3634367565 and https://github.com/systemd/systemd/actions/runs/3634482969 it seems CIFuzz can get past that point again. Thanks!

I'd go ahead and close this issue but I'm not sure whether you're planning to use it to track that `get_engine('libfuzzer')` bug.

**Comment by jonathanmetzman** [comment]
No problem! Yeah lets leave this open

**Comment by oliverchang** [comment]
Doing a diff of `pip list` before/after and manually downgrading things, it looks like `google-cloud-ndb==2.0.0` causes the issue. We just need to pin that back to 1.12.0

**Comment by rouault** [comment]
I also get the same issue with GDAL: https://github.com/OSGeo/gdal/actions/runs/3642968937/jobs/6150676162  . It is a bit weird: it was broken yesterday, got working again today but just got broken again

**Comment by jonathanmetzman** [comment]
Very weird. Somehow a disabled trigger ran again. Anyway I think I've remitigated this.
I should be able to land the actual fix soon.
