### ISSUE TITLE
brpc Coverage build fail.

### ISSUE THREAD

**Issue by 0x34d** [google/oss-fuzz#9154]
```
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: [/corpus/Fuzz_http.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/Fuzz_http.zip or
Step #5:         /corpus/Fuzz_http.zip.zip, and cannot find /corpus/Fuzz_http.zip.ZIP, period.
Step #5: Failed to unpack the corpus for Fuzz_http. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: [/corpus/Fuzz_json.zip]
Step #5:   End-of-central-directory signature not found.  Either this file is not
Step #5:   a zipfile, or it constitutes one disk of a multi-part archive.  In the
Step #5:   latter case the central directory and zipfile comment will be found on
Step #5:   the last disk(s) of this archive.
Step #5: unzip:  cannot find zipfile directory in one of /corpus/Fuzz_json.zip or
Step #5:         /corpus/Fuzz_json.zip.zip, and cannot find /corpus/Fuzz_json.zip.ZIP, period.
Step #5: Failed to unpack the corpus for Fuzz_json. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image brpc
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage brpc
Step #5: python infra/helper.py coverage brpc
Step #5: ********************************************************************************
Finished Step #5
ERROR
ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: step exited with non-zero status: 1
```

What I know,  I didn't use `Fuzz_http.zip` file.
My files are https://github.com/0x34d/oss-fuzz-bloat/tree/main/brpc
And operation work fine:
```
Step #3 - "compile-libfuzzer-coverage-x86_64": + pushd /src/oss-fuzz-bloat/brpc/
Step #3 - "compile-libfuzzer-coverage-x86_64": /src/oss-fuzz-bloat/brpc /src/brpc/build
Step #3 - "compile-libfuzzer-coverage-x86_64": + cp Fuzz_json_seed_corpus.zip /workspace/out/libfuzzer-coverage-x86_64/Fuzz_json_seed_corpus.zip
Step #3 - "compile-libfuzzer-coverage-x86_64": + cp Fuzz_http_seed_corpus.zip /workspace/out/libfuzzer-coverage-x86_64/Fuzz_http_seed_corpus.zip
Step #3 - "compile-libfuzzer-coverage-x86_64": + popd
```

**Comment by 0x34d** [comment]
And in new logs are.

```
Starting Step #5
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: Running Fuzz_json
Step #5: Running Fuzz_http
Step #5: Error occured while running Fuzz_json:
Step #5: Error occured while running Fuzz_http:
Step #5: INFO: Running with entropic power schedule (0xFF, 100).
Step #5: INFO: Seed: 1372032631
Step #5: MERGE-OUTER: 4185 files, 0 in the initial corpus, 0 processed earlier
Step #5: MERGE-OUTER: attempt 1
Step #5: INFO: Running with entropic power schedule (0xFF, 100).
Step #5: INFO: Seed: 1372077154
Step #5: INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
Step #5: MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge45.txt'
Step #5: MERGE-INNER: 4185 total files; 0 processed earlier; will process 4185 files now
Step #5: #1	pulse  exec/s: 0 rss: 49Mb
Step #5: #2	pulse  exec/s: 0 rss: 49Mb
Step #5: #4	pulse  exec/s: 0 rss: 49Mb
Step #5: #8	pulse  exec/s: 0 rss: 49Mb
Step #5: #16	pulse  exec/s: 0 rss: 49Mb
Step #5: #32	pulse  exec/s: 0 rss: 49Mb
Step #5: #64	pulse  exec/s: 0 rss: 49Mb
Step #5: #128	pulse  exec/s: 0 rss: 49Mb
Step #5: #256	pulse  exec/s: 0 rss: 49Mb
Step #5: #512	pulse  exec/s: 0 rss: 49Mb
Step #5: #1024	pulse  exec/s: 0 rss: 49Mb
Step #5: W1125 06:06:15.834053    53 /src/brpc/src/brpc/details/http_message.cpp:147] Invalid major_version=4


continue


Step #5: W1125 06:06:15.942561    53 /src/brpc/src/brpc/details/http_message.cpp:147] Invalid major_version=3
Step #5: W1125 06:06:15.942569    53 /src/brpc/src/brpc/details/http_message.cpp:147] InvINFO: Running with entropic power schedule (0xFF, 100).
Step #5: INFO: Seed: 1372027191
Step #5: MERGE-OUTER: 4291 files, 0 in the initial corpus, 0 processed earlier
Step #5: MERGE-OUTER: attempt 1
Step #5: INFO: Running with entropic power schedule (0xFF, 100).
Step #5: INFO: Seed: 1372070997
Step #5: INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 1048576 bytes
Step #5: MERGE-INNER: using the control file '/tmp/libFuzzerTemp.Merge37.txt'
Step #5: MERGE-INNER: 4291 total files; 0 processed earlier; will process 4291 files now
Step #5: #1	pulse  exec/s: 0 rss: 47Mb
Step #5: #2	pulse  exec/s: 0 rss: 47Mb
Step #5: #4	pulse  exec/s: 0 rss: 47Mb
Step #5: #8	pulse  exec/s: 0 rss: 47Mb
Step #5: #16	pulse  exec/s: 0 rss: 47Mb
Step #5: #32	pulse  exec/s: 0 rss: 47Mb
Step #5: #64	pulse  exec/s: 0 rss: 47Mb
Step #5: #128	pulse  exec/s: 0 rss: 47Mb
Step #5: #256	pulse  exec/s: 0 rss: 47Mb
Step #5: #512	pulse  exec/s: 0 rss: 47Mb
Step #5: #1024	pulse  exec/s: 0 rss: 47Mb
Step #5: #2048	pulse  exec/s: 0 rss: 47Mb
Step #5: #4096	pulse  exec/s: 0 rss: 47Mb
Step #5: #4291	DONE   exec/s: 0 rss: 53Mb
Step #5: UndefinedBehaviorSanitizer:DEADLYSIGNAL
Step #5: ==51==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address (pc 0x0000006bb8d1 bp 0x000000058297 sp 0x7ffd53a72470 T51)
Step #5: ==51==The signal is caused by a READ memory access.
Step #5: ==51==Hint: this fault was caused by a dereference of a high value address (see register values below).  Disassemble the provided pc to learn which register was used.
Step #5:     #0 0x6bb8d1 in __llvm_write_binary_ids (out/libfuzzer-coverage-x86_64/Fuzz_json+0x6bb8d1)
Step #5:     #1 0x6bad66 in lprofWriteDataImpl (out/libfuzzer-coverage-x86_64/Fuzz_json+0x6bad66)
Step #5:     #2 0x6bac1b in lprofWriteData (out/libfuzzer-coverage-x86_64/Fuzz_json+0x6bac1b)
Step #5:     #3 0x6b976d in writeFile InstrProfilingFile.c
Step #5:     #4 0x6b94d1 in __llvm_profile_write_file (out/libfuzzer-coverage-x86_64/Fuzz_json+0x6b94d1)
Step #5:     #5 0x7f10e58218a6  (/lib/x86_64-linux-gnu/libc.so.6+0x468a6) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
Step #5:     #6 0x7f10e5821a5f in exit (/lib/x86_64-linux-gnu/libc.so.6+0x46a5f) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
Step #5:     #7 0x4af838 in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:887:5
Step #5:     #8 0x4d8ed2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
Step #5:     #9 0x7f10e57ff082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
Step #5:     #10 0x4a02bd in _start (out/libfuzzer-coverage-x86_64/Fuzz_json+0x4a02bd)
Step #5: 
Step #5: DEDUP_TOKEN: __llvm_write_binary_ids--lprofWriteDataImpl--lprofWriteData
Step #5: UndefinedBehaviorSanitizer can not provide additional info.
Step #5: SUMMARY: UndefinedBehaviorSanitizer: SEGV (out/libfuzzer-coverage-x86_64/Fuzz_json+0x6bb8d1) in __llvm_write_binary_ids
Step #5: ==51==ABORTING
Step #5: MS: 0 ; base unit: 0000000000000000000000000000000000000000
Step #5: 
Step #5: 

```

**Comment by 0x34d** [comment]
There is no clear error that I, as a normal human, can understand.

**Comment by evverx** [comment]
> #0 0x6bb8d1 in __llvm_write_binary_ids (out/libfuzzer-coverage-x86_64/Fuzz_json+0x6bb8d1)

It looks like https://github.com/google/oss-fuzz/issues/6524. As far as I can remember it's usually caused by linking fuzz targets against shared libraries and switching to static libraries should probably fix it.

**Comment by 0x34d** [comment]
It's always shared libraries.
