### ISSUE TITLE
Fedora.37 Coveage command run Support.

### ISSUE THREAD

**Issue by 0x34d** [google/oss-fuzz#9234]
unable to Run `python infra/helper.py coverage --fuzz-target=FuzzStun coturn`  in Fedora.37

```
  import pipes
Traceback (most recent call last):
  File "/home/oblivion/project/oss-fuzz/infra/helper.py", line 1377, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/oblivion/project/oss-fuzz/infra/helper.py", line 190, in main
    result = coverage(args)
             ^^^^^^^^^^^^^^
  File "/home/oblivion/project/oss-fuzz/infra/helper.py", line 1077, in coverage
    if not download_corpora(args):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oblivion/project/oss-fuzz/infra/helper.py", line 1016, in download_corpora
    if args.public:
       ^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'public'
```

Note this all work, And an expected error comes out.
```
python infra/helper.py build_image coturn
python infra/helper.py build_fuzzers --sanitizer coverage coturn
python infra/helper.py check_build --sanitizer coverage coturn
```
Error due to not using `-fsanitize=fuzzer-no-link` :
```
ERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.

('/tmp/not-out/tmpmo9lqe_s/FuzzStunClient', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpmo9lqe_s/FuzzStunClient'], returncode=2, stdout=b'BAD BUILD: /tmp/not-out/tmpmo9lqe_s/FuzzStunClient does not seem to have coverage instrumentation.\nINFO: Running with entropic power schedule (0xFF, 100).\nINFO: Seed: 1337\nINFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes\nINFO: A corpus is not provided, starting from an empty corpus\n#2\tINITED exec/s: 0 rss: 29Mb\nERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.\nBAD BUILD: /tmp/not-out/tmpmo9lqe_s/FuzzStunClient seems to have either startup crash or exit:\n/tmp/not-out/tmpmo9lqe_s/FuzzStunClient -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null\nINFO: Running with entropic power schedule (0xFF, 100).\nINFO: Seed: 1337\nINFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes\nINFO: A corpus is not provided, starting from an empty corpus\n#2\tINITED exec/s: 0 rss: 29Mb\nERROR: no interesting inputs were found. Is the code instrumented for coverage? Exiting.\n', stderr=b''))
BAD BUILD: /tmp/not-out/tmpmo9lqe_s/FuzzStunClient does not seem to have coverage instrumentation.
```

**Comment by evverx** [comment]
I think this regression was introduced in 7556698dbc. I fixed it locally with
```diff
diff --git a/infra/helper.py b/infra/helper.py
index e1865c57..5cd31068 100755
--- a/infra/helper.py
+++ b/infra/helper.py
@@ -340,6 +340,10 @@ def get_parser():  # pylint: disable=too-many-statements
   coverage_parser.add_argument('--corpus-dir',
                                help='specify location of corpus'
                                ' to be used (requires --fuzz-target argument)')
+  coverage_parser.add_argument('--public',
+                               action='store_true',
+                               help='if set, will download public '
+                               'corpus using wget')
   coverage_parser.add_argument('project',
                                help='name of the project or path (external)')
   coverage_parser.add_argument('extra_args',
```
but haven't sent a PR yet.
