### ISSUE TITLE
ygot Fuzz Failing

### ISSUE THREAD

**Issue by wenovus** [google/oss-fuzz#9367]
https://github.com/openconfig/ygot/actions/runs/3859702213/jobs/6579479054
```
/usr/local/bin/compile_go_fuzzer: line 28: cd: /root/go/src/github.com/openconfig/ygot/exampleoc: No such file or directory
```

Looks similar to the failure that was fixed by https://github.com/google/oss-fuzz/pull/5476
```
Step #3: + compile_go_fuzzer ./exampleoc Fuzz fuzz_oc_unmarshall gofuzz
Step #3: /usr/local/bin/compile_go_fuzzer: line 28: cd: /root/go/src/./exampleoc: No such file or directory
```

**Comment by Alan32Liu** [comment]
Thanks, @wenovus.
I was not able to reproduce this issue locally with the following command under version of `OSS-Fuzz`, though:
```shell
python infra/helper.py check_build --sanitizer none --engine libfuzzer --architecture x86_64 ygot

INFO:root:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=none -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=go -e HELPER=True -v /usr/local/google/home/donggeliu/Code/oss-fuzz/build/out/ygot:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py.
Unable to find image 'gcr.io/oss-fuzz-base/base-runner:latest' locally
latest: Pulling from oss-fuzz-base/base-runner
846c0b181fff: Already exists
098536b25b62: Already exists
7f6305f557a8: Already exists
c7990df45336: Pull complete
5feb244454bd: Pull complete
aef6e001bcd5: Pull complete
5b697a09a15a: Pull complete
f1737a4dcaee: Pull complete
f849c8c4a10f: Pull complete
b8d47c76915a: Pull complete
437ffd8a2f80: Pull complete
b9b6fc49ea2a: Pull complete
4dc5612a310e: Pull complete
3cd585f8dbc5: Pull complete
0c8633bade86: Pull complete
Digest: sha256:8efa2159e83db816812a2120d572524c5d01999e71442c3cdb6e9f0322fe2414
Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-runner:latest
INFO: performing bad build checks for /tmp/not-out/tmpe188x_a_/fuzz_oc_unmarshall
INFO:root:Check build passed.
```

Maybe @oliverchang could provide more insight? Thanks!

**Comment by oliverchang** [comment]
@jonathanmetzman is this something specific to CIFuzz?

**Comment by jonathanmetzman** [comment]
If this keeps happening maybe add  `bad-build-check: false` to here: https://github.com/openconfig/ygot/blob/master/.github/workflows/cifuzz.yml#L6

**Comment by wenovus** [comment]
Thanks, we've already disabled the action.

**Comment by oliverchang** [comment]
Re the error pointed out in the original issue:

```
/usr/local/bin/compile_go_fuzzer: line 28: cd: /root/go/src/github.com/openconfig/ygot/exampleoc: No such file or directory
```

This is not an error, but rather a harmless warning. The target built successfully, but it looks like it instantly crashes on a 25 minute timeout:

```
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 1337
INFO: Loaded 1 modules   (120216 inline 8-bit counters): 120216 [0x2ad1028, 0x2aee5c0), 
INFO: Loaded 1 PC tables (120216 PCs): 120216 [0x10c000100000,0x10c0002d5980), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
ALARM: working on the last Unit for 25 seconds
       and the timeout value is 25 (use -timeout=N to change)
MS: 0 ; base unit: 0000000000000000000000000000000000000000


artifact_prefix='./'; Test unit written to ./timeout-da39a3ee5e6b4b0d3255bfef95601890afd80709
Base64: 
==194== ERROR: libFuzzer: timeout after 25 seconds
    #0 0x539091 in __sanitizer_print_stack_trace /src/llvm-project/compiler-rt/lib/asan/asan_stack.cpp:87:3
    #1 0x457ba8 in fuzzer::PrintStackTrace() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtil.cpp:210:5
    #2 0x43c7f9 in fuzzer::Fuzzer::AlarmCallback() /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:301:5
    #3 0x7f75b528f41f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1441f) (BuildId: 7b4536f41cdaa5888408e82d0836e33dcf436466)
    #4 0x5d5e42 in runtime.futex.abi0 runtime/sys_linux_amd64.s:559

DEDUP_TOKEN: __sanitizer_print_stack_trace--fuzzer::PrintStackTrace()--fuzzer::Fuzzer::AlarmCallback()
SUMMARY: libFuzzer: timeout

ERROR: 100.0% of fuzz targets seem to be broken. See the list above for a detailed information.
```

As @jonathanmetzman suggested, you can either disable the bad build check, or alternatively if this timeout is unexpected there may need to be a fix/workaround  made to the project to ensure fuzzing doesn't get stuck.

**Comment by jonathanmetzman** [comment]
@wenovus I think this is caused by differences in the hardware used by CIFuzz and OSS-Fuzz. The fix I mentioned (reproduced below) should work. I'd prefer if you reenabled CIFuzz, but either way I think this issue can be closed.
```
If this keeps happening maybe add bad-build-check: false to here: https://github.com/openconfig/ygot/blob/master/.github/workflows/cifuzz.yml#L6
```
