### ISSUE TITLE
Unable to access bug report

### ISSUE THREAD

**Issue by cfossace** [google/oss-fuzz#9716]
Hi, 

I am exploring this vulnerability https://oss-fuzz.com/testcase-detail/5738253143900160

But I am unable to reproduce it because I do not have access to this bug report. I do not think it has been fully patched, and am trying to work on a better patch. 

Thanks!

**Comment by oliverchang** [comment]
Hi, you should be able to download the reproducer via the link in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53137: https://oss-fuzz.com/download?testcase_id=5738253143900160

Since the reproducer is public now (and it can be easily reproduced, I'll paste the full stacktrace here):

```


INFO: Running with entropic power schedule (0xFF, 100).
--
  | INFO: Seed: 2779797729
  | INFO: Loaded 1 modules   (1036960 inline 8-bit counters): 1036960 [0x5826860, 0x5923b00),
  | INFO: Loaded 1 PC tables (1036960 PCs): 1036960 [0x5923b00,0x68f6500),
  | /mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_gdal_8f5d9038564387e8bdf28161d9e03f1ffb4dfbad/revisions/dimap_fuzzer: Running 1 inputs 100 time(s) each.
  | Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-51a1bf043fae2ef4bbfbe592fc9e90bce6f2968e
  | /src/gdal/frmts/gtiff/libtiff/tif_getimage.c:3019:52: runtime error: unsigned integer overflow: 31 * 926430463 cannot be represented in type 'unsigned int'
  | #0 0xb4aaa5 in gdal_TIFFReadRGBATileExt gdal/frmts/gtiff/libtiff/tif_getimage.c:3019:52
  | #1 0x707ba5 in GTiffRGBABand::IReadBlock(int, int, void*) gdal/frmts/gtiff/geotiff.cpp:8110:17
  | #2 0x8a729c in GDALRasterBand::GetLockedBlockRef(int, int, int) gdal/gcore/gdalrasterband.cpp:1365:20
  | #3 0x99e31e in GDALRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/gcore/rasterio.cpp:482:27
  | #4 0x6d81e9 in GTiffRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/frmts/gtiff/geotiff.cpp:5827:28
  | #5 0x12406b5 in GDALProxyRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/gcore/gdalproxydataset.cpp:291:30
  | #6 0x89fef6 in GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/gcore/gdalrasterband.cpp:377:16
  | #7 0xec9c01 in VRTSimpleSource::RasterIO(GDALDataType, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/frmts/vrt/vrtsources.cpp:1372:21
  | #8 0xea551f in VRTSourcedRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/frmts/vrt/vrtsourcedrasterband.cpp:344:35
  | #9 0x83e531 in DIMAPRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/frmts/dimap/dimapdataset.cpp:341:23
  | #10 0x89fef6 in GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) gdal/gcore/gdalrasterband.cpp:377:16
  | #11 0x8a0dd8 in GDALRasterIO gdal/gcore/gdalrasterband.cpp:411:21
  | #12 0x683e14 in GDALChecksumImage gdal/alg/gdalchecksum.cpp:194:21
  | #13 0x4d179d in LLVMFuzzerTestOneInput gdal/fuzzers/gdal_fuzzer.cpp:348:17
  | #14 0x436843 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
  | #15 0x421fa2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
  | #16 0x42784c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
  | #17 0x450d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
  | #18 0x7f2bfc9c40b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
  | #19 0x41816d in _start
  |  
  | SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /src/gdal/frmts/gtiff/libtiff/tif_getimage.c:3019:52 in

INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2779797729
INFO: Loaded 1 modules   (1036960 inline 8-bit counters): 1036960 [0x5826860, 0x5923b00),
INFO: Loaded 1 PC tables (1036960 PCs): 1036960 [0x5923b00,0x68f6500),
/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_gdal_8f5d9038564387e8bdf28161d9e03f1ffb4dfbad/revisions/dimap_fuzzer: Running 1 inputs 100 time(s) each.
Running: /mnt/scratch0/clusterfuzz/bot/inputs/fuzzer-testcases/crash-51a1bf043fae2ef4bbfbe592fc9e90bce6f2968e
/src/gdal/frmts/gtiff/libtiff/tif_getimage.c:3019:52: runtime error: unsigned integer overflow: 31 * 926430463 cannot be represented in type 'unsigned int'
    #0 0xb4aaa5 in gdal_TIFFReadRGBATileExt [gdal/frmts/gtiff/libtiff/tif_getimage.c:3019](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/frmts/gtiff/libtiff/tif_getimage.c#L3019):52
    #1 0x707ba5 in GTiffRGBABand::IReadBlock(int, int, void*) [gdal/frmts/gtiff/geotiff.cpp:8110](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/frmts/gtiff/geotiff.cpp#L8110):17
    #2 0x8a729c in GDALRasterBand::GetLockedBlockRef(int, int, int) [gdal/gcore/gdalrasterband.cpp:1365](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/gcore/gdalrasterband.cpp#L1365):20
    #3 0x99e31e in GDALRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/gcore/rasterio.cpp:482](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/gcore/rasterio.cpp#L482):27
    #4 0x6d81e9 in GTiffRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/frmts/gtiff/geotiff.cpp:5827](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/frmts/gtiff/geotiff.cpp#L5827):28
    #5 0x12406b5 in GDALProxyRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/gcore/gdalproxydataset.cpp:291](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/gcore/gdalproxydataset.cpp#L291):30
    #6 0x89fef6 in GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/gcore/gdalrasterband.cpp:377](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/gcore/gdalrasterband.cpp#L377):16
    #7 0xec9c01 in VRTSimpleSource::RasterIO(GDALDataType, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/frmts/vrt/vrtsources.cpp:1372](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/frmts/vrt/vrtsources.cpp#L1372):21
    #8 0xea551f in VRTSourcedRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/frmts/vrt/vrtsourcedrasterband.cpp:344](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/frmts/vrt/vrtsourcedrasterband.cpp#L344):35
    #9 0x83e531 in DIMAPRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/frmts/dimap/dimapdataset.cpp:341](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/frmts/dimap/dimapdataset.cpp#L341):23
    #10 0x89fef6 in GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) [gdal/gcore/gdalrasterband.cpp:377](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/gcore/gdalrasterband.cpp#L377):16
    #11 0x8a0dd8 in GDALRasterIO [gdal/gcore/gdalrasterband.cpp:411](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/gcore/gdalrasterband.cpp#L411):21
    #12 0x683e14 in GDALChecksumImage [gdal/alg/gdalchecksum.cpp:194](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/alg/gdalchecksum.cpp#L194):21
    #13 0x4d179d in LLVMFuzzerTestOneInput [gdal/fuzzers/gdal_fuzzer.cpp:348](https://github.com/OSGeo/gdal/blob/b24aa9a34855f90e0491d99551dedd72b5dbc994/fuzzers/gdal_fuzzer.cpp#L348):17
    #14 0x436843 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #15 0x421fa2 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:324:6
    #16 0x42784c in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:860:9
    #17 0x450d82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #18 0x7f2bfc9c40b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
    #19 0x41816d in _start
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /src/gdal/frmts/gtiff/libtiff/tif_getimage.c:3019:52 in
```
