### ISSUE TITLE
Confusing/non-reproducible crash from CIFuzz

### ISSUE THREAD

**Issue by randombit** [google/oss-fuzz#9814]
I'm running into a problem with CiFuzz where it reports a crash in a particular PR

```
==39==ERROR: AddressSanitizer: allocator is out of memory trying to allocate 0x2000000210 bytes
    #0 0x4e0a2d in operator new(unsigned long) /src/llvm-project/compiler-rt/lib/asan/asan_new_delete.cpp:95:3
    #1 0xb84419 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) (build-out/ocsp+0xb84419)
    #2 0x611dc1 in Botan::PK_Verifier::PK_Verifier(Botan::Public_Key const&, Botan::AlgorithmIdentifier const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) /src/botan/src/lib/pubkey/pubkey.cpp:328:15
    #3 0x54eb60 in Botan::X509_Object::verify_signature(Botan::Public_Key const&) const /src/botan/src/lib/x509/x509_obj.cpp:119:19
    #4 0x55a33b in Botan::(anonymous namespace)::parse_x509_cert_body(Botan::X509_Object const&) /src/botan/src/lib/x509/x509cert.cpp:311:41
```

https://github.com/randombit/botan/actions/runs/4282516603/jobs/7456893822

CIFuzz reports this a reproducible and in fact reports the same issue for 3 different fuzzers (which all internally have a callchain that ends up in this function which is crashing) and has done so across several runs in CI. This function is new in this PR. So far so good.

The problem is

a) I cannot reproduce the issue locally using libfuzzer. Apparently this triggers within 10K executions on CI, but I'm over two million execs locally with no crash.
b) The backtrace does not make any sense because on this line, we are not creating any kind of string, so I have no idea what is failing.

Any ideas or suggestions on debugging? At this point I'm half tempted to just merge it and let OSS-Fuzz proper pick up the issue (if it really is an issue) in the hopes that it will be easier to debug that way.

Specific request (beyond general request for advice): if the fuzzer fails in CIFuzz can the failing artifact be dumped into the log? That would probably make debugging this simpler.

**Comment by randombit** [comment]
I was able to diagnose by having the fuzzer printf the input before it ran. I was able to copy that from the job output and reproduce. I still don't understand why it reproed so quickly in CI but not at all locally.

The backtrace was also quite incorrect. Reproducing locally the backtrace showed where we actually crashed, which made diagnosis of the bug simple.

```
    #0 0x7fad515e948b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::_M_data() const /bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/basic_string.h:234:28
    #1 0x7fad515e948b in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../include/c++/12.2.1/bits/basic_string.h:544:21
    #2 0x7fad515e948b in Botan::(anonymous namespace)::parse_rsa_signature_algorithm[abi:cxx11](Botan::AlgorithmIdentifier const&) /home/jack/work/botan/src/lib/pubkey/rsa/rsa.cpp:759:26
    #3 0x7fad515e948b in Botan::RSA_PublicKey::create_x509_verification_op(Botan::AlgorithmIdentifier const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) const /home/jack/work/botan/src/lib/pubkey/rsa/rsa.cpp:815:60
    #4 0x7fad515cf07b in Botan::PK_Verifier::PK_Verifier(Botan::Public_Key const&, Botan::AlgorithmIdentifier const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>> const&) /home/jack/work/botan/src/lib/pubkey/pubkey.cpp:328:15
```

My immediate issue is resolved. But I think there are two things that could have been done to make this easier:

* If the fuzzer crashes in CiFuzz, print the input that caused the crash
* Fix the backtraces (I imagine this is non-trivial)

I'll leave this issue open in the hopes that one or both of the above might be addressed but feel free to close if you don't find them actionable.

**Comment by jonathanmetzman** [comment]
>If the fuzzer crashes in CiFuzz, print the input that caused the crash

We include it in the artifacts. see this page (https://github.com/randombit/botan/actions/runs/4282516603) it's the "summary page", press on the link that says artifacts. We probably should log this 

>Fix the backtraces (I imagine this is non-trivial)

No idea why this went wrong.
