### ISSUE TITLE
urllib3: Fuzzer missing from project coverage

### ISSUE THREAD

**Issue by sg3-141-592** [google/oss-fuzz#9863]
When reviewing the code coverage for urllib3 the coverage for `fuzz_requests.py` is missing from the report.

[https://storage.googleapis.com/oss-fuzz-introspector/urllib3/inspector-report/20230305/fuzz_report.html](https://storage.googleapis.com/oss-fuzz-introspector/urllib3/inspector-report/20230305/fuzz_report.html)

We can see `fuzz_requests` in the introspector report

<img width="659" alt="image" src="https://user-images.githubusercontent.com/5122866/222974999-97d90434-5d75-4f8d-b166-956597a18fcf.png">

but `fuzz_requests.py` isn't in the coverage report, and also the coverage from this fuzzer is missing in the report.

**Comment by DavidKorczynski** [comment]
I think is probably because the fuzzer is having some trouble running, am seeing this issue:

```
=== Uncaught Python exception: ===
  | MaxRetryError: HTTPConnectionPool(host='localhost', port=8011): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4687259b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
  | Traceback (most recent call last):
  | File "fuzz_requests.py", line 109, in TestOneInput
  | File "urllib3/_request_methods.py", line 118, in request
  | File "urllib3/_request_methods.py", line 217, in request_encode_body
  | File "urllib3/poolmanager.py", line 433, in urlopen
  | File "urllib3/connectionpool.py", line 874, in urlopen
  | File "urllib3/connectionpool.py", line 874, in urlopen
  | File "urllib3/connectionpool.py", line 874, in urlopen
  | File "urllib3/connectionpool.py", line 844, in urlopen
  | File "urllib3/util/retry.py", line 505, in increment
  | MaxRetryError: HTTPConnectionPool(host='localhost', port=8011): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4687259b80>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

This probably affects such that the fuzzer either failed to generate corpus or was not run in a manner such that atheris was exited proper (sys.exit(0)) which is needed for coverage runs.

**Comment by sg3-141-592** [comment]
Thanks for finding this @DavidKorczynski . I'll do some research on where the issue is occurring.

I can run this locally on my Ubuntu 20.04 setup without exception, so it's likely to be an environment difference I've not accounted for.

I couldn't find the exception you've shared on the introspector reports or this build dashboard [https://oss-fuzz-build-logs.storage.googleapis.com/index.html#urllib3](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#urllib3). How did you see this exception?

**Comment by DavidKorczynski** [comment]
This was an issue reported by OSS-Fuzz to the list of emails in the `project.yaml`. Basically, it's reported as a "bug found by the fuzzer" because it breaks the fuzzer execution.

To get experience with the end-to-end OSS-Fuzz approach I think a good approach is to carry out an initial integration of some project where you've reached out the maintainers beforehand to ask if it's okay for you to see potential issues being raised. If the maintainers are happy with this then you can put your email in the `project.yaml` and see e.g. all logs + issues being raised.
